table D_Calendario
	lineageTag: d6a21c89-f4cc-41c2-ad78-28846398781d

	measure 'Tem Dados Discador' = ```
			
			    // Verifica se existe registro da tabela F_Discador
			    // no contexto atual de data.
			
			    IF(
			        COUNTROWS(F_Discador) > 0,
			        1,
			        BLANK()
			    )
			```
		formatString: 0
		lineageTag: a8fd56fa-74bf-4ca8-90d5-ee5212721999

	measure 'Tem Dados YUZAP' = ```
			
			    // Verifica se existe registro da tabela F_Discador
			    // no contexto atual de data.
			
			    IF(
			        COUNTROWS(F_Yuzap_Conversas) > 0,
			        1,
			        BLANK()
			    )
			```
		formatString: 0
		lineageTag: 0c54640e-48f1-4d3d-9ad2-9064d3e94a23

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 96015bdb-f13f-4f0c-baed-f80c922983e5
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: ced5da8a-a079-4541-9ba6-ec6b862f09b5
			defaultHierarchy: LocalDateTable_5056a06b-5a7e-4bc0-8ba5-9d0e00270da5.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: c146245d-118c-4c9a-b4df-054d2db04854
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: 2350e21f-4688-461a-b7a3-0b66bee851e9
		summarizeBy: sum
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: ddc0821f-f094-4132-9bc3-dc984578bba2
		summarizeBy: none
		sourceColumn: Nome do Mês

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: 437e25e9-fd76-452c-a392-8769562d52fb
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: f412faf8-e6ee-44c7-9527-50c3d9edba08
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	column 'Nome do Dia'
		dataType: string
		lineageTag: a735b0ce-1cb7-474a-9ba6-ffe86088b8b0
		summarizeBy: none
		sourceColumn: Nome do Dia

		annotation SummarizationSetBy = Automatic

	column Mês/Ano
		dataType: string
		lineageTag: 23f5e231-d64e-45e7-808c-1c0e60bd0d6a
		summarizeBy: none
		sourceColumn: Mês/Ano
		sortByColumn: 'MesAno Ordem'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'MesAno Ordem' =
			
			YEAR(D_Calendario[Data]) * 100 + MONTH(D_Calendario[Data])
		formatString: 0
		lineageTag: af177825-b109-4fef-bdce-c1b3633a0e7c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition D_Calendario = m
		mode: import
		source =
				let
				    Fonte = Consulta1(#date(2024, 1, 1), 5000, #duration(1, 0, 0, 0)),
				    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Convertido para Tabela",{{"Column1", type date}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Column1", "Data"}}),
				    #"Ano Inserido" = Table.AddColumn(#"Colunas Renomeadas", "Ano", each Date.Year([Data]), Int64.Type),
				    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([Data]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Mês Inserido", "Nome do Mês", each Date.MonthName([Data]), type text),
				    #"Trimestre Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Trimestre", each Date.QuarterOfYear([Data]), Int64.Type),
				    #"Dia Inserido" = Table.AddColumn(#"Trimestre Inserido", "Dia", each Date.Day([Data]), Int64.Type),
				    #"Nome do Dia Inserido" = Table.AddColumn(#"Dia Inserido", "Nome do Dia", each Date.DayOfWeekName([Data]), type text),
				    #"Coluna Personalizada Adicionada" = Table.AddColumn(#"Nome do Dia Inserido", "Mês/Ano", each Text.Combine({Text.Start(Text.Proper([Nome do Mês]), 3), "/", Text.From([Ano], "pt-BR")}), type text)
				in
				    #"Coluna Personalizada Adicionada"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

