table 'Medidas Gráficos Discador'
	lineageTag: 0f17c257-4eae-4aa7-8078-61b69bd96afc

	measure Tabulacoes = ```
			
			    COUNTROWS(F_Discador)
			```
		formatString: 0
		lineageTag: cd5f7997-8e7b-4dcc-be12-180ad36debd4

	partition 'Medidas Gráficos Discador' = m
		mode: import
		queryGroup: Discador
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

