table 'Medidas KPIS Discador'
	lineageTag: b2c08a6e-a3e3-4104-ac40-d8c28d3f8832

	measure 'Tempo Médio(seg)' =
			
			COALESCE(
			    AVERAGEX(
			        FILTER(
			            F_Discador,
			            NOT ISBLANK(F_Discador[duracao]) &&
			            F_Discador[duracao] > 0
			        ),
			        F_Discador[duracao]
			    ),
			    0
			)
		lineageTag: a6253f47-69d2-40b1-800d-b9815ef1c990

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tempo Médio Atendimento (mm:ss)' =
			
			VAR SegundosMedios = [Tempo Médio(seg)]
			VAR Minutos = INT(SegundosMedios / 60)
			VAR Segundos = MOD(ROUND(SegundosMedios, 0), 60)
			
			RETURN
			    FORMAT(Minutos, "00") & ":" & FORMAT(Segundos, "00")
		lineageTag: 9ba6e1f0-3131-460e-b6d8-50436eae3127

	measure 'Média Tentativas até Alô' =
			
			COALESCE(
			    AVERAGEX(
			        FILTER(
			            F_Discador,
			            F_Discador[status] = "Sucesso" &&
			            F_Discador[tentativas] > 0
			        ),
			        F_Discador[tentativas]
			    ),
			    0
			)
		lineageTag: fd0a4c2c-fd2e-4b0e-9833-b0e11dfa609b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aptos do Discador que Não Chegaram no Yuzap' = ```
			
			    // Conta os telefones únicos da dimensão D_Telefone
			    // que possuem registro apto no Discador
			    // e não possuem registro no Yuzap.
			
			    COALESCE(
			        COUNTROWS(
			            FILTER(
			                VALUES(D_Telefone[Telefone]),
			                CALCULATE(
			                    COUNTROWS(F_Discador),
			                    NOT ISBLANK(F_Discador[tabulacao_01]),
			                    NOT F_Discador[tabulacao_01] IN {
			                        "Segmento_inapto",
			                        "cnpj_inativo",
			                        "Compra efetuada pela central",
			                        "Estabelecimento Fechou"
			                    }
			                ) > 0
			                &&
			                CALCULATE(
			                    COUNTROWS(F_Yuzap_Conversas)
			                ) = 0
			            )
			        ),
			        0
			    )
			```
		formatString: 0
		lineageTag: 0395a13a-0702-43a4-9e4b-cd1853427c0a

	partition 'Medidas KPIS Discador' = m
		mode: import
		queryGroup: Discador
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

