table 'Medidas YUZAP KPIS'
	lineageTag: eb0da095-383b-4651-89d9-cc9d8199eef3

	measure 'Leads Únicos Yuzap' = ```
			
			VAR Contagem = 
			    CALCULATE(
			        DISTINCTCOUNT(F_Yuzap_Conversas[ID]),
			        KEEPFILTERS(F_Yuzap_Conversas[Labels] <> "func_frigo")
			    )
			RETURN 
			    COALESCE(Contagem, 0)
			```
		formatString: 0
		lineageTag: 7954a177-c639-4678-a7e7-c9def77336da

	measure 'MoM % Leads Únicos Yuzap Texto' =
			
			VAR TemMes =
			    HASONEVALUE(D_Calendario[Mês/Ano])
			
			VAR MomValor =
			    DIVIDE(
			        [Leads Únicos Yuzap] -
			            CALCULATE(
			                [Leads Únicos Yuzap],
			                DATEADD(D_Calendario[Data], -1, MONTH)
			            ),
			        CALCULATE(
			            [Leads Únicos Yuzap],
			            DATEADD(D_Calendario[Data], -1, MONTH)
			        ),
			        BLANK()
			    )
			
			VAR MomTruncado =
			    TRUNC(MomValor * 100, 0) / 100
			
			RETURN
			IF(
			    NOT TemMes,
			    BLANK(),
			    IF(
			        ISBLANK(MomTruncado),
			        "0%",
			        IF(
			            MomTruncado > 0,
			            "+" & FORMAT(MomTruncado, "0%"),
			            FORMAT(MomTruncado, "0%")
			        )
			    )
			)
		lineageTag: a4e53fc0-2496-4f1e-8c47-57bea0a612cf

	measure 'Clientes Aptos' = ```
			
			    // Conta os contatos únicos do Yuzap considerados aptos.
			   
			
			    COALESCE(
			        CALCULATE(
			            DISTINCTCOUNT(F_Yuzap_Conversas[ID]),
			            F_Yuzap_Conversas[Labels] IN {
			                "cadastro_ativo",
			                "documentação_cadastro",
			                "entrar_contato",
			                "prazo_limite_preço",
			                "reativação",
			                "venda",
			                "Linha_Angus"
			
			
			            }
			        ),
			        0
			    )
			```
		formatString: 0
		lineageTag: a05202ff-aad9-4229-9811-9a6df6f93282

	measure '% Clientes Aptos' =
			
			DIVIDE(
			    [Clientes Aptos],
			    [Leads Únicos Yuzap],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9855c9f4-2553-4a5e-a846-b536792333c8

	measure 'Leads Migrados para WhatsApp' = ```
			
			    // Conta os telefones da dimensão que aparecem tanto no Discador quanto no Yuzap.
			    // Essa medida representa os leads que efetivamente passaram do canal de voz para o WhatsApp.
			    // EXCLUI conversas com Label 'func_frigo' (funcionários do frigorífico).
			    COALESCE(
			        COUNTROWS(
			            FILTER(
			                VALUES(D_Telefone[Telefone]),
			                CALCULATE(COUNTROWS(F_Discador)) > 0 &&
			                CALCULATE(
			                    COUNTROWS(F_Yuzap_Conversas),
			                    KEEPFILTERS(F_Yuzap_Conversas[Labels] <> "func_frigo")
			                ) > 0
			            )
			        ),
			        0
			    )
			
			```
		formatString: 0
		lineageTag: 8961666a-b511-43bf-8466-5637b91dedb6

	measure '% Leads Migrados para WhatsApp' =
			
			DIVIDE(
			    [Leads Migrados para WhatsApp],
			    [Leads Únicos Yuzap],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 95b013a7-852c-4688-97dc-e84b83f67956

	measure 'Clientes com Venda' = ```
			
			    // Conta clientes com etiqueta ativo_venda.
			    // Representa clientes que já possuem cadastro ativo e realizaram uma venda.
			
			    COALESCE(
			        CALCULATE(
			            DISTINCTCOUNT(F_Yuzap_Conversas[ID]),
			            F_Yuzap_Conversas[Labels] = "venda"
			        ),
			        0
			    )
			```
		formatString: 0
		lineageTag: e84d510d-fbb3-4166-9a85-0428715da0e3

	measure '% Clientes com Venda sobre Aptos' =
			
			DIVIDE(
			    [Clientes com Venda],
			    [Clientes Aptos],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 50b0f32b-4d1a-46e0-bafc-dc76bfb0ef20

	measure 'Clientes Inaptos' = ```
			
			    // Conta os contatos únicos do Yuzap considerados aptos.
			   
			
			    COALESCE(
			        CALCULATE(
			            DISTINCTCOUNT(F_Yuzap_Conversas[ID]),
			            F_Yuzap_Conversas[Labels] IN {
			                "segmento_inapto",
			                "cnpj_inativo"
			
			
			            }
			        ),
			        0
			    )
			```
		formatString: 0
		lineageTag: 36274b91-8cac-4485-816f-fc6564aa4c1e

	/// JSON com dados dos 4 KPIs do HTML Yuzap: leads+MoM, aptos+%, discador+%, venda+%. Responde a slicers.
	measure '_JSON KPIs Yuzap' =
			"{""leads"":" & COALESCE([Leads Únicos Yuzap], 0) &
			",""mom"":""" & COALESCE([MoM % Leads Únicos Yuzap Texto], "--") & """" &
			",""aptos"":" & COALESCE([Clientes Aptos], 0) &
			",""pctAptos"":" & SUBSTITUTE(FORMAT(COALESCE([% Clientes Aptos], 0) * 100, "0.0"), ",", ".") &
			",""discador"":" & COALESCE([Leads Migrados para WhatsApp], 0) &
			",""pctDiscador"":" & SUBSTITUTE(FORMAT(COALESCE([% Leads Migrados para WhatsApp], 0) * 100, "0.0"), ",", ".") &
			",""venda"":" & COALESCE([Clientes com Venda], 0) &
			",""pctVendaAptos"":" & SUBSTITUTE(FORMAT(COALESCE([% Clientes com Venda sobre Aptos], 0) * 100, "0.0"), ",", ".") &
			"}"
		displayFolder: HTML Yuzap
		lineageTag: 5eab7f85-1d00-4ff6-8344-392a21d684b6

	partition 'Medidas YUZAP KPIS' = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

