table 'Medidas Visão Executiva'
	lineageTag: 13a474d7-56fe-43ba-bf44-819cb0738937

	measure 'Faturamento Total' =
			
			SUM(DCVVQ_VENDAGERALTELEVENDAS[VLRVENDA])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 46bc0039-2c5d-46d7-b3cb-8e252102b465

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Peso Total Vendido' =
			
			SUM(DCVVQ_VENDAGERALTELEVENDAS[PESOVENDA])
		lineageTag: 19eedd4f-7578-458a-b2ca-6fa43bccb7ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ticket Mediano' =
			
			MEDIANX(
			    VALUES(DCVVQ_VENDAGERALTELEVENDAS[NROPEDIDO]),
			    CALCULATE(SUM(DCVVQ_VENDAGERALTELEVENDAS[VLRVENDA]))
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: be77a2e3-572a-431c-b284-f75fd2f2b915

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Total Devoluções (R$)' =
			
			SUM(DCVVQ_VENDAGERALTELEVENDAS[VLRDEVOLUCAO])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: bfb56861-6ffe-430a-847d-60d0a6c94ab9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Peso Total Devolvido' =
			
			SUM(DCVVQ_VENDAGERALTELEVENDAS[PESODEVOLVIDO])
		lineageTag: 9cfb6e06-242e-4127-85ac-a7eb2414179e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total de Pedidos' =
			
			DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[NROPEDIDO])
		formatString: 0
		lineageTag: 1a3d43aa-93f6-4238-87d8-8d366d5dbab1

	measure 'Total de Itens' =
			
			COUNTROWS(DCVVQ_VENDAGERALTELEVENDAS)
		formatString: 0
		lineageTag: f4eaca59-54dc-44c1-b3ba-15c7a4be4229

	measure 'Total Clientes Ativos' =
			
			DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
		formatString: 0
		lineageTag: 38867db5-632b-494c-a250-56ce3a6968ed

	measure 'Faturamento Mês Anterior' =
			
			CALCULATE(
			    [Faturamento Total],
			    DATEADD(D_Calendario[Data], -1, MONTH)
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: a77007f5-6842-4d4f-beb7-9efbd37fe2d6

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Variação MoM Faturamento' =
			
			[Faturamento Total] - [Faturamento Mês Anterior]
		lineageTag: 89eb7e31-185f-45c9-a62e-2f5cf4aa31e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM Faturamento %' =
			
			VAR FaturamentoAtual =
			    SUM(DCVVQ_VENDAGERALTELEVENDAS[VLRVENDA])
			
			VAR FaturamentoMesAnterior =
			    CALCULATE(
			        SUM(DCVVQ_VENDAGERALTELEVENDAS[VLRVENDA]),
			        DATEADD(D_Calendario[Data], -1, MONTH)
			    )
			
			VAR Variacao =
			    DIVIDE(
			        FaturamentoAtual - FaturamentoMesAnterior,
			        FaturamentoMesAnterior,
			        0
			    )
			
			RETURN
			FORMAT(Variacao, "+0.0%;-0.0%;0.0%")
		lineageTag: fa5b6149-42c0-4db4-9082-84f84536ddc8

	measure 'MoM Peso Total Vendido %' =
			
			VAR PesoAtual =
			    SUM(DCVVQ_VENDAGERALTELEVENDAS[PESOVENDA])
			
			VAR PesoMesAnterior =
			    CALCULATE(
			        SUM(DCVVQ_VENDAGERALTELEVENDAS[PESOVENDA]),
			        DATEADD(D_Calendario[Data], -1, MONTH)
			    )
			
			VAR Variacao =
			    DIVIDE(
			        PesoAtual - PesoMesAnterior,
			        PesoMesAnterior,
			        0
			    )
			
			RETURN
			FORMAT(Variacao, "+0.0%;-0.0%;0.0%")
		lineageTag: 1d350221-b51e-481d-8efa-e45844fc1911

	measure 'MoM Ticket Mediano %' =
			
			VAR TicketAtual =
			    MEDIANX(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[NROPEDIDO]),
			        CALCULATE(
			            SUM(DCVVQ_VENDAGERALTELEVENDAS[VLRVENDA])
			        )
			    )
			
			VAR TicketMesAnterior =
			    CALCULATE(
			        MEDIANX(
			            VALUES(DCVVQ_VENDAGERALTELEVENDAS[NROPEDIDO]),
			            CALCULATE(
			                SUM(DCVVQ_VENDAGERALTELEVENDAS[VLRVENDA])
			            )
			        ),
			        DATEADD(D_Calendario[Data], -1, MONTH)
			    )
			
			VAR Variacao =
			    DIVIDE(
			        TicketAtual - TicketMesAnterior,
			        TicketMesAnterior,
			        0
			    )
			
			RETURN
			FORMAT(Variacao, "+0.0%;-0.0%;0.0%")
		lineageTag: fca0eae3-25d9-4c75-ba8f-43a394a37e57

	measure 'MoM Devoluções %' =
			
			VAR DevolucaoAtual =
			    SUM(DCVVQ_VENDAGERALTELEVENDAS[VLRDEVOLUCAO])
			
			VAR DevolucaoMesAnterior =
			    CALCULATE(
			        SUM(DCVVQ_VENDAGERALTELEVENDAS[VLRDEVOLUCAO]),
			        DATEADD(D_Calendario[Data], -1, MONTH)
			    )
			
			VAR Variacao =
			    DIVIDE(
			        DevolucaoAtual - DevolucaoMesAnterior,
			        DevolucaoMesAnterior,
			        0
			    )
			
			RETURN
			FORMAT(Variacao, "+0.0%;-0.0%;0.0%")
		lineageTag: 0913daf7-50f9-4327-91fd-9eb9c4a5b6c8

	measure 'MoM Peso Total Devolvido %' =
			
			VAR PesoDevolvidoAtual =
			    SUM(DCVVQ_VENDAGERALTELEVENDAS[PESODEVOLVIDO])
			
			VAR PesoDevolvidoMesAnterior =
			    CALCULATE(
			        SUM(DCVVQ_VENDAGERALTELEVENDAS[PESODEVOLVIDO]),
			        DATEADD(D_Calendario[Data], -1, MONTH)
			    )
			
			VAR Variacao =
			    DIVIDE(
			        PesoDevolvidoAtual - PesoDevolvidoMesAnterior,
			        PesoDevolvidoMesAnterior,
			        0
			    )
			
			RETURN
			FORMAT(Variacao, "+0.0%;-0.0%;0.0%")
		lineageTag: cd8ed810-0789-459f-8d10-d228815ce60e

	measure 'MoM Clientes Ativos %' =
			
			VAR ClientesAtivosAtual =
			    DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			
			VAR ClientesAtivosMesAnterior =
			    CALCULATE(
			        DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]),
			        DATEADD(D_Calendario[Data], -1, MONTH)
			    )
			
			VAR Variacao =
			    DIVIDE(
			        ClientesAtivosAtual - ClientesAtivosMesAnterior,
			        ClientesAtivosMesAnterior,
			        0
			    )
			
			RETURN
			FORMAT(Variacao, "+0.0%;-0.0%;0.0%")
		lineageTag: 538f7bf4-3849-46eb-93fa-7ea04e6bb995

	/// JSON com dados dos 4 KPIs do HTML Saude do Negocio: Faturamento, Peso, Ticket Mediano, Clientes Ativos com MoM%. Responde a filtros nativos.
	measure '_JSON KPIs Saude' =
			"{""fat"":"         & SUBSTITUTE(FORMAT(COALESCE([Faturamento Total], 0), "0.##"), ",", ".") &
			",""momFat"":"""    & COALESCE([MoM Faturamento %], "--") & """" &
			",""peso"":"        & SUBSTITUTE(FORMAT(COALESCE([Peso Total Vendido], 0), "0.##"), ",", ".") &
			",""momPeso"":"""   & COALESCE([MoM Peso Total Vendido %], "--") & """" &
			",""ticket"":"      & SUBSTITUTE(FORMAT(COALESCE([Ticket Mediano], 0), "0.##"), ",", ".") &
			",""momTicket"":""" & COALESCE([MoM Ticket Mediano %], "--") & """" &
			",""clientes"":"    & COALESCE([Total Clientes Ativos], 0) &
			",""momClientes"":""" & COALESCE([MoM Clientes Ativos %], "--") & """" &
			"}"
		displayFolder: HTML Saude
		lineageTag: 9165fc4b-89ea-448e-8405-bfa7e030e690

	/// Array JSON com métricas mensais (Faturamento, Peso, Pedidos, Ticket Mediano) para o gráfico de evolução do HTML Saude do Negocio. IGNORA filtro de data.
	measure '_JSON Evolucao Saude' =
			VAR _meses =
			    CALCULATETABLE(
			        FILTER(
			            SUMMARIZE(DCVVQ_VENDAGERALTELEVENDAS, D_Calendario[Mês/Ano], D_Calendario[MesAno Ordem]),
			            NOT ISBLANK(D_Calendario[MesAno Ordem])
			        ),
			        ALL(D_Calendario)
			    )
			VAR _result =
			    ADDCOLUMNS(
			        _meses,
			        "_fat",
			            VAR _ym = D_Calendario[Mês/Ano]
			            RETURN CALCULATE([Faturamento Total], ALL(D_Calendario), D_Calendario[Mês/Ano] = _ym),
			        "_peso",
			            VAR _ym = D_Calendario[Mês/Ano]
			            RETURN CALCULATE([Peso Total Vendido], ALL(D_Calendario), D_Calendario[Mês/Ano] = _ym),
			        "_ped",
			            VAR _ym = D_Calendario[Mês/Ano]
			            RETURN CALCULATE([Total de Pedidos], ALL(D_Calendario), D_Calendario[Mês/Ano] = _ym),
			        "_ticket",
			            VAR _ym = D_Calendario[Mês/Ano]
			            RETURN CALCULATE([Ticket Mediano], ALL(D_Calendario), D_Calendario[Mês/Ano] = _ym),
			        "_devRS",
			            VAR _ym = D_Calendario[Mês/Ano]
			            RETURN CALCULATE([Total Devoluções (R$)], ALL(D_Calendario), D_Calendario[Mês/Ano] = _ym),
			        "_devPeso",
			            VAR _ym = D_Calendario[Mês/Ano]
			            RETURN CALCULATE([Peso Total Devolvido], ALL(D_Calendario), D_Calendario[Mês/Ano] = _ym)
			    )
			RETURN
			"[" &
			CONCATENATEX(
			    _result,
			    "{""mes"":""" & D_Calendario[Mês/Ano] &
			    """,""ord"":" & D_Calendario[MesAno Ordem] &
			    ",""fat"":"     & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""peso"":"    & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""pedidos"":" & COALESCE([_ped], 0) &
			    ",""ticket"":"  & SUBSTITUTE(FORMAT(COALESCE([_ticket], 0), "0.00"), ",", ".") &
			    ",""devRS"":"   & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""devPeso"":" & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			    "}",
			    ",",
			    D_Calendario[MesAno Ordem], ASC
			) & "]"
		displayFolder: HTML Saude
		lineageTag: f23cb472-12e5-4133-a6c1-40cf3634d967

	/// Top 10 produtos por Faturamento para o gráfico de barras do HTML Saude. Inclui peso e qtd para contexto.
	measure '_JSON Top Produtos Saude' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO]) && DCVVQ_VENDAGERALTELEVENDAS[PRODUTO] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",     [Faturamento Total],
			        "_peso",    [Peso Total Vendido],
			        "_qtd",     CALCULATE(SUM(DCVVQ_VENDAGERALTELEVENDAS[QTDVENDA])),
			        "_devRS",   [Total Devoluções (R$)],
			        "_devPeso", [Peso Total Devolvido],
			        "_devQtd",  CALCULATE(SUM(DCVVQ_VENDAGERALTELEVENDAS[QTDDEVOLVIDA]))
			    )
			VAR _topVenda = TOPN(10, FILTER(_com, [_fat] > 0), [_fat], DESC)
			VAR _topDev   = TOPN(10, FILTER(_com, [_devRS] > 0), [_devRS], DESC)
			VAR _arrVenda =
			    "[" & CONCATENATEX(
			        _topVenda,
			        "{""produto"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO], """""", ""), "\", "") &
			        """,""val"":"   & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""peso"":"    & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""qtd"":"     & SUBSTITUTE(FORMAT(COALESCE([_qtd], 0), "0.00"), ",", ".") &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrDev =
			    "[" & CONCATENATEX(
			        _topDev,
			        "{""produto"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO], """""", ""), "\", "") &
			        """,""val"":"   & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""peso"":"    & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""qtd"":"     & SUBSTITUTE(FORMAT(COALESCE([_devQtd], 0), "0.00"), ",", ".") &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			RETURN
			"{""venda"":" & _arrVenda & ",""devolucao"":" & _arrDev & "}"
		displayFolder: HTML Saude
		lineageTag: f6116420-7945-4e86-80d9-609cc77de03c

	/// Top 10 clientes por Faturamento para o gráfico de barras do HTML Saude. Inclui peso e qtd de pedidos para contexto.
	measure '_JSON Top Clientes Saude' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE]) && DCVVQ_VENDAGERALTELEVENDAS[CLIENTE] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_peso",     [Peso Total Vendido],
			        "_pedidos",  [Total de Pedidos],
			        "_devRS",    [Total Devoluções (R$)],
			        "_devPeso",  [Peso Total Devolvido]
			    )
			VAR _topVenda = TOPN(10, FILTER(_com, [_fat] > 0), [_fat], DESC)
			VAR _topDev   = TOPN(10, FILTER(_com, [_devRS] > 0), [_devRS], DESC)
			VAR _arrVenda =
			    "[" & CONCATENATEX(
			        _topVenda,
			        "{""cliente"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE], """""", ""), "\", "") &
			        """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""peso"":"      & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""pedidos"":"   & COALESCE([_pedidos], 0) &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrDev =
			    "[" & CONCATENATEX(
			        _topDev,
			        "{""cliente"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE], """""", ""), "\", "") &
			        """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""peso"":"      & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""pedidos"":"   & COALESCE([_pedidos], 0) &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			RETURN
			"{""venda"":" & _arrVenda & ",""devolucao"":" & _arrDev & "}"
		displayFolder: HTML Saude
		lineageTag: 8d2b15ca-fc32-4264-b077-0c177992ceda

	/// Distribuição do faturamento por GRUPOPRODUTO para o treemap do HTML Saude. Todos os grupos ordenados, com fat absoluto e % do total.
	measure '_JSON Mix Grupo Saude' =
			VAR _total = [Faturamento Total]
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO]) && DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO] <> ""
			    )
			VAR _comFat =
			    ADDCOLUMNS(
			        _todos,
			        "_fat", [Faturamento Total],
			        "_pct", DIVIDE([Faturamento Total], _total) * 100
			    )
			VAR _ord = FILTER(_comFat, [_fat] > 0)
			RETURN
			"[" &
			CONCATENATEX(
			    _ord,
			    "{""grupo"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO], """""", ""), "\", "") &
			    """,""fat"":" & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""pct"":"   & SUBSTITUTE(FORMAT(COALESCE([_pct], 0), "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Saude
		lineageTag: b3546d47-4c40-4104-948a-f57ceabb522f

	/// JSON com o bloco resumido de devoluções do HTML Saude: Total R$, Peso Devolvido, Taxa R$, Taxa Peso, com MoMs.
	measure '_JSON Devolucoes Saude' =
			"{""totalRS"":"    & SUBSTITUTE(FORMAT(COALESCE([Total Devoluções (R$)], 0), "0.00"), ",", ".") &
			",""momRS"":"""    & COALESCE([MoM Devoluções %], "--") & """" &
			",""totalPeso"":"  & SUBSTITUTE(FORMAT(COALESCE([Peso Total Devolvido], 0), "0.00"), ",", ".") &
			",""momPeso"":"""  & COALESCE([MoM Peso Total Devolvido %], "--") & """" &
			",""taxaRS"":"     & SUBSTITUTE(FORMAT(COALESCE([Taxa de Devolução (R$)], 0) * 100, "0.00"), ",", ".") &
			",""taxaPeso"":"   & SUBSTITUTE(FORMAT(COALESCE([Taxa de Devolução (Peso)], 0) * 100, "0.00"), ",", ".") &
			"}"
		displayFolder: HTML Saude
		lineageTag: 97766ac4-9653-4876-9d0e-fe4229f4f4e6

	/// Array JSON com dados por VENDEDOR para a aba Vendedor da tabela do HTML Saude. Inclui faturamento, peso, pedidos e itens.
	measure '_JSON Tabela Vendedor Saude' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR]) && DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",     [Faturamento Total],
			        "_peso",    [Peso Total Vendido],
			        "_pedidos", [Total de Pedidos],
			        "_itens",   [Total de Itens]
			    )
			VAR _ord = FILTER(_com, [_fat] > 0)
			RETURN
			"[" &
			CONCATENATEX(
			    _ord,
			    "{""vendedor"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR], """""", ""), "\", "") &
			    """,""fat"":"      & SUBSTITUTE(FORMAT(COALESCE([_fat],  0), "0.00"), ",", ".") &
			    ",""peso"":"       & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""pedidos"":"    & COALESCE([_pedidos], 0) &
			    ",""itens"":"      & COALESCE([_itens], 0) &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Saude
		lineageTag: 9820b52d-5daa-47fb-bf6f-fe28d8154b1c

	/// Array JSON com dados por PRODUTO para a aba Produto da tabela do HTML Saude. Inclui grupo, faturamento, peso e qtd vendida.
	measure '_JSON Tabela Produto Saude' =
			VAR _todos =
			    SUMMARIZE(
			        DCVVQ_VENDAGERALTELEVENDAS,
			        DCVVQ_VENDAGERALTELEVENDAS[PRODUTO],
			        DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO]
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",  [Faturamento Total],
			        "_peso", [Peso Total Vendido],
			        "_qtd",  CALCULATE(SUM(DCVVQ_VENDAGERALTELEVENDAS[QTDVENDA]))
			    )
			VAR _ord =
			    FILTER(
			        _com,
			        [_fat] > 0
			        && NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO])
			        && DCVVQ_VENDAGERALTELEVENDAS[PRODUTO] <> ""
			    )
			RETURN
			"[" &
			CONCATENATEX(
			    _ord,
			    "{""produto"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO], """""", ""), "\", "") &
			    """,""grupo"":"""  & SUBSTITUTE(SUBSTITUTE(COALESCE(DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO], ""), """""", ""), "\", "") &
			    """,""fat"":"     & SUBSTITUTE(FORMAT(COALESCE([_fat],  0), "0.00"), ",", ".") &
			    ",""peso"":"      & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""qtd"":"       & SUBSTITUTE(FORMAT(COALESCE([_qtd],  0), "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Saude
		lineageTag: e892204f-7906-497b-bd40-2b92fd7d5936

	/// Array JSON com dados por CLIENTE para a aba Cliente da tabela do HTML Saude. Inclui atividade, porte, faturamento e pedidos.
	measure '_JSON Tabela Cliente Saude' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE]) && DCVVQ_VENDAGERALTELEVENDAS[CLIENTE] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_atividade", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE])),
			        "_porte",     CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[PORTE])),
			        "_fat",       [Faturamento Total],
			        "_pedidos",   [Total de Pedidos]
			    )
			VAR _ord = FILTER(_com, [_fat] > 0)
			RETURN
			"[" &
			CONCATENATEX(
			    _ord,
			    "{""cliente"":"""     & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE], """""", ""), "\", "") &
			    """,""atividade"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_atividade], ""), """""", ""), "\", "") &
			    """,""porte"":"""     & SUBSTITUTE(SUBSTITUTE(COALESCE([_porte], ""), """""", ""), "\", "") &
			    """,""fat"":"        & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""pedidos"":"      & COALESCE([_pedidos], 0) &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Saude
		lineageTag: b6a6214c-66a6-482e-b557-a1b2d81d5399

	/// Array JSON com dados por CIDADE para a aba Cidade da tabela do HTML Saude. Inclui UF, faturamento e clientes ativos.
	measure '_JSON Tabela Cidade Saude' =
			VAR _todos =
			    SUMMARIZE(
			        DCVVQ_VENDAGERALTELEVENDAS,
			        DCVVQ_VENDAGERALTELEVENDAS[CIDADE],
			        DCVVQ_VENDAGERALTELEVENDAS[UF]
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_clientes", [Total Clientes Ativos]
			    )
			VAR _ord =
			    FILTER(
			        _com,
			        [_fat] > 0
			        && NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[CIDADE])
			        && DCVVQ_VENDAGERALTELEVENDAS[CIDADE] <> ""
			    )
			RETURN
			"[" &
			CONCATENATEX(
			    _ord,
			    "{""cidade"":"""   & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CIDADE], """""", ""), "\", "") &
			    """,""uf"":"""      & SUBSTITUTE(SUBSTITUTE(COALESCE(DCVVQ_VENDAGERALTELEVENDAS[UF], ""), """""", ""), "\", "") &
			    """,""fat"":"      & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""clientes"":"   & COALESCE([_clientes], 0) &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Saude
		lineageTag: c6e8914e-609d-476f-b42a-a07a38284806

	/// Array JSON com dados por TIPODEVOLUCAO para a aba Devolução da tabela do HTML Saude. Inclui qtd devolvida, peso devolvido e valor R$.
	measure '_JSON Tabela Devolucao Saude' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO]) && DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_qtd",  CALCULATE(SUM(DCVVQ_VENDAGERALTELEVENDAS[QTDDEVOLVIDA])),
			        "_peso", [Peso Total Devolvido],
			        "_val",  [Total Devoluções (R$)]
			    )
			VAR _ord = FILTER(_com, [_val] > 0)
			RETURN
			"[" &
			CONCATENATEX(
			    _ord,
			    "{""tipo"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO], """""", ""), "\", "") &
			    """,""qtd"":"  & SUBSTITUTE(FORMAT(COALESCE([_qtd],  0), "0.00"), ",", ".") &
			    ",""peso"":"   & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""val"":"    & SUBSTITUTE(FORMAT(COALESCE([_val],  0), "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_val], DESC
			) & "]"
		displayFolder: HTML Saude
		lineageTag: b77f2f67-cde6-4e29-ab25-94388498d3a6

	/// JS Saude do Negocio v3 - mini-barras apenas em colunas monetarias (R$), toggles Venda/Devolucao nos top10, dropdown evolucao estendido
	measure '_JS Saude' =
			"<script>" & "(function () {
			  'use strict';
			  function rJ(id) { var e = document.getElementById(id); try { return JSON.parse((e && e.textContent) || 'null'); } catch (ex) { return null; } }
			  function esc(v) { return String(v == null ? '' : v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
			  function escT(v) { return esc(v).replace(/'/g,'&#39;'); }
			  function fN(v) { return (Number(v) || 0).toLocaleString('pt-BR'); }
			  function fA(v) { v = Number(v) || 0; if (Math.abs(v) >= 1e6) return (v/1e6).toFixed(1).replace('.',',') + ' mi'; if (Math.abs(v) >= 1e3) return (v/1e3).toFixed(1).replace('.',',') + ' mil'; return fN(Math.round(v)); }
			  function fM(v) { v = Number(v) || 0; return 'R$ ' + v.toLocaleString('pt-BR', {minimumFractionDigits:2, maximumFractionDigits:2}); }
			  function fMK(v) { v = Number(v) || 0; if (Math.abs(v) >= 1e6) return 'R$ ' + (v/1e6).toFixed(2).replace('.',',') + ' mi'; if (Math.abs(v) >= 1e3) return 'R$ ' + (v/1e3).toFixed(1).replace('.',',') + ' mil'; return fM(v); }
			  function fAkg(v) { return fA(v) + ' kg'; }
			  function momCls(s) { if (!s || s === '--') return 'neu'; return s.indexOf('+') === 0 ? 'up' : (s.indexOf('-') === 0 ? 'down' : 'neu'); }
			  function momClsInv(s) { if (!s || s === '--') return 'neu'; return s.indexOf('+') === 0 ? 'down' : (s.indexOf('-') === 0 ? 'up' : 'neu'); }
			  function svgDim(el, fbW, fbH) { var bb = el.getBoundingClientRect(); return [Math.round(bb.width) || fbW, Math.round(bb.height) || fbH]; }
			  function tagColor(str) {
			    if (!str) return {bg:'rgba(139,139,139,.12)',fg:'#5A5A5A'};
			    var h=0; for (var i=0;i<str.length;i++) h = ((h<<5)-h) + str.charCodeAt(i);
			    var palette = [
			      {bg:'rgba(184,147,90,.15)',fg:'#8A6740'},
			      {bg:'rgba(78,125,98,.15)',fg:'#3D6049'},
			      {bg:'rgba(74,110,138,.15)',fg:'#3A5872'},
			      {bg:'rgba(192,124,58,.15)',fg:'#995F2C'},
			      {bg:'rgba(58,36,16,.12)',fg:'#3A2410'},
			      {bg:'rgba(90,90,90,.15)',fg:'#5A5A5A'}
			    ];
			    return palette[Math.abs(h) % palette.length];
			  }
			  var ttEl = document.getElementById('tt');
			  window.tip = function(e,h){ if (!ttEl) return; ttEl.innerHTML = h; ttEl.classList.add('on'); var vw=window.innerWidth, vh=window.innerHeight, tw=ttEl.offsetWidth, th=ttEl.offsetHeight; var lx=e.clientX+14; if(lx+tw+8>vw) lx=e.clientX-tw-14; if(lx<4) lx=4; var ty=e.clientY-36; if(ty<4) ty=e.clientY+18; if(ty+th+4>vh) ty=vh-th-4; ttEl.style.left=lx+'px'; ttEl.style.top=ty+'px'; };
			  window.tipOff = function(){ ttEl && ttEl.classList.remove('on'); };
			  window.tgD = function(id){ var l = document.getElementById(id); if (!l) return; document.querySelectorAll('.dd-list.on').forEach(function(e){ if(e!==l) e.classList.remove('on'); }); l.classList.toggle('on'); };
			  window.ddC = function(e){ var o = e.target.closest('.dd-item'); if (!o) return; var ls=e.currentTarget, p=ls.dataset.p, fn=ls.dataset.fn, v=o.dataset.v, l=o.dataset.l; var b=document.getElementById(p+'-b'); if(b){ b.textContent=l+' ▾'; b.dataset.v=v; } ls.querySelectorAll('.dd-item').forEach(function(el){ el.classList.toggle('act', el.dataset.v===v); }); ls.classList.remove('on'); if(window[fn]) window[fn](); };
			  document.addEventListener('click', function(e){ if (!e.target.closest('.dd') && !e.target.closest('.tabs') && !e.target.closest('.mini-toggle')) document.querySelectorAll('.dd-list.on').forEach(function(el){ el.classList.remove('on'); }); });
			  function axes(W,H,P,mx,fmtFn){ var s=''; var fn=fmtFn||fA; for(var i=0;i<=4;i++){ var y=P.t+(H-P.t-P.b)*i/4, v=mx*(1-i/4); s += ""<line class='gl' x1='""+(P.l)+""' x2='""+(W-P.r)+""' y1='""+(y)+""' y2='""+(y)+""'/>""; if(i<4) s += ""<text class='axl' x='""+(P.l-4)+""' y='""+(y+4)+""' text-anchor='end'>""+fn(v)+""</text>""; } return s; }
			  function smoothCurve(pts){if(pts.length<2)return pts.length?'M'+pts[0].x.toFixed(1)+','+pts[0].y.toFixed(1):'';var d='M'+pts[0].x.toFixed(1)+','+pts[0].y.toFixed(1);for(var i=0;i<pts.length-1;i++){var p0=pts[Math.max(i-1,0)],p1=pts[i],p2=pts[i+1],p3=pts[Math.min(i+2,pts.length-1)];var cp1x=p1.x+(p2.x-p0.x)/6,cp1y=p1.y+(p2.y-p0.y)/6,cp2x=p2.x-(p3.x-p1.x)/6,cp2y=p2.y-(p3.y-p1.y)/6;d+=' C'+cp1x.toFixed(1)+','+cp1y.toFixed(1)+' '+cp2x.toFixed(1)+','+cp2y.toFixed(1)+' '+p2.x.toFixed(1)+','+p2.y.toFixed(1);}return d;}
			  var kpiIcons = {
			    money: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><line x1='12' y1='1' x2='12' y2='23'/><path d='M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6'/></svg>"",
			    weight: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><circle cx='12' cy='5' r='3'/><path d='M6.5 22L4 9l16 0-2.5 13z'/></svg>"",
			    target: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><circle cx='12' cy='12' r='10'/><circle cx='12' cy='12' r='6'/><circle cx='12' cy='12' r='2'/></svg>"",
			    users: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><path d='M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2'/><circle cx='9' cy='7' r='4'/><path d='M23 21v-2a4 4 0 0 0-3-3.87'/><path d='M16 3.13a4 4 0 0 1 0 7.75'/></svg>""
			  };
			  function buildKPIs(){
			    var K=rJ('jKpi')||{}; var el=document.getElementById('kpiGrid'); if(!el) return;
			    var cards=[
			      {icon:'money',label:'Faturamento Total',val:fMK(K.fat||0),sub:'MoM = <span class=\''+momCls(K.momFat)+'\'>'+(K.momFat||'-')+'</span>'},
			      {icon:'weight',label:'Peso Vendido',val:fA(K.peso||0)+' kg',sub:'MoM = <span class=\''+momCls(K.momPeso)+'\'>'+(K.momPeso||'-')+'</span>'},
			      {icon:'target',label:'Ticket Mediano',val:fMK(K.ticket||0),sub:'MoM = <span class=\''+momCls(K.momTicket)+'\'>'+(K.momTicket||'-')+'</span>'},
			      {icon:'users',label:'Clientes Ativos',val:fN(K.clientes||0),sub:'MoM = <span class=\''+momCls(K.momClientes)+'\'>'+(K.momClientes||'-')+'</span>'}
			    ];
			    el.innerHTML=cards.map(function(c){ return ""<div class='kpi'><div class='kpi-top'><span class='kpi-label'>""+c.label+""</span><div class='kpi-icon'>""+kpiIcons[c.icon]+""</div></div><div class='kpi-val'>""+c.val+""</div><div class='kpi-sub'>""+c.sub+""</div></div>""; }).join('');
			  }
			  window.rEv = function(){
			    var btn=document.getElementById('mE-b'); if(!btn) return; var k=btn.dataset.v;
			    var btn2=document.getElementById('mE2-b'); var k2 = btn2 ? btn2.dataset.v : 'none';
			    var hasComp = (k2 && k2 !== 'none' && k2 !== k);
			    var el=document.getElementById('svgEv'); if(!el) return;
			    var d=svgDim(el,800,200); var W=d[0],H=d[1]; el.setAttribute('viewBox','0 0 '+W+' '+H);
			    var EV=rJ('jEv')||[]; if(!EV.length){ el.innerHTML=""<text x='""+(W/2)+""' y='""+(H/2)+""' text-anchor='middle' fill='#999'>Sem dados</text>""; return; }
			    function pickFmt(kk){ if(kk==='fat'||kk==='ticket'||kk==='devRS') return fMK; if(kk==='peso'||kk==='devPeso') return fAkg; return fA; }
			    var fmtFn = pickFmt(k);
			    var fmtFn2 = pickFmt(k2);
			    var P={t:24, r: hasComp?72:16, b:28, l:64};
			    var vals=EV.map(function(d2){ return Number(d2[k])||0; });
			    var mx=Math.max.apply(null,vals.concat([1]))*1.18, CW=W-P.l-P.r, CH=H-P.t-P.b, gw=CW/(EV.length-1||1);
			    var pts=EV.map(function(d2,i){ var v=Number(d2[k])||0; var x=P.l+(EV.length>1?i*gw:CW/2); var y=P.t+CH-(v/mx)*CH; return {x:x,y:y,v:v,mes:d2.mes}; });
			    var pts2=null, mx2=0;
			    if(hasComp){
			      var vals2=EV.map(function(d2){ return Number(d2[k2])||0; });
			      mx2=Math.max.apply(null,vals2.concat([1]))*1.18;
			      pts2=EV.map(function(d2,i){ var v=Number(d2[k2])||0; var x=P.l+(EV.length>1?i*gw:CW/2); var y=P.t+CH-(v/mx2)*CH; return {x:x,y:y,v:v,mes:d2.mes}; });
			    }
			    var lineD=smoothCurve(pts);
			    var areaD='M'+pts[0].x.toFixed(1)+','+(P.t+CH)+' L'+lineD.slice(1)+' L'+pts[pts.length-1].x.toFixed(1)+','+(P.t+CH)+'Z';
			    var uid='g'+Math.floor(Math.random()*99999);
			    var svg=axes(W,H,P,mx,fmtFn);
			    if(hasComp){
			      for(var ai=0; ai<4; ai++){
			        var ay=P.t+CH*ai/4, av=mx2*(1-ai/4);
			        svg += ""<text class='axl' x='""+(W-P.r+6)+""' y='""+(ay+4)+""' text-anchor='start' style='fill:#4A6E8A;font-weight:600'>""+fmtFn2(av)+""</text>"";
			      }
			    }
			    svg += ""<defs><linearGradient id='lg""+uid+""' x1='0%' y1='0%' x2='100%' y2='0%'><stop offset='0%' stop-color='#1A1A1A' stop-opacity='.8'/><stop offset='100%' stop-color='#B8935A' stop-opacity='1'/></linearGradient><linearGradient id='ag""+uid+""' x1='0%' y1='0%' x2='0%' y2='100%'><stop offset='0%' stop-color='#B8935A' stop-opacity='.15'/><stop offset='100%' stop-color='#B8935A' stop-opacity='0'/></linearGradient></defs>"";
			    svg += ""<path d='""+areaD+""' fill='url(#ag""+uid+"")'/>"";
			    svg += ""<path d='""+lineD+""' fill='none' stroke='url(#lg""+uid+"")' stroke-width='2.5' stroke-linejoin='round' stroke-linecap='round'/>"";
			    if(hasComp){
			      var lineD2=smoothCurve(pts2);
			      svg += ""<path d='""+lineD2+""' fill='none' stroke='#4A6E8A' stroke-width='2.2' stroke-linejoin='round' stroke-linecap='round' stroke-dasharray='5,4'/>"";
			    }
			    var ML={fat:'Faturamento',peso:'Peso',pedidos:'Pedidos',ticket:'Ticket',devRS:'Devolução R$',devPeso:'Peso Devolvido'};
			    var lbl=ML[k]||k;
			    var lbl2=ML[k2]||k2;
			    if(hasComp){
			      svg += ""<g transform='translate(""+(P.l+8)+"",""+(P.t-12)+"")'>"";
			      svg += ""<line x1='0' y1='0' x2='18' y2='0' stroke='#B8935A' stroke-width='2.5'/>"";
			      svg += ""<text x='22' y='4' style='fill:#1A1A1A;font-size:10.5px;font-weight:600'>""+esc(lbl)+""</text>"";
			      var off=Math.round(lbl.length*6.5+40);
			      svg += ""<line x1='""+off+""' y1='0' x2='""+(off+18)+""' y2='0' stroke='#4A6E8A' stroke-width='2.2' stroke-dasharray='5,4'/>"";
			      svg += ""<text x='""+(off+22)+""' y='4' style='fill:#4A6E8A;font-size:10.5px;font-weight:600'>""+esc(lbl2)+""</text>"";
			      svg += ""</g>"";
			    }
			    pts.forEach(function(p,i){
			      var compTip = hasComp ? ('<br>'+lbl2+': '+fmtFn2(pts2[i].v)) : '';
			      svg += ""<circle cx='""+p.x.toFixed(1)+""' cy='""+p.y.toFixed(1)+""' r='10' fill='transparent' onmousemove=\""tip(event,'<b>""+escT(p.mes)+""</b><br>""+lbl+"": ""+fmtFn(p.v)+""""+compTip+""')\"" onmouseleave='tipOff()'/>"";
			      svg += ""<circle cx='""+p.x.toFixed(1)+""' cy='""+p.y.toFixed(1)+""' r='3.5' fill='#B8935A' stroke='#fff' stroke-width='1.5' pointer-events='none'/>"";
			      if(hasComp){
			        svg += ""<circle cx='""+pts2[i].x.toFixed(1)+""' cy='""+pts2[i].y.toFixed(1)+""' r='3' fill='#4A6E8A' stroke='#fff' stroke-width='1.5' pointer-events='none'/>"";
			      }
			      if(pts.length <= 16) svg += ""<text class='axl' x='""+p.x.toFixed(1)+""' y='""+(H-8)+""' text-anchor='middle' pointer-events='none'>""+esc(p.mes)+""</text>"";
			    });
			    el.innerHTML=svg;
			  };
			  var _modoP='venda', _modoC='venda';
			  window.setModoP=function(m){ _modoP=m; document.querySelectorAll('#tpToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderTopProdutos(); };
			  window.setModoC=function(m){ _modoC=m; document.querySelectorAll('#tcToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderTopClientes(); };
			  function renderTopProdutos(){
			    var el=document.getElementById('topProdutos'); if(!el) return;
			    var TP=rJ('jTp')||{venda:[],devolucao:[]};
			    var data=TP[_modoP]||[];
			    if(!data.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Math.max.apply(null,data.map(function(d){ return Number(d.val)||0; }).concat([1]));
			    var lbl = _modoP==='venda' ? 'Faturamento' : 'Devolução';
			    el.innerHTML=data.map(function(d){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      return ""<div class='bar-row' onmousemove=\""tip(event,'<b>""+escT(d.produto)+""</b><br>""+lbl+"": ""+fMK(v)+""<br>Peso: ""+fA(Number(d.peso)||0)+"" kg<br>Qtd: ""+fA(Number(d.qtd)||0)+""')\"" onmouseleave='tipOff()'><div class='bar-head'><div class='bar-name'>""+esc(d.produto)+""</div><div class='bar-val'>""+fMK(v)+""</div></div><div class='bar-track'><div class='bar-fill' data-w='""+w+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.bar-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  function renderTopClientes(){
			    var el=document.getElementById('topClientes'); if(!el) return;
			    var TC=rJ('jTc')||{venda:[],devolucao:[]};
			    var data=TC[_modoC]||[];
			    if(!data.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Math.max.apply(null,data.map(function(d){ return Number(d.val)||0; }).concat([1]));
			    var lbl = _modoC==='venda' ? 'Faturamento' : 'Devolução';
			    el.innerHTML=data.map(function(d){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      return ""<div class='bar-row' onmousemove=\""tip(event,'<b>""+escT(d.cliente)+""</b><br>""+lbl+"": ""+fMK(v)+""<br>Pedidos: ""+fN(Number(d.pedidos)||0)+""')\"" onmouseleave='tipOff()'><div class='bar-head'><div class='bar-name'>""+esc(d.cliente)+""</div><div class='bar-val'>""+fMK(v)+""</div></div><div class='bar-track'><div class='bar-fill' data-w='""+w+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.bar-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  function renderTreemap(){
			    var el=document.getElementById('svgMix'); if(!el) return;
			    var d=svgDim(el,800,220); var W=d[0],H=d[1]; el.setAttribute('viewBox','0 0 '+W+' '+H);
			    var MX=rJ('jMx')||[]; if(!MX.length){ el.innerHTML=""<text x='""+(W/2)+""' y='""+(H/2)+""' text-anchor='middle' fill='#999'>Sem dados</text>""; return; }
			    var total=MX.reduce(function(s,d2){ return s+(Number(d2.fat)||0); }, 0);
			    var colors=['#1A1A1A','#B8935A','#4E7D62','#C07C3A','#4A6E8A','#3A2410','#5A5A5A','#8B8B8B'];
			    var x=0, svg='';
			    MX.forEach(function(d2,i){
			      var v=Number(d2.fat)||0;
			      var w=(v/Math.max(total,1))*W;
			      var c=colors[i % colors.length];
			      var pct=(Number(d2.pct)||0).toFixed(1).replace('.',',');
			      svg += ""<g onmousemove=\""tip(event,'<b>""+escT(d2.grupo)+""</b><br>""+fMK(v)+""<br>""+pct+""%')\"" onmouseleave='tipOff()' style='cursor:default'>"";
			      svg += ""<rect x='""+x+""' y='0' width='""+w+""' height='""+H+""' fill='""+c+""' opacity='.95'/>"";
			      if(w > 60){
			        svg += ""<text x='""+(x+w/2)+""' y='""+(H/2-12)+""' text-anchor='middle' fill='#fff' font-size='13' font-weight='700' font-family='Segoe UI,sans-serif'>""+esc(d2.grupo)+""</text>"";
			        svg += ""<text x='""+(x+w/2)+""' y='""+(H/2+8)+""' text-anchor='middle' fill='#fff' font-size='11' font-weight='600' font-family='Segoe UI,sans-serif' opacity='.85'>""+pct+""%</text>"";
			        svg += ""<text x='""+(x+w/2)+""' y='""+(H/2+24)+""' text-anchor='middle' fill='#fff' font-size='10' font-weight='500' font-family='Segoe UI,sans-serif' opacity='.7'>""+fMK(v)+""</text>"";
			      }
			      svg += ""</g>"";
			      x += w;
			    });
			    el.innerHTML=svg;
			  }
			  function renderDevolucoes(){
			    var el=document.getElementById('devolKpis'); if(!el) return;
			    var D=rJ('jDv')||{};
			    var minis=[
			      {label:'Total Devolvido',val:fMK(D.totalRS||0),sub:'MoM = <span class=\''+momClsInv(D.momRS)+'\'>'+(D.momRS||'-')+'</span>'},
			      {label:'Peso Devolvido',val:fA(D.totalPeso||0)+' kg',sub:'MoM = <span class=\''+momClsInv(D.momPeso)+'\'>'+(D.momPeso||'-')+'</span>'},
			      {label:'Taxa Devolução (R$)',val:(Number(D.taxaRS)||0).toFixed(2).replace('.',',')+'%',sub:'sobre o faturamento'},
			      {label:'Taxa Devolução (Peso)',val:(Number(D.taxaPeso)||0).toFixed(2).replace('.',',')+'%',sub:'sobre o peso total'}
			    ];
			    el.innerHTML=minis.map(function(m){ return ""<div class='mini-kpi'><div class='mini-label'>""+m.label+""</div><div class='mini-val'>""+m.val+""</div><div class='mini-sub'>""+m.sub+""</div></div>""; }).join('');
			  }
			  var _aba='vendedor';
			  window.setAba=function(aba){ _aba=aba; document.querySelectorAll('#abasTabs .tab').forEach(function(t){ t.classList.toggle('on', t.dataset.aba===aba); }); renderTabela(); };
			  function renderTabela(){
			    var el=document.getElementById('tabelaBox'); if(!el) return;
			    var data, cols;
			    if(_aba==='vendedor'){ data=rJ('jTv')||[]; cols=[{k:'vendedor',t:'Vendedor',cls:'name'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'peso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'itens',t:'Itens',cls:'num',fmt:fN}]; }
			    else if(_aba==='produto'){ data=rJ('jTpr')||[]; cols=[{k:'produto',t:'Produto',cls:'name'},{k:'grupo',t:'Grupo',cls:'tag'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'peso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'qtd',t:'Qtd Vendida',cls:'num',fmt:fA}]; }
			    else if(_aba==='cliente'){ data=rJ('jTcl')||[]; cols=[{k:'cliente',t:'Cliente',cls:'name'},{k:'atividade',t:'Atividade',cls:'tag'},{k:'porte',t:'Porte',cls:'tag'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN}]; }
			    else if(_aba==='cidade'){ data=rJ('jTci')||[]; cols=[{k:'cidade',t:'Cidade',cls:'name'},{k:'uf',t:'UF',cls:'tag'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'clientes',t:'Clientes Ativos',cls:'num',fmt:fN}]; }
			    else { data=rJ('jTdv')||[]; cols=[{k:'tipo',t:'Tipo de Devolução',cls:'name'},{k:'qtd',t:'Qtd Devolvida',cls:'num',fmt:fA},{k:'peso',t:'Peso Devolvido (kg)',cls:'num',fmt:fA},{k:'val',t:'Valor R$',cls:'num',fmt:fMK,bar:true}]; }
			    if(!data.length){ el.innerHTML=""<div style='padding:20px;color:#8B8B8B;text-align:center'>Sem dados</div>""; return; }
			    var maxNum={};
			    cols.forEach(function(c){ if(c.cls==='num' && c.bar){ maxNum[c.k]=Math.max.apply(null, data.map(function(d){return Number(d[c.k])||0;}).concat([1])); } });
			    var head=""<thead><tr>"" + cols.map(function(c){ return ""<th class='th-""+c.cls+""'>""+c.t+""</th>""; }).join('') + ""</tr></thead>"";
			    var body=""<tbody>"" + data.map(function(d){
			      return ""<tr>"" + cols.map(function(c){
			        var v=d[c.k]; var text=c.fmt?c.fmt(v):esc(v);
			        if(c.cls==='num' && c.bar){
			          var n=Number(v)||0; var pct=Math.max(0,(n/maxNum[c.k])*100);
			          return ""<td class='td-num'><div class='cell-val'>""+text+""</div><div class='cell-bar'><div class='cell-fill' style='width:""+pct.toFixed(1)+""%'></div></div></td>"";
			        }
			        if(c.cls==='tag'){
			          var clr=tagColor(v);
			          return ""<td class='td-tag'><span class='tag-badge' style='background:""+clr.bg+"";color:""+clr.fg+""'>""+esc(v||'-')+""</span></td>"";
			        }
			        return ""<td class='td-""+c.cls+""'>""+text+""</td>"";
			      }).join('') + ""</tr>"";
			    }).join('') + ""</tbody>"";
			    el.innerHTML=""<table class='tbl'>"" + head + body + ""</table>"";
			  }
			  function renderAll(){
			    if(!document.getElementById('kpiGrid')) return false;
			    try { buildKPIs(); renderDevolucoes(); rEv(); renderTopProdutos(); renderTopClientes(); renderTreemap(); renderTabela(); return true; }
			    catch(e){ console.error(e); return false; }
			  }
			  var _prevHash='';
			  function dataHash(){
			    return ['jKpi','jEv','jTp','jTc','jMx','jDv','jTv','jTpr','jTcl','jTci','jTdv'].map(function(id){
			      var e=document.getElementById(id); if(!e) return '';
			      return e.textContent.length+'|'+e.textContent.slice(0,20);
			    }).join('~');
			  }
			  setInterval(function(){ var h=dataHash(); if(h!==_prevHash){ _prevHash=h; renderAll(); } }, 350);
			  var rt;
			  window.addEventListener('resize', function(){ clearTimeout(rt); rt=setTimeout(renderAll,120); });
			  function tryRender(a){ a=a||0; if(renderAll()) return; if(a<25) setTimeout(function(){ tryRender(a+1); }, 100); }
			  if(document.readyState==='loading'){ document.addEventListener('DOMContentLoaded', function(){ tryRender(); }); } else { tryRender(); }
			  window.addEventListener('load', function(){ tryRender(); });
			})();" & "</script>"
		displayFolder: HTML Saude
		lineageTag: 44cee7ae-9d0a-4538-8e3c-4a56037305cd

	/// Dashboard HTML Saude do Negocio v3: KPIs > Devolucoes > Evolucao (dropdown 6 opcoes) > Top 10s (toggle Venda/Devolucao) > Mix > Tabela com mini-barras R$ e badges.
	measure 'HTML Saude' =
			"<style>:root {
			  --bg:    #EEEAE2;
			  --surf:  #FFFFFF;
			  --surf2: #F7F3EB;
			  --bd:    rgba(26,26,26,.07);
			  --bd2:   rgba(26,26,26,.15);
			  --t1:    #1A1A1A;
			  --t2:    #5A5A5A;
			  --t3:    #8B8B8B;
			  --gold:  #B8935A;
			  --goldS: #EAD9BE;
			  --dark:  #1E1E1E;
			  --grn:   #4E7D62;
			  --org:   #C07C3A;
			  --blu:   #4A6E8A;
			  --red:   #A04848;
			  --sh1:   0 1px 3px rgba(0,0,0,.06);
			  --sh2:   0 2px 10px rgba(0,0,0,.1);
			  --r:     10px;
			  --ease:  cubic-bezier(.4,0,.2,1);
			}
			* { box-sizing: border-box; margin: 0; padding: 0; }
			html, body {
			  background: var(--bg);
			  font-family: 'Segoe UI', system-ui, sans-serif;
			  font-size: 14px; color: var(--t1);
			  -webkit-font-smoothing: antialiased;
			  min-height: 100vh;
			}
			.dash { padding: 14px 16px; display: flex; flex-direction: column; gap: 12px; }
			.hdr { display: flex; align-items: center; justify-content: space-between; padding: 0 2px; }
			.hdr-title { font-size: 25px; font-weight: 700; letter-spacing: -.5px; }
			.hdr-sub { font-size: 13px; color: var(--t3); margin-left: 8px; }
			.kpi-row { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; }
			.kpi { background: var(--surf); border-radius: var(--r); padding: 14px 16px; box-shadow: var(--sh1); border: 1px solid var(--bd); }
			.kpi-top { display: flex; align-items: flex-start; justify-content: space-between; gap: 8px; }
			.kpi-label { font-size: 12.5px; color: var(--t2); font-weight: 500; }
			.kpi-icon { width: 30px; height: 30px; border-radius: 8px; background: linear-gradient(135deg, var(--goldS), #F0E4CC); display: flex; align-items: center; justify-content: center; color: var(--gold); flex-shrink: 0; }
			.kpi-icon svg { width: 14px; height: 14px; }
			.kpi-val { font-size: 32px; font-weight: 700; letter-spacing: -.6px; line-height: 1.1; font-variant-numeric: tabular-nums; margin-top: 6px; }
			.kpi-sub { font-size: 12.5px; color: var(--t3); margin-top: 4px; }
			.kpi-sub .up { color: var(--grn); font-weight: 600; }
			.kpi-sub .down { color: var(--red); font-weight: 600; }
			.kpi-sub .neu { color: var(--gold); font-weight: 600; }
			.card { background: var(--surf); border-radius: var(--r); padding: 12px 14px; box-shadow: var(--sh1); border: 1px solid var(--bd); }
			.card-head { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 10px; gap: 10px; }
			.card-title { font-size: 16px; font-weight: 600; letter-spacing: -.2px; }
			.card-sub { font-size: 12px; color: var(--t3); margin-top: 1px; }
			.evol-card svg { width: 100%; height: 220px; display: block; }
			.dd { position: relative; display: inline-block; }
			.dd-btn { background: var(--dark); color: #fff; border: none; border-radius: 100px; padding: 6px 14px; font-size: 12.5px; font-weight: 600; cursor: pointer; outline: none; font-family: inherit; }
			.dd-btn-cmp { background: #4A6E8A; }
			.dd-list { position: absolute; top: calc(100% + 4px); right: 0; min-width: 160px; background: #222; border-radius: 8px; box-shadow: 0 8px 24px rgba(0,0,0,.3); z-index: 9999; display: none; overflow: hidden; }
			.dd-list.on { display: block; }
			.dd-item { padding: 8px 14px; color: rgba(255,255,255,.85); font-size: 12.5px; font-weight: 500; cursor: pointer; white-space: nowrap; transition: background .1s; font-family: inherit; }
			.dd-item:hover { background: rgba(255,255,255,.1); }
			.dd-item.act { color: var(--gold); }
			.mini-toggle { display: flex; background: var(--surf2); border: 1px solid var(--bd2); border-radius: 100px; overflow: hidden; }
			.mini-toggle button { padding: 5px 13px; font-size: 12px; font-weight: 600; border: none; background: transparent; color: var(--t2); cursor: pointer; font-family: inherit; transition: all .15s; }
			.mini-toggle button.on { background: var(--dark); color: #fff; border-radius: 100px; }
			.cv { width: 100%; display: block; }
			.cv .gl { stroke: rgba(0,0,0,.06); stroke-dasharray: 3,4; }
			.cv .axl { fill: #8B8B8B; font-size: 12.5px; font-weight: 500; }
			.cv .axv { fill: #1A1A1A; font-size: 12.5px; font-weight: 600; font-variant-numeric: tabular-nums; }
			.two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
			.bars-list { display: flex; flex-direction: column; gap: 9px; }
			.bar-row { cursor: default; }
			.bar-head { display: flex; justify-content: space-between; gap: 8px; margin-bottom: 4px; }
			.bar-name { font-size: 13px; color: #1A1A1A; font-weight: 500; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; flex: 1; min-width: 0; }
			.bar-val { font-size: 13px; font-weight: 700; font-variant-numeric: tabular-nums; color: var(--t1); }
			.bar-track { height: 6px; background: #EAD9BE; border-radius: 100px; overflow: hidden; }
			.bar-fill { height: 100%; border-radius: 100px; background: linear-gradient(90deg, #1A1A1A, var(--gold)); width: 0; transition: width .8s var(--ease); }
			.treemap-card svg { width: 100%; height: 240px; display: block; }
			.devol-row { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; }
			.mini-kpi { background: var(--surf2); border-radius: 8px; padding: 10px 12px; border: 1px solid var(--bd); }
			.mini-label { font-size: 12px; color: var(--t2); font-weight: 500; margin-bottom: 3px; }
			.mini-val { font-size: 22px; font-weight: 700; letter-spacing: -.3px; font-variant-numeric: tabular-nums; }
			.mini-sub { font-size: 11.5px; color: var(--t3); margin-top: 2px; }
			.mini-sub .up { color: var(--grn); font-weight: 600; }
			.mini-sub .down { color: var(--red); font-weight: 600; }
			.mini-sub .neu { color: var(--gold); font-weight: 600; }
			.tabs { display: flex; gap: 4px; background: var(--surf2); padding: 3px; border-radius: 100px; border: 1px solid var(--bd2); }
			.tab { padding: 6px 15px; font-size: 12.5px; font-weight: 600; border: none; background: transparent; color: var(--t2); cursor: pointer; font-family: inherit; border-radius: 100px; transition: all .15s; }
			.tab.on { background: var(--dark); color: #fff; }
			.table-wrap { overflow-x: auto; max-height: 460px; overflow-y: auto; border-radius: 8px; }
			.tbl { width: 100%; border-collapse: collapse; font-size: 13px; }
			.tbl th { position: sticky; top: 0; background: var(--surf2); padding: 10px 12px; text-align: left; font-weight: 600; color: var(--t2); border-bottom: 1px solid var(--bd2); font-size: 12px; text-transform: uppercase; letter-spacing: .3px; z-index: 2; }
			.tbl th.th-num { text-align: right; }
			.tbl td { padding: 7px 10px; border-bottom: 1px solid var(--bd); vertical-align: middle; }
			.tbl tr:hover td { background: var(--surf2); }
			.tbl td.td-name { font-weight: 500; color: var(--t1); }
			.tbl td.td-tag { color: var(--t2); font-size: 12px; }
			.tbl td.td-num { text-align: right; font-variant-numeric: tabular-nums; font-weight: 600; color: var(--t1); min-width: 100px; }
			.cell-val { display: block; }
			.cell-bar { height: 3px; background: rgba(26,26,26,.04); border-radius: 100px; overflow: hidden; margin-top: 3px; }
			.cell-fill { height: 100%; background: linear-gradient(90deg, #1A1A1A, var(--gold)); border-radius: 100px; }
			.tag-badge { display: inline-block; padding: 3px 10px; border-radius: 100px; font-size: 11.5px; font-weight: 600; letter-spacing: .2px; white-space: nowrap; }
			.tt { position: fixed; background: #1E1E1E; color: #fff; padding: 7px 12px; border-radius: 7px; font-size: 12.5px; pointer-events: none; opacity: 0; transition: opacity .15s; z-index: 9999; white-space: nowrap; box-shadow: 0 4px 20px rgba(0,0,0,.2); }
			.tt.on { opacity: 1; }
			.tt b { color: #D4B687; }
			</style>" &
			"<div class='dash'>
			  <div class='hdr'>
			    <div>
			      <span class='hdr-title'>Saúde do Negócio</span>
			      <span class='hdr-sub'>Visão executiva consolidada do faturamento, produtos, clientes e devoluções</span>
			    </div>
			  </div>
			  <div class='kpi-row' id='kpiGrid'></div>
			  <div class='card'>
			    <div class='card-head'>
			      <div><div class='card-title'>Saúde de Devolução</div><div class='card-sub'>Pulso de devoluções - detalhamento na página específica</div></div>
			    </div>
			    <div class='devol-row' id='devolKpis'></div>
			  </div>
			  <div class='card evol-card'>
			    <div class='card-head'>
			      <div>
			        <div class='card-title'>Evolução Mensal</div>
			        <div class='card-sub'>Histórico completo - ignora filtro de data</div>
			      </div>
			      <div style='display:flex;gap:8px;align-items:center'>
			        <div class='dd'>
			          <button class='dd-btn' id='mE-b' data-v='fat' data-t='mE-l' onclick='tgD(&quot;mE-l&quot;)'>Faturamento ▾</button>
			          <div class='dd-list' id='mE-l' data-p='mE' data-fn='rEv' onclick='ddC(event)'>
			            <div class='dd-item act' data-v='fat' data-l='Faturamento'>Faturamento</div>
			            <div class='dd-item' data-v='peso' data-l='Peso'>Peso</div>
			            <div class='dd-item' data-v='pedidos' data-l='Pedidos'>Pedidos</div>
			            <div class='dd-item' data-v='ticket' data-l='Ticket'>Ticket</div>
			            <div class='dd-item' data-v='devRS' data-l='Devolução R$'>Devolução R$</div>
			            <div class='dd-item' data-v='devPeso' data-l='Peso Devolvido'>Peso Devolvido</div>
			          </div>
			        </div>
			        <span style='font-size:11px;color:var(--t3);font-weight:600'>vs</span>
			        <div class='dd'>
			          <button class='dd-btn dd-btn-cmp' id='mE2-b' data-v='none' data-t='mE2-l' onclick='tgD(&quot;mE2-l&quot;)'>Nenhuma ▾</button>
			          <div class='dd-list' id='mE2-l' data-p='mE2' data-fn='rEv' onclick='ddC(event)'>
			            <div class='dd-item act' data-v='none' data-l='Nenhuma'>Nenhuma</div>
			            <div class='dd-item' data-v='fat' data-l='Faturamento'>Faturamento</div>
			            <div class='dd-item' data-v='peso' data-l='Peso'>Peso</div>
			            <div class='dd-item' data-v='pedidos' data-l='Pedidos'>Pedidos</div>
			            <div class='dd-item' data-v='ticket' data-l='Ticket'>Ticket</div>
			            <div class='dd-item' data-v='devRS' data-l='Devolução R$'>Devolução R$</div>
			            <div class='dd-item' data-v='devPeso' data-l='Peso Devolvido'>Peso Devolvido</div>
			          </div>
			        </div>
			      </div>
			    </div>
			    <svg class='cv' id='svgEv' preserveAspectRatio='xMidYMid meet'></svg>
			  </div>
			  <div class='two-col'>
			    <div class='card'>
			      <div class='card-head'>
			        <div><div class='card-title'>Top 10 Produtos</div><div class='card-sub'>Por volume - alterne entre venda e devolução</div></div>
			        <div class='mini-toggle' id='tpToggle'>
			          <button class='on' data-m='venda' onclick='setModoP(&quot;venda&quot;)'>Venda</button>
			          <button data-m='devolucao' onclick='setModoP(&quot;devolucao&quot;)'>Devolução</button>
			        </div>
			      </div>
			      <div class='bars-list' id='topProdutos'></div>
			    </div>
			    <div class='card'>
			      <div class='card-head'>
			        <div><div class='card-title'>Top 10 Clientes</div><div class='card-sub'>Por volume - alterne entre venda e devolução</div></div>
			        <div class='mini-toggle' id='tcToggle'>
			          <button class='on' data-m='venda' onclick='setModoC(&quot;venda&quot;)'>Venda</button>
			          <button data-m='devolucao' onclick='setModoC(&quot;devolucao&quot;)'>Devolução</button>
			        </div>
			      </div>
			      <div class='bars-list' id='topClientes'></div>
			    </div>
			  </div>
			  <div class='card treemap-card'>
			    <div class='card-head'>
			      <div><div class='card-title'>Mix por Grupo de Produto</div><div class='card-sub'>Distribuição do faturamento por grupo</div></div>
			    </div>
			    <svg class='cv' id='svgMix' preserveAspectRatio='xMidYMid meet'></svg>
			  </div>
			  <div class='card'>
			    <div class='card-head'>
			      <div><div class='card-title'>Insights da Operação</div><div class='card-sub'>Detalhamento por dimensão - mini-barras mostram proporção na coluna</div></div>
			      <div class='tabs' id='abasTabs'>
			        <button class='tab on' data-aba='vendedor' onclick='setAba(&quot;vendedor&quot;)'>Vendedor</button>
			        <button class='tab' data-aba='produto' onclick='setAba(&quot;produto&quot;)'>Produto</button>
			        <button class='tab' data-aba='cliente' onclick='setAba(&quot;cliente&quot;)'>Cliente</button>
			        <button class='tab' data-aba='cidade' onclick='setAba(&quot;cidade&quot;)'>Cidade</button>
			        <button class='tab' data-aba='devolucao' onclick='setAba(&quot;devolucao&quot;)'>Devolução</button>
			      </div>
			    </div>
			    <div class='table-wrap' id='tabelaBox'></div>
			  </div>
			</div>
			<div class='tt' id='tt'></div>" &
			"<script type='application/json' id='jKpi'>" & [_JSON KPIs Saude] & "</script>" &
			"<script type='application/json' id='jEv'>" & [_JSON Evolucao Saude] & "</script>" &
			"<script type='application/json' id='jTp'>" & [_JSON Top Produtos Saude] & "</script>" &
			"<script type='application/json' id='jTc'>" & [_JSON Top Clientes Saude] & "</script>" &
			"<script type='application/json' id='jMx'>" & [_JSON Mix Grupo Saude] & "</script>" &
			"<script type='application/json' id='jDv'>" & [_JSON Devolucoes Saude] & "</script>" &
			"<script type='application/json' id='jTv'>" & [_JSON Tabela Vendedor Saude] & "</script>" &
			"<script type='application/json' id='jTpr'>" & [_JSON Tabela Produto Saude] & "</script>" &
			"<script type='application/json' id='jTcl'>" & [_JSON Tabela Cliente Saude] & "</script>" &
			"<script type='application/json' id='jTci'>" & [_JSON Tabela Cidade Saude] & "</script>" &
			"<script type='application/json' id='jTdv'>" & [_JSON Tabela Devolucao Saude] & "</script>" &
			[_JS Saude]
		displayFolder: HTML Saude
		lineageTag: 33d099c9-accd-425d-bc9f-71e5cbbb4e60

	/// Quantidade de vendedores distintos com faturamento > 0 no período filtrado.
	measure 'Vendedores Ativos' =
			CALCULATE(
			    DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR]),
			    DCVVQ_VENDAGERALTELEVENDAS[VLRVENDA] > 0
			)
		formatString: 0
		lineageTag: 9ce60af7-fa22-458e-86c5-7c980d70ffc7

	/// Variação percentual MoM da quantidade de vendedores ativos. Retorna string formatada (ex: +12,3%, -5,0%, 0,0%).
	measure 'MoM Vendedores Ativos %' =
			VAR Atual = [Vendedores Ativos]
			VAR Anterior =
			    CALCULATE([Vendedores Ativos], DATEADD(D_Calendario[Data], -1, MONTH))
			VAR Variacao =
			    DIVIDE(Atual - Anterior, Anterior, 0)
			RETURN
			    FORMAT(Variacao, "+0.0%;-0.0%;0.0%")
		lineageTag: 4696873a-9903-44eb-90c2-0730a763bca0

	/// Variação percentual MoM do total de pedidos. Retorna string formatada (ex: +12,3%, -5,0%, 0,0%).
	measure 'MoM Pedidos %' =
			VAR Atual = [Total de Pedidos]
			VAR Anterior =
			    CALCULATE([Total de Pedidos], DATEADD(D_Calendario[Data], -1, MONTH))
			VAR Variacao =
			    DIVIDE(Atual - Anterior, Anterior, 0)
			RETURN
			    FORMAT(Variacao, "+0.0%;-0.0%;0.0%")
		lineageTag: a1579e44-9c92-4e2e-a6e3-6f2fcdce9234

	/// JSON com dados dos 4 KPIs do HTML Comercial: Faturamento, Pedidos, Ticket Mediano, Vendedores Ativos com MoM%.
	measure '_JSON KPIs Comercial' =
			"{""fat"":"           & SUBSTITUTE(FORMAT(COALESCE([Faturamento Total], 0), "0.##"), ",", ".") &
			",""momFat"":"""      & COALESCE([MoM Faturamento %], "--") & """" &
			",""pedidos"":"       & COALESCE([Total de Pedidos], 0) &
			",""momPedidos"":"""  & COALESCE([MoM Pedidos %], "--") & """" &
			",""ticket"":"        & SUBSTITUTE(FORMAT(COALESCE([Ticket Mediano], 0), "0.##"), ",", ".") &
			",""momTicket"":"""   & COALESCE([MoM Ticket Mediano %], "--") & """" &
			",""vendedores"":"    & COALESCE([Vendedores Ativos], 0) &
			",""momVendedores"":""" & COALESCE([MoM Vendedores Ativos %], "--") & """" &
			"}"
		displayFolder: HTML Comercial
		lineageTag: 540ff715-0661-4a89-9993-be42953df73b

	/// TODOS os vendedores em duas visões (venda e devolucao). Cada item: nome, val (R$), peso, pedidos.
	measure '_JSON Ranking Vendedor Comercial' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR]) && DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_peso",     [Peso Total Vendido],
			        "_pedidos",  [Total de Pedidos],
			        "_devRS",    [Total Devoluções (R$)],
			        "_devPeso",  [Peso Total Devolvido]
			    )
			VAR _venda = FILTER(_com, [_fat] > 0)
			VAR _dev   = FILTER(_com, [_devRS] > 0)
			VAR _arrVenda =
			    "[" & CONCATENATEX(
			        _venda,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR], """""", ""), "\", "") &
			        """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""peso"":"      & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""pedidos"":"   & COALESCE([_pedidos], 0) &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrDev =
			    "[" & CONCATENATEX(
			        _dev,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR], """""", ""), "\", "") &
			        """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""peso"":"      & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""pedidos"":"   & COALESCE([_pedidos], 0) &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			RETURN
			"{""venda"":" & _arrVenda & ",""devolucao"":" & _arrDev & "}"
		displayFolder: HTML Comercial
		lineageTag: 5af8d204-7277-4015-a42a-eb5f736d9ac1

	/// Array JSON com dados por VENDEDOR para a aba Vendedor da tabela do HTML Comercial. Inclui faturamento, peso, pedidos, devolução R$ e taxa de devolução.
	measure '_JSON Tabela Vendedor Comercial' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR]) && DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_peso",     [Peso Total Vendido],
			        "_pedidos",  [Total de Pedidos],
			        "_devRS",    [Total Devoluções (R$)],
			        "_taxaDev",  DIVIDE([Total Devoluções (R$)], [Faturamento Total], 0) * 100
			    )
			VAR _ord = FILTER(_com, [_fat] > 0)
			RETURN
			"[" &
			CONCATENATEX(
			    _ord,
			    "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR], """""", ""), "\", "") &
			    """,""fat"":"        & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""peso"":"         & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""pedidos"":"      & COALESCE([_pedidos], 0) &
			    ",""devRS"":"        & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""taxaDev"":"      & SUBSTITUTE(FORMAT(COALESCE([_taxaDev], 0), "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Comercial
		lineageTag: 55c58ac1-930d-42aa-974e-6438926f12d1

	/// Array JSON com top 200 combinacoes Cliente + Vendedor por faturamento para a aba Cliente+Vendedor do HTML Comercial. Inclui fat, pedidos, dev R$ e taxa.
	measure '_JSON Tabela ClienteVendedor Comercial' =
			VAR _todos =
			    SUMMARIZE(
			        DCVVQ_VENDAGERALTELEVENDAS,
			        DCVVQ_VENDAGERALTELEVENDAS[CLIENTE],
			        DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR]
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_pedidos",  [Total de Pedidos],
			        "_devRS",    [Total Devoluções (R$)],
			        "_taxaDev",  DIVIDE([Total Devoluções (R$)], [Faturamento Total], 0) * 100
			    )
			VAR _filt =
			    FILTER(
			        _com,
			        [_fat] > 0
			        && NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE])
			        && DCVVQ_VENDAGERALTELEVENDAS[CLIENTE] <> ""
			        && NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR])
			        && DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR] <> ""
			    )
			VAR _top = TOPN(200, _filt, [_fat], DESC)
			RETURN
			"[" &
			CONCATENATEX(
			    _top,
			    "{""cliente"":"""  & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE], """""", ""), "\", "") &
			    """,""vendedor"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR], """""", ""), "\", "") &
			    """,""fat"":"      & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""pedidos"":"    & COALESCE([_pedidos], 0) &
			    ",""devRS"":"      & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""taxaDev"":"    & SUBSTITUTE(FORMAT(COALESCE([_taxaDev], 0), "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Comercial
		lineageTag: eb97ee5a-ba05-4c9c-84d5-7f2462825c23

	/// Top 10 grupos de produto em duas visões (venda e devolucao). Cada item: nome, val (R$), peso, qtd.
	measure '_JSON Ranking Grupo Comercial' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO]) && DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_peso",     [Peso Total Vendido],
			        "_qtd",      CALCULATE(SUM(DCVVQ_VENDAGERALTELEVENDAS[QTDVENDA])),
			        "_devRS",    [Total Devoluções (R$)],
			        "_devPeso",  [Peso Total Devolvido],
			        "_devQtd",   CALCULATE(SUM(DCVVQ_VENDAGERALTELEVENDAS[QTDDEVOLVIDA]))
			    )
			VAR _topVenda = TOPN(10, FILTER(_com, [_fat] > 0), [_fat], DESC)
			VAR _topDev   = TOPN(10, FILTER(_com, [_devRS] > 0), [_devRS], DESC)
			VAR _arrVenda =
			    "[" & CONCATENATEX(
			        _topVenda,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO], """""", ""), "\", "") &
			        """,""val"":"   & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""peso"":"    & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""qtd"":"     & SUBSTITUTE(FORMAT(COALESCE([_qtd], 0), "0.00"), ",", ".") &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrDev =
			    "[" & CONCATENATEX(
			        _topDev,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO], """""", ""), "\", "") &
			        """,""val"":"   & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""peso"":"    & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""qtd"":"     & SUBSTITUTE(FORMAT(COALESCE([_devQtd], 0), "0.00"), ",", ".") &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			RETURN
			"{""venda"":" & _arrVenda & ",""devolucao"":" & _arrDev & "}"
		displayFolder: HTML Comercial
		lineageTag: fc0e9490-586e-4c22-8ae5-db449812b1ae

	/// TODOS os subgrupos em duas visões (venda e devolucao).
	measure '_JSON Ranking Subgrupo Comercial' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[SUBGRUPOPROD]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[SUBGRUPOPROD]) && DCVVQ_VENDAGERALTELEVENDAS[SUBGRUPOPROD] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_peso",     [Peso Total Vendido],
			        "_qtd",      CALCULATE(SUM(DCVVQ_VENDAGERALTELEVENDAS[QTDVENDA])),
			        "_devRS",    [Total Devoluções (R$)],
			        "_devPeso",  [Peso Total Devolvido],
			        "_devQtd",   CALCULATE(SUM(DCVVQ_VENDAGERALTELEVENDAS[QTDDEVOLVIDA]))
			    )
			VAR _venda = FILTER(_com, [_fat] > 0)
			VAR _dev   = FILTER(_com, [_devRS] > 0)
			VAR _arrVenda =
			    "[" & CONCATENATEX(
			        _venda,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[SUBGRUPOPROD], """""", ""), "\", "") &
			        """,""val"":"   & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""peso"":"    & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""qtd"":"     & SUBSTITUTE(FORMAT(COALESCE([_qtd], 0), "0.00"), ",", ".") &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrDev =
			    "[" & CONCATENATEX(
			        _dev,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[SUBGRUPOPROD], """""", ""), "\", "") &
			        """,""val"":"   & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""peso"":"    & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""qtd"":"     & SUBSTITUTE(FORMAT(COALESCE([_devQtd], 0), "0.00"), ",", ".") &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			RETURN
			"{""venda"":" & _arrVenda & ",""devolucao"":" & _arrDev & "}"
		displayFolder: HTML Comercial
		lineageTag: c9066c1e-e4cc-4acc-830f-87210ea864f4

	/// TODAS as famílias em duas visões (venda e devolucao).
	measure '_JSON Ranking Familia Comercial' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[DESCRFAMILIA]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[DESCRFAMILIA]) && DCVVQ_VENDAGERALTELEVENDAS[DESCRFAMILIA] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_peso",     [Peso Total Vendido],
			        "_qtd",      CALCULATE(SUM(DCVVQ_VENDAGERALTELEVENDAS[QTDVENDA])),
			        "_devRS",    [Total Devoluções (R$)],
			        "_devPeso",  [Peso Total Devolvido],
			        "_devQtd",   CALCULATE(SUM(DCVVQ_VENDAGERALTELEVENDAS[QTDDEVOLVIDA]))
			    )
			VAR _venda = FILTER(_com, [_fat] > 0)
			VAR _dev   = FILTER(_com, [_devRS] > 0)
			VAR _arrVenda =
			    "[" & CONCATENATEX(
			        _venda,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[DESCRFAMILIA], """""", ""), "\", "") &
			        """,""val"":"   & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""peso"":"    & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""qtd"":"     & SUBSTITUTE(FORMAT(COALESCE([_qtd], 0), "0.00"), ",", ".") &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrDev =
			    "[" & CONCATENATEX(
			        _dev,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[DESCRFAMILIA], """""", ""), "\", "") &
			        """,""val"":"   & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""peso"":"    & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""qtd"":"     & SUBSTITUTE(FORMAT(COALESCE([_devQtd], 0), "0.00"), ",", ".") &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			RETURN
			"{""venda"":" & _arrVenda & ",""devolucao"":" & _arrDev & "}"
		displayFolder: HTML Comercial
		lineageTag: 68c37824-3a8f-4086-96c6-446aeef15cc4

	/// TODOS os produtos em duas visões (venda e devolucao).
	measure '_JSON Ranking Produto Comercial' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO]) && DCVVQ_VENDAGERALTELEVENDAS[PRODUTO] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_peso",     [Peso Total Vendido],
			        "_qtd",      CALCULATE(SUM(DCVVQ_VENDAGERALTELEVENDAS[QTDVENDA])),
			        "_devRS",    [Total Devoluções (R$)],
			        "_devPeso",  [Peso Total Devolvido],
			        "_devQtd",   CALCULATE(SUM(DCVVQ_VENDAGERALTELEVENDAS[QTDDEVOLVIDA]))
			    )
			VAR _venda = FILTER(_com, [_fat] > 0)
			VAR _dev   = FILTER(_com, [_devRS] > 0)
			VAR _arrVenda =
			    "[" & CONCATENATEX(
			        _venda,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO], """""", ""), "\", "") &
			        """,""val"":"   & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""peso"":"    & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""qtd"":"     & SUBSTITUTE(FORMAT(COALESCE([_qtd], 0), "0.00"), ",", ".") &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrDev =
			    "[" & CONCATENATEX(
			        _dev,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO], """""", ""), "\", "") &
			        """,""val"":"   & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""peso"":"    & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""qtd"":"     & SUBSTITUTE(FORMAT(COALESCE([_devQtd], 0), "0.00"), ",", ".") &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			RETURN
			"{""venda"":" & _arrVenda & ",""devolucao"":" & _arrDev & "}"
		displayFolder: HTML Comercial
		lineageTag: 3bc88520-7e62-4cb3-a0c9-b1d0af5488ae

	/// Array JSON com dados por SUBGRUPOPROD para a aba Subgrupo da tabela do HTML Comercial.
	measure '_JSON Tabela Subgrupo Comercial' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[SUBGRUPOPROD]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[SUBGRUPOPROD]) && DCVVQ_VENDAGERALTELEVENDAS[SUBGRUPOPROD] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_peso",     [Peso Total Vendido],
			        "_pedidos",  [Total de Pedidos],
			        "_devRS",    [Total Devoluções (R$)],
			        "_taxaDev",  DIVIDE([Total Devoluções (R$)], [Faturamento Total], 0) * 100
			    )
			VAR _ord = FILTER(_com, [_fat] > 0)
			RETURN
			"[" &
			CONCATENATEX(
			    _ord,
			    "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[SUBGRUPOPROD], """""", ""), "\", "") &
			    """,""fat"":"        & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""peso"":"         & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""pedidos"":"      & COALESCE([_pedidos], 0) &
			    ",""devRS"":"        & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""taxaDev"":"      & SUBSTITUTE(FORMAT(COALESCE([_taxaDev], 0), "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Comercial
		lineageTag: a22c09e1-7c99-47bc-b5a7-9e29236f3671

	/// Array JSON com dados por DESCRFAMILIA para a aba Familia da tabela do HTML Comercial.
	measure '_JSON Tabela Familia Comercial' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[DESCRFAMILIA]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[DESCRFAMILIA]) && DCVVQ_VENDAGERALTELEVENDAS[DESCRFAMILIA] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_peso",     [Peso Total Vendido],
			        "_pedidos",  [Total de Pedidos],
			        "_devRS",    [Total Devoluções (R$)],
			        "_taxaDev",  DIVIDE([Total Devoluções (R$)], [Faturamento Total], 0) * 100
			    )
			VAR _ord = FILTER(_com, [_fat] > 0)
			RETURN
			"[" &
			CONCATENATEX(
			    _ord,
			    "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[DESCRFAMILIA], """""", ""), "\", "") &
			    """,""fat"":"        & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""peso"":"         & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""pedidos"":"      & COALESCE([_pedidos], 0) &
			    ",""devRS"":"        & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""taxaDev"":"      & SUBSTITUTE(FORMAT(COALESCE([_taxaDev], 0), "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Comercial
		lineageTag: af2d45a5-fe82-45f2-9a59-17c35dc8266f

	/// Array JSON com dados por PRODUTO para a aba Produto da tabela do HTML Comercial. Inclui grupo, fat, peso, pedidos, devolução R$ e taxa de devolução.
	measure '_JSON Tabela Produto Comercial' =
			VAR _todos =
			    SUMMARIZE(
			        DCVVQ_VENDAGERALTELEVENDAS,
			        DCVVQ_VENDAGERALTELEVENDAS[PRODUTO],
			        DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO]
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_peso",     [Peso Total Vendido],
			        "_pedidos",  [Total de Pedidos],
			        "_devRS",    [Total Devoluções (R$)],
			        "_taxaDev",  DIVIDE([Total Devoluções (R$)], [Faturamento Total], 0) * 100
			    )
			VAR _ord =
			    FILTER(
			        _com,
			        [_fat] > 0
			        && NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO])
			        && DCVVQ_VENDAGERALTELEVENDAS[PRODUTO] <> ""
			    )
			RETURN
			"[" &
			CONCATENATEX(
			    _ord,
			    "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO], """""", ""), "\", "") &
			    """,""grupo"":"""    & SUBSTITUTE(SUBSTITUTE(COALESCE(DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO], ""), """""", ""), "\", "") &
			    """,""fat"":"        & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""peso"":"         & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""pedidos"":"      & COALESCE([_pedidos], 0) &
			    ",""devRS"":"        & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""taxaDev"":"      & SUBSTITUTE(FORMAT(COALESCE([_taxaDev], 0), "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Comercial
		lineageTag: 644723c5-5dd6-421a-85a3-fcc1dacae69f

	/// Dashboard HTML Comercial v11: revisao ortografica completa - acentos PT-BR aplicados em todos os textos visiveis.
	measure 'HTML Comercial' =
			"<style>:root {
			  --bg:    #EEEAE2;
			  --surf:  #FFFFFF;
			  --surf2: #F7F3EB;
			  --bd:    rgba(26,26,26,.07);
			  --bd2:   rgba(26,26,26,.15);
			  --t1:    #1A1A1A;
			  --t2:    #5A5A5A;
			  --t3:    #8B8B8B;
			  --gold:  #B8935A;
			  --goldS: #EAD9BE;
			  --dark:  #1E1E1E;
			  --grn:   #4E7D62;
			  --org:   #C07C3A;
			  --blu:   #4A6E8A;
			  --red:   #A04848;
			  --sh1:   0 1px 3px rgba(0,0,0,.06);
			  --sh2:   0 2px 10px rgba(0,0,0,.1);
			  --r:     10px;
			  --ease:  cubic-bezier(.4,0,.2,1);
			}
			* { box-sizing: border-box; margin: 0; padding: 0; }
			html, body {
			  background: var(--bg);
			  font-family: 'Segoe UI', system-ui, sans-serif;
			  font-size: 14px; color: var(--t1);
			  -webkit-font-smoothing: antialiased;
			  min-height: 100vh;
			}
			.dash { padding: 14px 16px; display: flex; flex-direction: column; gap: 12px; }
			.hdr { display: flex; align-items: center; justify-content: space-between; padding: 0 2px; }
			.hdr-title { font-size: 25px; font-weight: 700; letter-spacing: -.5px; }
			.hdr-sub { font-size: 13px; color: var(--t3); margin-left: 8px; }
			.kpi-row { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; }
			.kpi { background: var(--surf); border-radius: var(--r); padding: 14px 16px; box-shadow: var(--sh1); border: 1px solid var(--bd); }
			.kpi-top { display: flex; align-items: flex-start; justify-content: space-between; gap: 8px; }
			.kpi-label { font-size: 12.5px; color: var(--t2); font-weight: 500; }
			.kpi-icon { width: 30px; height: 30px; border-radius: 8px; background: linear-gradient(135deg, var(--goldS), #F0E4CC); display: flex; align-items: center; justify-content: center; color: var(--gold); flex-shrink: 0; }
			.kpi-icon svg { width: 14px; height: 14px; }
			.kpi-val { font-size: 32px; font-weight: 700; letter-spacing: -.6px; line-height: 1.1; font-variant-numeric: tabular-nums; margin-top: 6px; }
			.kpi-sub { font-size: 12.5px; color: var(--t3); margin-top: 4px; }
			.kpi-sub .up { color: var(--grn); font-weight: 600; }
			.kpi-sub .down { color: var(--red); font-weight: 600; }
			.kpi-sub .neu { color: var(--gold); font-weight: 600; }
			.card { background: var(--surf); border-radius: var(--r); padding: 12px 14px; box-shadow: var(--sh1); border: 1px solid var(--bd); }
			.card-head { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 10px; gap: 10px; flex-wrap: wrap; }
			.card-title { font-size: 16px; font-weight: 600; letter-spacing: -.2px; }
			.card-sub { font-size: 12px; color: var(--t3); margin-top: 1px; }
			.toggle-group { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
			.mini-toggle, .tri-toggle { display: flex; background: var(--surf2); border: 1px solid var(--bd2); border-radius: 100px; overflow: hidden; }
			.mini-toggle button, .tri-toggle button { padding: 5px 13px; font-size: 12px; font-weight: 600; border: none; background: transparent; color: var(--t2); cursor: pointer; font-family: inherit; transition: all .15s; }
			.mini-toggle button.on, .tri-toggle button.on { background: var(--dark); color: #fff; border-radius: 100px; }
			.two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; align-items: stretch; }
			.two-col > .card { display: flex; flex-direction: column; }
			.bars-list-scroll { display: flex; flex-direction: column; gap: 9px; max-height: 380px; overflow-y: auto; padding-right: 6px; }
			.bars-list-scroll::-webkit-scrollbar { width: 6px; }
			.bars-list-scroll::-webkit-scrollbar-track { background: rgba(26,26,26,.04); border-radius: 100px; }
			.bars-list-scroll::-webkit-scrollbar-thumb { background: var(--goldS); border-radius: 100px; }
			.bars-list-scroll::-webkit-scrollbar-thumb:hover { background: var(--gold); }
			.bar-row { cursor: default; }
			.bar-head { display: flex; justify-content: space-between; gap: 8px; margin-bottom: 4px; }
			.bar-name { font-size: 13px; color: #1A1A1A; font-weight: 500; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; flex: 1; min-width: 0; }
			.bar-val { font-size: 13px; font-weight: 700; font-variant-numeric: tabular-nums; color: var(--t1); }
			.bar-track { height: 6px; background: #EAD9BE; border-radius: 100px; overflow: hidden; }
			.bar-fill { height: 100%; border-radius: 100px; background: linear-gradient(90deg, #1A1A1A, var(--gold)); width: 0; transition: width .8s var(--ease); }
			.donut-card { display: flex; flex-direction: column; }
			.donut-svg-wrap { flex: 1; min-height: 0; display: flex; }
			.donut-svg-wrap svg { width: 100%; height: 100%; display: block; }
			.donut-slice { transition: opacity .2s; cursor: pointer; }
			.donut-slice:hover { opacity: .85; }
			.chart-vert-wrap { overflow-x: auto; overflow-y: hidden; padding-bottom: 4px; }
			.chart-vert-wrap::-webkit-scrollbar { height: 8px; }
			.chart-vert-wrap::-webkit-scrollbar-track { background: rgba(26,26,26,.04); border-radius: 100px; }
			.chart-vert-wrap::-webkit-scrollbar-thumb { background: var(--goldS); border-radius: 100px; }
			.chart-vert-wrap::-webkit-scrollbar-thumb:hover { background: var(--gold); }
			.chart-vert-wrap svg .vbar { transition: opacity .2s; cursor: pointer; }
			.chart-vert-wrap svg .vbar:hover { opacity: .80; }
			.tabs { display: flex; gap: 4px; background: var(--surf2); padding: 3px; border-radius: 100px; border: 1px solid var(--bd2); flex-wrap: wrap; }
			.tab { padding: 6px 15px; font-size: 12.5px; font-weight: 600; border: none; background: transparent; color: var(--t2); cursor: pointer; font-family: inherit; border-radius: 100px; transition: all .15s; }
			.tab.on { background: var(--dark); color: #fff; }
			.table-wrap { overflow-x: auto; max-height: 460px; overflow-y: auto; border-radius: 8px; }
			.tbl { width: 100%; border-collapse: collapse; font-size: 13px; }
			.tbl th { position: sticky; top: 0; background: var(--surf2); padding: 10px 12px; text-align: left; font-weight: 600; color: var(--t2); border-bottom: 1px solid var(--bd2); font-size: 12px; text-transform: uppercase; letter-spacing: .3px; z-index: 2; }
			.tbl th.th-num { text-align: right; }
			.tbl td { padding: 7px 10px; border-bottom: 1px solid var(--bd); vertical-align: middle; }
			.tbl tr:hover td { background: var(--surf2); }
			.tbl td.td-name { font-weight: 500; color: var(--t1); }
			.tbl td.td-tag { color: var(--t2); font-size: 12px; }
			.tbl td.td-num { text-align: right; font-variant-numeric: tabular-nums; font-weight: 600; color: var(--t1); min-width: 100px; }
			.cell-val { display: block; }
			.cell-bar { height: 3px; background: rgba(26,26,26,.04); border-radius: 100px; overflow: hidden; margin-top: 3px; }
			.cell-fill { height: 100%; background: linear-gradient(90deg, #1A1A1A, var(--gold)); border-radius: 100px; }
			.tag-badge { display: inline-block; padding: 3px 10px; border-radius: 100px; font-size: 11.5px; font-weight: 600; letter-spacing: .2px; white-space: nowrap; }
			.tt { position: fixed; background: #1E1E1E; color: #fff; padding: 7px 12px; border-radius: 7px; font-size: 12.5px; pointer-events: none; opacity: 0; transition: opacity .15s; z-index: 9999; white-space: nowrap; box-shadow: 0 4px 20px rgba(0,0,0,.2); }
			.tt.on { opacity: 1; }
			.tt b { color: #D4B687; }
			</style>" &
			"<div class='dash'>
			  <div class='hdr'>
			    <div>
			      <span class='hdr-title'>Comercial</span>
			      <span class='hdr-sub'>Performance por vendedor e produto</span>
			    </div>
			  </div>
			  <div class='kpi-row' id='kpiGrid'></div>
			  <div class='two-col'>
			    <div class='card'>
			      <div class='card-head'>
			        <div>
			          <div class='card-title'>Ranking de Vendedores</div>
			          <div class='card-sub'>Todos os vendedores - rolagem vertical</div>
			        </div>
			        <div class='mini-toggle' id='vendModoToggle'>
			          <button class='on' data-m='venda' onclick='setModoV(&quot;venda&quot;)'>Venda</button>
			          <button data-m='devolucao' onclick='setModoV(&quot;devolucao&quot;)'>Devolução</button>
			        </div>
			      </div>
			      <div class='bars-list-scroll' id='rankingVend'></div>
			    </div>
			    <div class='card donut-card'>
			      <div class='card-head'>
			        <div>
			          <div class='card-title'>Mix por Grupo de Produto</div>
			          <div class='card-sub'>Participação dos grupos - alterne Venda / Devolução</div>
			        </div>
			        <div class='mini-toggle' id='grupoModoToggle'>
			          <button class='on' data-m='venda' onclick='setModoG(&quot;venda&quot;)'>Venda</button>
			          <button data-m='devolucao' onclick='setModoG(&quot;devolucao&quot;)'>Devolução</button>
			        </div>
			      </div>
			      <div class='donut-svg-wrap'><svg id='svgGrupo' preserveAspectRatio='xMidYMid meet'></svg></div>
			    </div>
			  </div>
			  <div class='card'>
			    <div class='card-head'>
			      <div>
			        <div class='card-title'>Top 15 - Análise Hierárquica de Produto</div>
			        <div class='card-sub'>Barras verticais com rótulo de dados - escolha o nível e o modo</div>
			      </div>
			      <div class='toggle-group'>
			        <div class='tri-toggle' id='prodHierToggle'>
			          <button class='on' data-p='familia' onclick='setModoP(&quot;familia&quot;)'>Família</button>
			          <button data-p='produto' onclick='setModoP(&quot;produto&quot;)'>Produto</button>
			          <button data-p='subgrupo' onclick='setModoP(&quot;subgrupo&quot;)'>Subgrupo</button>
			        </div>
			        <div class='mini-toggle' id='prodModoToggle'>
			          <button class='on' data-m='venda' onclick='setModoR(&quot;venda&quot;)'>Venda</button>
			          <button data-m='devolucao' onclick='setModoR(&quot;devolucao&quot;)'>Devolução</button>
			        </div>
			      </div>
			    </div>
			    <div class='chart-vert-wrap' id='analiseProd'></div>
			  </div>
			  <div class='card'>
			    <div class='card-head'>
			      <div><div class='card-title'>Insights da Operação</div><div class='card-sub'>Detalhamento por dimensão - mini-barras nas colunas R$</div></div>
			      <div class='tabs' id='abasTabs'>
			        <button class='tab on' data-aba='vendedor' onclick='setAba(&quot;vendedor&quot;)'>Vendedor</button>
			        <button class='tab' data-aba='produto' onclick='setAba(&quot;produto&quot;)'>Produto</button>
			        <button class='tab' data-aba='subgrupo' onclick='setAba(&quot;subgrupo&quot;)'>Subgrupo</button>
			        <button class='tab' data-aba='familia' onclick='setAba(&quot;familia&quot;)'>Família</button>
			        <button class='tab' data-aba='clivend' onclick='setAba(&quot;clivend&quot;)'>Cliente + Vendedor</button>
			      </div>
			    </div>
			    <div class='table-wrap' id='tabelaBox'></div>
			  </div>
			</div>
			<div class='tt' id='tt'></div>" &
			"<script type='application/json' id='jKpi'>" & [_JSON KPIs Comercial] & "</script>" &
			"<script type='application/json' id='jRvd'>" & [_JSON Ranking Vendedor Comercial] & "</script>" &
			"<script type='application/json' id='jRgr'>" & [_JSON Ranking Grupo Comercial] & "</script>" &
			"<script type='application/json' id='jRsg'>" & [_JSON Ranking Subgrupo Comercial] & "</script>" &
			"<script type='application/json' id='jRfm'>" & [_JSON Ranking Familia Comercial] & "</script>" &
			"<script type='application/json' id='jRpd'>" & [_JSON Ranking Produto Comercial] & "</script>" &
			"<script type='application/json' id='jTvd'>" & [_JSON Tabela Vendedor Comercial] & "</script>" &
			"<script type='application/json' id='jTpr'>" & [_JSON Tabela Produto Comercial] & "</script>" &
			"<script type='application/json' id='jTsg'>" & [_JSON Tabela Subgrupo Comercial] & "</script>" &
			"<script type='application/json' id='jTfm'>" & [_JSON Tabela Familia Comercial] & "</script>" &
			"<script type='application/json' id='jTcv'>" & [_JSON Tabela ClienteVendedor Comercial] & "</script>" &
			[_JS Comercial]
		displayFolder: HTML Comercial
		lineageTag: e78df333-9923-479d-bfe9-90787c031559

	/// JS Comercial v15 - grafico Top 15 com H=500 e P.b=70 (elimina espaco em branco abaixo dos nomes).
	measure '_JS Comercial' =
			"<script>" & "(function () {
			  'use strict';
			  function rJ(id) { var e = document.getElementById(id); try { return JSON.parse((e && e.textContent) || 'null'); } catch (ex) { return null; } }
			  function esc(v) { return String(v == null ? '' : v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
			  function escT(v) { return esc(v).replace(/'/g,'&#39;'); }
			  function fN(v) { return (Number(v) || 0).toLocaleString('pt-BR'); }
			  function fA(v) { v = Number(v) || 0; if (Math.abs(v) >= 1e6) return (v/1e6).toFixed(1).replace('.',',') + ' M'; if (Math.abs(v) >= 1e3) return (v/1e3).toFixed(1).replace('.',',') + ' mil'; return fN(v); }
			  function fM(v) { v = Number(v) || 0; return 'R$ ' + v.toLocaleString('pt-BR', {minimumFractionDigits:2, maximumFractionDigits:2}); }
			  function fMK(v) { v = Number(v) || 0; if (Math.abs(v) >= 1e6) return 'R$ ' + (v/1e6).toFixed(2).replace('.',',') + ' M'; if (Math.abs(v) >= 1e3) return 'R$ ' + (v/1e3).toFixed(1).replace('.',',') + ' mil'; return fM(v); }
			  function fPct(v) { return (Number(v)||0).toFixed(2).replace('.',',') + '%'; }
			  function momCls(s) { if (!s || s === '--') return 'neu'; return s.indexOf('+') === 0 ? 'up' : (s.indexOf('-') === 0 ? 'down' : 'neu'); }
			  function svgDim(el, fbW, fbH) { var bb = el.getBoundingClientRect(); return [Math.round(bb.width) || fbW, Math.round(bb.height) || fbH]; }
			  function tagColor(str) {
			    if (!str) return {bg:'rgba(139,139,139,.12)',fg:'#5A5A5A'};
			    var h=0; for (var i=0;i<str.length;i++) h = ((h<<5)-h) + str.charCodeAt(i);
			    var palette = [
			      {bg:'rgba(184,147,90,.15)',fg:'#8A6740'},
			      {bg:'rgba(78,125,98,.15)',fg:'#3D6049'},
			      {bg:'rgba(74,110,138,.15)',fg:'#3A5872'},
			      {bg:'rgba(192,124,58,.15)',fg:'#995F2C'},
			      {bg:'rgba(58,36,16,.12)',fg:'#3A2410'},
			      {bg:'rgba(90,90,90,.15)',fg:'#5A5A5A'}
			    ];
			    return palette[Math.abs(h) % palette.length];
			  }
			  var ttEl = document.getElementById('tt');
			  window.tip = function(e,h){ if (!ttEl) return; ttEl.innerHTML = h; ttEl.classList.add('on'); ttEl.style.left = (e.clientX+14)+'px'; ttEl.style.top = (e.clientY-36)+'px'; };
			  window.tipOff = function(){ ttEl && ttEl.classList.remove('on'); };
			  var kpiIcons = {
			    money: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><line x1='12' y1='1' x2='12' y2='23'/><path d='M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6'/></svg>"",
			    bag: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><path d='M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z'/><line x1='3' y1='6' x2='21' y2='6'/><path d='M16 10a4 4 0 0 1-8 0'/></svg>"",
			    target: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><circle cx='12' cy='12' r='10'/><circle cx='12' cy='12' r='6'/><circle cx='12' cy='12' r='2'/></svg>"",
			    users: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><path d='M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2'/><circle cx='9' cy='7' r='4'/><path d='M23 21v-2a4 4 0 0 0-3-3.87'/><path d='M16 3.13a4 4 0 0 1 0 7.75'/></svg>""
			  };
			  function buildKPIs(){
			    var K=rJ('jKpi')||{}; var el=document.getElementById('kpiGrid'); if(!el) return;
			    var cards=[
			      {icon:'money',label:'Faturamento Total',val:fMK(K.fat||0),sub:'MoM = <span class=\''+momCls(K.momFat)+'\'>'+(K.momFat||'-')+'</span>'},
			      {icon:'bag',label:'Total de Pedidos',val:fN(K.pedidos||0),sub:'MoM = <span class=\''+momCls(K.momPedidos)+'\'>'+(K.momPedidos||'-')+'</span>'},
			      {icon:'target',label:'Ticket Mediano',val:fMK(K.ticket||0),sub:'MoM = <span class=\''+momCls(K.momTicket)+'\'>'+(K.momTicket||'-')+'</span>'},
			      {icon:'users',label:'Vendedores Ativos',val:fN(K.vendedores||0),sub:'MoM = <span class=\''+momCls(K.momVendedores)+'\'>'+(K.momVendedores||'-')+'</span>'}
			    ];
			    el.innerHTML=cards.map(function(c){ return ""<div class='kpi'><div class='kpi-top'><span class='kpi-label'>""+c.label+""</span><div class='kpi-icon'>""+kpiIcons[c.icon]+""</div></div><div class='kpi-val'>""+c.val+""</div><div class='kpi-sub'>""+c.sub+""</div></div>""; }).join('');
			  }
			  var _modoV='venda';
			  window.setModoV=function(m){ _modoV=m; document.querySelectorAll('#vendModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderRankingVendedor(); };
			  function renderRankingVendedor(){
			    var el=document.getElementById('rankingVend'); if(!el) return;
			    var data=rJ('jRvd')||{venda:[],devolucao:[]};
			    var arr=data[_modoV]||[];
			    if(!arr.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Math.max.apply(null,arr.map(function(d){ return Number(d.val)||0; }).concat([1]));
			    var lbl=_modoV==='venda'?'Faturamento':'Devolução';
			    el.innerHTML=arr.map(function(d){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      var tt='<b>'+escT(d.nome)+'</b><br>'+lbl+': '+fMK(v)+'<br>Peso: '+fA(Number(d.peso)||0)+' kg<br>Pedidos: '+fN(Number(d.pedidos)||0);
			      return ""<div class='bar-row' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'><div class='bar-head'><div class='bar-name'>""+esc(d.nome)+""</div><div class='bar-val'>""+fMK(v)+""</div></div><div class='bar-track'><div class='bar-fill' data-w='""+w+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.bar-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  var _modoG='venda';
			  window.setModoG=function(m){ _modoG=m; document.querySelectorAll('#grupoModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderRoscaGrupo(); };
			  function renderRoscaGrupo(){
			    var el=document.getElementById('svgGrupo'); if(!el) return;
			    var d=svgDim(el,420,360); var W=d[0],H=d[1];
			    el.setAttribute('viewBox','0 0 '+W+' '+H);
			    var data=rJ('jRgr')||{venda:[],devolucao:[]};
			    var arr=(data[_modoG]||[]).filter(function(d2){ return (Number(d2.val)||0) > 0; });
			    if(!arr.length){ el.innerHTML=""<text x='""+(W/2)+""' y='""+(H/2)+""' text-anchor='middle' fill='#999'>Sem dados</text>""; return; }
			    var total=arr.reduce(function(s,d2){ return s + (Number(d2.val)||0); }, 0);
			    if(total<=0) total=1;
			    var colors=['#1A1A1A','#B8935A','#4E7D62','#C07C3A','#4A6E8A','#5A5A5A'];
			    var cx=W*0.30, cy=H/2;
			    var r=Math.min(W*0.26, H*0.40), ri=r*0.58;
			    var start=-Math.PI/2;
			    var svg='';
			    arr.forEach(function(d2,i){
			      var v=Number(d2.val)||0;
			      var ang=(v/total)*Math.PI*2;
			      var end=start+ang;
			      var largeArc = ang > Math.PI ? 1 : 0;
			      var x1=cx+r*Math.cos(start), y1=cy+r*Math.sin(start);
			      var x2=cx+r*Math.cos(end),   y2=cy+r*Math.sin(end);
			      var xi1=cx+ri*Math.cos(end), yi1=cy+ri*Math.sin(end);
			      var xi2=cx+ri*Math.cos(start), yi2=cy+ri*Math.sin(start);
			      var dPath='M '+x1.toFixed(2)+' '+y1.toFixed(2) +
			                ' A '+r.toFixed(2)+' '+r.toFixed(2)+' 0 '+largeArc+' 1 '+x2.toFixed(2)+' '+y2.toFixed(2) +
			                ' L '+xi1.toFixed(2)+' '+yi1.toFixed(2) +
			                ' A '+ri.toFixed(2)+' '+ri.toFixed(2)+' 0 '+largeArc+' 0 '+xi2.toFixed(2)+' '+yi2.toFixed(2) +
			                ' Z';
			      var pct=(v/total*100).toFixed(1).replace('.',',');
			      var color=colors[i % colors.length];
			      var ttHtml='<b>'+escT(d2.nome)+'</b><br>'+(_modoG==='venda'?'Faturamento':'Devolução')+': '+fMK(v)+'<br>'+pct+'% do total';
			      svg += ""<path class='donut-slice' d='""+dPath+""' fill='""+color+""' stroke='#FFFFFF' stroke-width='2' onmousemove=\""tip(event,'""+ttHtml+""')\"" onmouseleave='tipOff()'/>"";
			      start=end;
			    });
			    var lblCentro=_modoG==='venda'?'FATURAMENTO':'DEVOLUÇÃO';
			    svg += ""<text x='""+cx+""' y='""+(cy-2)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:22px;font-weight:700;font-family:Segoe UI,system-ui'>""+fMK(total)+""</text>"";
			    svg += ""<text x='""+cx+""' y='""+(cy+18)+""' text-anchor='middle' fill='#8B8B8B' style='font-size:11px;font-weight:600;letter-spacing:1.8px;font-family:Segoe UI,system-ui'>""+lblCentro+""</text>"";
			    var lx=W*0.58;
			    var step=48;
			    var ly=Math.max(32, (H - arr.length*step)/2 + 16);
			    arr.forEach(function(d2,i){
			      var v=Number(d2.val)||0;
			      var pct=(v/total*100).toFixed(1).replace('.',',');
			      var color=colors[i % colors.length];
			      var y=ly + i*step;
			      svg += ""<rect x='""+lx+""' y='""+(y-11)+""' width='14' height='14' rx='3' fill='""+color+""'/>"";
			      svg += ""<text x='""+(lx+22)+""' y='""+y+""' fill='#1A1A1A' style='font-size:14px;font-weight:600;font-family:Segoe UI,system-ui'>""+esc(d2.nome)+""</text>"";
			      svg += ""<text x='""+(lx+22)+""' y='""+(y+18)+""' style='font-size:12.5px;font-family:Segoe UI,system-ui'><tspan fill='#5A5A5A'>""+fMK(v)+""</tspan> <tspan fill='#B8935A' font-weight='700'>""+pct+""%</tspan></text>"";
			    });
			    el.innerHTML=svg;
			  }
			  var _modoP='familia', _modoR='venda';
			  window.setModoP=function(m){ _modoP=m; document.querySelectorAll('#prodHierToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.p===m); }); renderAnaliseProduto(); };
			  window.setModoR=function(m){ _modoR=m; document.querySelectorAll('#prodModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderAnaliseProduto(); };
			  function renderAnaliseProduto(){
			    var el=document.getElementById('analiseProd'); if(!el) return;
			    var sources={subgrupo:'jRsg', familia:'jRfm', produto:'jRpd'};
			    var data=rJ(sources[_modoP])||{venda:[],devolucao:[]};
			    var arr=(data[_modoR]||[]).slice(0,15);
			    if(!arr.length){ el.innerHTML=""<div style='padding:30px;color:#8B8B8B;text-align:center'>Sem dados</div>""; return; }
			    var H=500;
			    var P={t:38, r:24, b:70, l:68};
			    var n=arr.length;
			    var containerW = el.clientWidth || 900;
			    var availW = containerW - P.l - P.r;
			    var minBarW = 30;
			    var maxBarW = 56;
			    var defaultGap = 18;
			    var maxGap = 40;
			    var idealBarW = (availW - (n-1)*defaultGap) / Math.max(n,1);
			    var barW, gap, contentW, startX;
			    if (idealBarW >= maxBarW) {
			      barW = maxBarW;
			      var remaining = availW - n*barW;
			      gap = n > 1 ? Math.min(maxGap, remaining / (n-1)) : 0;
			      var totalBarsW = n*barW + (n-1)*gap;
			      startX = P.l + Math.max(0, (availW - totalBarsW) / 2);
			      contentW = containerW;
			    } else if (idealBarW >= minBarW) {
			      barW = idealBarW;
			      gap = defaultGap;
			      startX = P.l;
			      contentW = containerW;
			    } else {
			      barW = minBarW;
			      gap = defaultGap;
			      startX = P.l;
			      contentW = n*barW + (n-1)*gap + P.l + P.r;
			    }
			    var W = Math.max(contentW, containerW);
			    var mx = Math.max.apply(null, arr.map(function(d){ return Number(d.val)||0; }).concat([1])) * 1.10;
			    var lblFn = _modoR==='venda' ? 'Faturamento' : 'Devolução';
			    var uid = 'b' + Math.floor(Math.random()*99999);
			    var maxWordChars = barW < 40 ? 10 : 14;
			    var svg = ""<defs><linearGradient id='bg""+uid+""' x1='0%' y1='0%' x2='0%' y2='100%'><stop offset='0%' stop-color='#B8935A' stop-opacity='1'/><stop offset='100%' stop-color='#1A1A1A' stop-opacity='1'/></linearGradient></defs>"";
			    for (var i=0; i<=4; i++){
			      var y = P.t + (H - P.t - P.b) * i / 4;
			      var v = mx * (1 - i/4);
			      svg += ""<line x1='""+P.l+""' x2='""+(W-P.r)+""' y1='""+y.toFixed(1)+""' y2='""+y.toFixed(1)+""' stroke='rgba(0,0,0,.06)' stroke-dasharray='3,4'/>"";
			      if (i<4) svg += ""<text x='""+(P.l-6)+""' y='""+(y+4).toFixed(1)+""' text-anchor='end' fill='#8B8B8B' style='font-size:12.5px;font-family:Segoe UI,system-ui;font-weight:500'>""+fA(v)+""</text>"";
			    }
			    arr.forEach(function(d, i){
			      var v = Number(d.val)||0;
			      var bh = Math.max(2, (v/mx) * (H - P.t - P.b));
			      var bx = startX + i*(barW+gap);
			      var by = H - P.b - bh;
			      var labelX = bx + barW/2;
			      var tt = '<b>'+escT(d.nome)+'</b><br>'+lblFn+': '+fMK(v)+'<br>Peso: '+fA(Number(d.peso)||0)+' kg<br>Qtd: '+fA(Number(d.qtd)||0);
			      svg += ""<rect class='vbar' x='""+bx.toFixed(1)+""' y='""+by.toFixed(1)+""' width='""+barW.toFixed(1)+""' height='""+bh.toFixed(1)+""' rx='3' fill='url(#bg""+uid+"")' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'/>"";
			      svg += ""<text x='""+labelX.toFixed(1)+""' y='""+(by-8).toFixed(1)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:11.5px;font-weight:700;font-variant-numeric:tabular-nums;font-family:Segoe UI,system-ui;pointer-events:none'>R$ ""+fA(v)+""</text>"";
			      var words = d.nome.split(/\s+/);
			      var displayWords = words.slice(0, 4).map(function(w){ return w.length > maxWordChars ? w.slice(0, maxWordChars-2) + '..' : w; });
			      var nameY = H - P.b + 16;
			      displayWords.forEach(function(w, j){
			        svg += ""<text x='""+labelX.toFixed(1)+""' y='""+(nameY + j*14)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:11.5px;font-weight:500;font-family:Segoe UI,system-ui'>""+esc(w)+""</text>"";
			      });
			    });
			    el.innerHTML = ""<svg width='""+W+""' height='""+H+""' xmlns='http://www.w3.org/2000/svg'>""+svg+""</svg>"";
			  }
			  var _aba='vendedor';
			  window.setAba=function(aba){ _aba=aba; document.querySelectorAll('#abasTabs .tab').forEach(function(t){ t.classList.toggle('on', t.dataset.aba===aba); }); renderTabela(); };
			  function renderTabela(){
			    var el=document.getElementById('tabelaBox'); if(!el) return;
			    var data, cols;
			    if(_aba==='vendedor'){ data=rJ('jTvd')||[]; cols=[{k:'nome',t:'Vendedor',cls:'name'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'peso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'devRS',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else if(_aba==='produto'){ data=rJ('jTpr')||[]; cols=[{k:'nome',t:'Produto',cls:'name'},{k:'grupo',t:'Grupo',cls:'tag'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'peso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'devRS',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else if(_aba==='subgrupo'){ data=rJ('jTsg')||[]; cols=[{k:'nome',t:'Subgrupo',cls:'name'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'peso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'devRS',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else if(_aba==='familia'){ data=rJ('jTfm')||[]; cols=[{k:'nome',t:'Família',cls:'name'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'peso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'devRS',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else { data=rJ('jTcv')||[]; cols=[{k:'cliente',t:'Cliente',cls:'name'},{k:'vendedor',t:'Vendedor',cls:'tag'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'devRS',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    if(!data.length){ el.innerHTML=""<div style='padding:20px;color:#8B8B8B;text-align:center'>Sem dados</div>""; return; }
			    var maxNum={};
			    cols.forEach(function(c){ if(c.cls==='num' && c.bar){ maxNum[c.k]=Math.max.apply(null, data.map(function(d){return Number(d[c.k])||0;}).concat([1])); } });
			    var head=""<thead><tr>"" + cols.map(function(c){ return ""<th class='th-""+c.cls+""'>""+c.t+""</th>""; }).join('') + ""</tr></thead>"";
			    var body=""<tbody>"" + data.map(function(d){
			      return ""<tr>"" + cols.map(function(c){
			        var v=d[c.k]; var text=c.fmt?c.fmt(v):esc(v);
			        if(c.cls==='num' && c.bar){
			          var n=Number(v)||0; var pct=Math.max(0,(n/maxNum[c.k])*100);
			          return ""<td class='td-num'><div class='cell-val'>""+text+""</div><div class='cell-bar'><div class='cell-fill' style='width:""+pct.toFixed(1)+""%'></div></div></td>"";
			        }
			        if(c.cls==='tag'){
			          var clr=tagColor(v);
			          return ""<td class='td-tag'><span class='tag-badge' style='background:""+clr.bg+"";color:""+clr.fg+""'>""+esc(v||'-')+""</span></td>"";
			        }
			        return ""<td class='td-""+c.cls+""'>""+text+""</td>"";
			      }).join('') + ""</tr>"";
			    }).join('') + ""</tbody>"";
			    el.innerHTML=""<table class='tbl'>"" + head + body + ""</table>"";
			  }
			  function renderAll(){
			    if(!document.getElementById('kpiGrid')) return false;
			    try { buildKPIs(); renderRankingVendedor(); renderRoscaGrupo(); renderAnaliseProduto(); renderTabela(); return true; }
			    catch(e){ console.error(e); return false; }
			  }
			  var _prevHash='';
			  function dataHash(){
			    return ['jKpi','jRvd','jRgr','jRsg','jRfm','jRpd','jTvd','jTpr','jTsg','jTfm','jTcv'].map(function(id){
			      var e=document.getElementById(id); if(!e) return '';
			      return e.textContent.length+'|'+e.textContent.slice(0,20);
			    }).join('~');
			  }
			  setInterval(function(){ var h=dataHash(); if(h!==_prevHash){ _prevHash=h; renderAll(); } }, 350);
			  var rt;
			  window.addEventListener('resize', function(){ clearTimeout(rt); rt=setTimeout(renderAll,120); });
			  function tryRender(a){ a=a||0; if(renderAll()) return; if(a<25) setTimeout(function(){ tryRender(a+1); }, 100); }
			  if(document.readyState==='loading'){ document.addEventListener('DOMContentLoaded', function(){ tryRender(); }); } else { tryRender(); }
			  window.addEventListener('load', function(){ tryRender(); });
			})();" & "</script>"
		displayFolder: HTML Comercial
		lineageTag: abc3b921-6631-4289-9415-5024451f4195

	/// Faturamento medio por cliente ativo no periodo.
	measure 'Ticket Médio por Cliente' = DIVIDE([Faturamento Total], [Total Clientes Ativos], 0)
		formatString: "R$ "#,##0.00
		lineageTag: 9515dcc7-eebd-4c7f-9649-acc3d1352304

	/// Variacao percentual MoM do ticket medio por cliente.
	measure 'MoM Ticket Médio por Cliente %' =
			VAR Atual = [Ticket Médio por Cliente]
			VAR Anterior =
			    CALCULATE([Ticket Médio por Cliente], DATEADD(D_Calendario[Data], -1, MONTH))
			VAR Variacao =
			    DIVIDE(Atual - Anterior, Anterior, 0)
			RETURN
			    FORMAT(Variacao, "+0.0%;-0.0%;0.0%")
		lineageTag: 1ad5dd17-6aa4-4973-8611-44a1fa805559

	/// Quantidade media de pedidos por cliente ativo no periodo.
	measure 'Pedidos por Cliente' = DIVIDE([Total de Pedidos], [Total Clientes Ativos], 0)
		formatString: 0.00
		lineageTag: 500c9506-6196-482d-8bd2-010a3ef15812

	/// Variacao percentual MoM de pedidos por cliente.
	measure 'MoM Pedidos por Cliente %' =
			VAR Atual = [Pedidos por Cliente]
			VAR Anterior =
			    CALCULATE([Pedidos por Cliente], DATEADD(D_Calendario[Data], -1, MONTH))
			VAR Variacao =
			    DIVIDE(Atual - Anterior, Anterior, 0)
			RETURN
			    FORMAT(Variacao, "+0.0%;-0.0%;0.0%")
		lineageTag: ba36dd68-bafe-4fec-b5b1-8751ffad1b0d

	/// Recorrência Rolling 2M: % dos clientes ativos no período filtrado que também compraram em algum dos 2 meses cheios imediatamente anteriores ao início do período.
	measure 'Taxa de Recorrência %' =
			VAR _mesInicio = DATE(YEAR(MIN(D_Calendario[Data])), MONTH(MIN(D_Calendario[Data])), 1)
			VAR _dataMaxJanela = _mesInicio - 1
			VAR _dataMinJanela = EDATE(_mesInicio, -2)
			VAR _ativosNoPeriodo =
			    CALCULATETABLE(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]),
			        DCVVQ_VENDAGERALTELEVENDAS[VLRVENDA] > 0
			    )
			VAR _ativosNaJanelaAnterior =
			    CALCULATETABLE(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]),
			        DCVVQ_VENDAGERALTELEVENDAS[VLRVENDA] > 0,
			        FILTER(
			            ALL(D_Calendario),
			            D_Calendario[Data] >= _dataMinJanela &&
			            D_Calendario[Data] <= _dataMaxJanela
			        )
			    )
			VAR _recorrentes = INTERSECT(_ativosNoPeriodo, _ativosNaJanelaAnterior)
			VAR _qtdRecorrentes = COUNTROWS(_recorrentes)
			VAR _qtdAtivos = COUNTROWS(_ativosNoPeriodo)
			RETURN
			    DIVIDE(_qtdRecorrentes, _qtdAtivos, 0) * 100
		formatString: 0.00
		lineageTag: 9d75a1cb-5d89-4d7f-a1cf-f6fa9e331612

	/// Variacao percentual MoM da taxa de recorrencia.
	measure 'MoM Taxa de Recorrência %' =
			VAR Atual = [Taxa de Recorrência %]
			VAR Anterior =
			    CALCULATE([Taxa de Recorrência %], DATEADD(D_Calendario[Data], -1, MONTH))
			VAR Variacao =
			    DIVIDE(Atual - Anterior, Anterior, 0)
			RETURN
			    FORMAT(Variacao, "+0.0%;-0.0%;0.0%")
		lineageTag: 59f72fc8-ed75-4cb5-b946-5296b9cfd1d9

	/// JSON com dados dos 4 KPIs do HTML Clientes. v2 - formato 0.00 (estavel) ao inves de 0.## (gerava '0.' invalido quando valor era zero).
	measure '_JSON KPIs Clientes' =
			"{""clientes"":"        & COALESCE([Total Clientes Ativos], 0) &
			",""momClientes"":"""   & COALESCE([MoM Clientes Ativos %], "--") & """" &
			",""ticketMed"":"       & SUBSTITUTE(FORMAT(COALESCE([Ticket Médio por Cliente], 0), "0.00"), ",", ".") &
			",""momTicket"":"""     & COALESCE([MoM Ticket Médio por Cliente %], "--") & """" &
			",""pedPorCli"":"       & SUBSTITUTE(FORMAT(COALESCE([Pedidos por Cliente], 0), "0.00"), ",", ".") &
			",""momPed"":"""        & COALESCE([MoM Pedidos por Cliente %], "--") & """" &
			",""recorrencia"":"     & SUBSTITUTE(FORMAT(COALESCE([Taxa de Recorrência %], 0), "0.00"), ",", ".") &
			",""momRec"":"""        & COALESCE([MoM Taxa de Recorrência %], "--") & """" &
			"}"
		displayFolder: HTML Clientes
		lineageTag: e99cfe32-b65f-4e10-a898-ee838618d8da

	/// Distribuicao por ATIVIDADE em duas visoes (venda e devolucao). Cada item: nome, val (R$), peso, clientes ativos, pedidos.
	measure '_JSON Distribuicao Atividade Clientes' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE]) && DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_peso",     [Peso Total Vendido],
			        "_clientes", [Total Clientes Ativos],
			        "_pedidos",  [Total de Pedidos],
			        "_devRS",    [Total Devoluções (R$)],
			        "_devPeso",  [Peso Total Devolvido]
			    )
			VAR _venda = FILTER(_com, [_fat] > 0)
			VAR _dev   = FILTER(_com, [_devRS] > 0)
			VAR _arrVenda =
			    "[" & CONCATENATEX(
			        _venda,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE], """""", ""), "\", "") &
			        """,""val"":"      & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""peso"":"       & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""clientes"":"   & COALESCE([_clientes], 0) &
			        ",""pedidos"":"    & COALESCE([_pedidos], 0) &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrDev =
			    "[" & CONCATENATEX(
			        _dev,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE], """""", ""), "\", "") &
			        """,""val"":"      & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""peso"":"       & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""clientes"":"   & COALESCE([_clientes], 0) &
			        ",""pedidos"":"    & COALESCE([_pedidos], 0) &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			RETURN
			"{""venda"":" & _arrVenda & ",""devolucao"":" & _arrDev & "}"
		displayFolder: HTML Clientes
		lineageTag: 467adb57-695a-408a-9051-0f0148fe1570

	/// Distribuicao por PORTE em duas visoes (venda e devolucao).
	measure '_JSON Distribuicao Porte Clientes' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[PORTE]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[PORTE]) && DCVVQ_VENDAGERALTELEVENDAS[PORTE] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_peso",     [Peso Total Vendido],
			        "_clientes", [Total Clientes Ativos],
			        "_pedidos",  [Total de Pedidos],
			        "_devRS",    [Total Devoluções (R$)],
			        "_devPeso",  [Peso Total Devolvido]
			    )
			VAR _venda = FILTER(_com, [_fat] > 0)
			VAR _dev   = FILTER(_com, [_devRS] > 0)
			VAR _arrVenda =
			    "[" & CONCATENATEX(
			        _venda,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PORTE], """""", ""), "\", "") &
			        """,""val"":"      & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""peso"":"       & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""clientes"":"   & COALESCE([_clientes], 0) &
			        ",""pedidos"":"    & COALESCE([_pedidos], 0) &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrDev =
			    "[" & CONCATENATEX(
			        _dev,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PORTE], """""", ""), "\", "") &
			        """,""val"":"      & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""peso"":"       & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""clientes"":"   & COALESCE([_clientes], 0) &
			        ",""pedidos"":"    & COALESCE([_pedidos], 0) &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			RETURN
			"{""venda"":" & _arrVenda & ",""devolucao"":" & _arrDev & "}"
		displayFolder: HTML Clientes
		lineageTag: 5de1ce79-b1c7-4622-bf95-0e94fc925be6

	/// Ranking por CIDADE em duas visoes (venda e devolucao). Top 50 cada para limitar tamanho - JS aplica slice(0,15).
	measure '_JSON Ranking Cidade Clientes' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[CIDADE]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[CIDADE]) && DCVVQ_VENDAGERALTELEVENDAS[CIDADE] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_clientes", [Total Clientes Ativos],
			        "_pedidos",  [Total de Pedidos],
			        "_devRS",    [Total Devoluções (R$)]
			    )
			VAR _venda = TOPN(50, FILTER(_com, [_fat] > 0), [_fat], DESC)
			VAR _dev   = TOPN(50, FILTER(_com, [_devRS] > 0), [_devRS], DESC)
			VAR _arrVenda =
			    "[" & CONCATENATEX(
			        _venda,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CIDADE], """""", ""), "\", "") &
			        """,""val"":"      & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""clientes"":"   & COALESCE([_clientes], 0) &
			        ",""pedidos"":"    & COALESCE([_pedidos], 0) &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrDev =
			    "[" & CONCATENATEX(
			        _dev,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CIDADE], """""", ""), "\", "") &
			        """,""val"":"      & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""clientes"":"   & COALESCE([_clientes], 0) &
			        ",""pedidos"":"    & COALESCE([_pedidos], 0) &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			RETURN
			"{""venda"":" & _arrVenda & ",""devolucao"":" & _arrDev & "}"
		displayFolder: HTML Clientes
		lineageTag: 6029aab0-e1cd-44a9-aab4-2c3c2ed06e57

	/// Ranking por UF em duas visoes (venda e devolucao). Mostra todas as 4 UFs.
	measure '_JSON Ranking UF Clientes' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[UF]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[UF]) && DCVVQ_VENDAGERALTELEVENDAS[UF] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_clientes", [Total Clientes Ativos],
			        "_pedidos",  [Total de Pedidos],
			        "_devRS",    [Total Devoluções (R$)]
			    )
			VAR _venda = FILTER(_com, [_fat] > 0)
			VAR _dev   = FILTER(_com, [_devRS] > 0)
			VAR _arrVenda =
			    "[" & CONCATENATEX(
			        _venda,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[UF], """""", ""), "\", "") &
			        """,""val"":"      & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""clientes"":"   & COALESCE([_clientes], 0) &
			        ",""pedidos"":"    & COALESCE([_pedidos], 0) &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrDev =
			    "[" & CONCATENATEX(
			        _dev,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[UF], """""", ""), "\", "") &
			        """,""val"":"      & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""clientes"":"   & COALESCE([_clientes], 0) &
			        ",""pedidos"":"    & COALESCE([_pedidos], 0) &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			RETURN
			"{""venda"":" & _arrVenda & ",""devolucao"":" & _arrDev & "}"
		displayFolder: HTML Clientes
		lineageTag: 9aee0e1b-5ba6-4007-9a20-79d01c47d903

	/// Tabela detalhada por CLIENTE (top 200 por faturamento) - cliente, atividade, porte, cidade, fat, pedidos, devRS, taxa dev.
	measure '_JSON Tabela Cliente Clientes' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE]) && DCVVQ_VENDAGERALTELEVENDAS[CLIENTE] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_atividade", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE])),
			        "_porte",     CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[PORTE])),
			        "_cidade",    CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[CIDADE])),
			        "_fat",       [Faturamento Total],
			        "_pedidos",   [Total de Pedidos],
			        "_devRS",     [Total Devoluções (R$)]
			    )
			VAR _top =
			    TOPN(200, FILTER(_com, [_fat] > 0), [_fat], DESC)
			RETURN
			"[" & CONCATENATEX(
			    _top,
			    "{""cliente"":"""   & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE], """""", ""), "\", "") &
			    """,""atividade"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_atividade], "-"), """""", ""), "\", "") &
			    """,""porte"":"""     & SUBSTITUTE(SUBSTITUTE(COALESCE([_porte], "-"), """""", ""), "\", "") &
			    """,""cidade"":"""    & SUBSTITUTE(SUBSTITUTE(COALESCE([_cidade], "-"), """""", ""), "\", "") &
			    """,""fat"":"        & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""pedidos"":"      & COALESCE([_pedidos], 0) &
			    ",""devRS"":"        & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""taxaDev"":"      & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_devRS], 0), COALESCE([_fat], 0) + COALESCE([_devRS], 0), 0) * 100, "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Clientes
		lineageTag: 34f370c0-5254-44c3-a648-6b7032f7b453

	/// Tabela detalhada por ATIVIDADE - nome, fat, peso, pedidos, clientes, devRS, taxa dev.
	measure '_JSON Tabela Atividade Clientes' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE]) && DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_peso",     [Peso Total Vendido],
			        "_pedidos",  [Total de Pedidos],
			        "_clientes", [Total Clientes Ativos],
			        "_devRS",    [Total Devoluções (R$)]
			    )
			VAR _f = FILTER(_com, [_fat] > 0 || [_devRS] > 0)
			RETURN
			"[" & CONCATENATEX(
			    _f,
			    "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE], """""", ""), "\", "") &
			    """,""fat"":"        & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""peso"":"         & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""pedidos"":"      & COALESCE([_pedidos], 0) &
			    ",""clientes"":"     & COALESCE([_clientes], 0) &
			    ",""devRS"":"        & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""taxaDev"":"      & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_devRS], 0), COALESCE([_fat], 0) + COALESCE([_devRS], 0), 0) * 100, "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Clientes
		lineageTag: d969c2e0-b6d6-4279-a8f2-c24cba6db45b

	/// Tabela detalhada por PORTE - nome, clientes, fat, ticketMedio, pedidos, devRS, taxa dev.
	measure '_JSON Tabela Porte Clientes' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[PORTE]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[PORTE]) && DCVVQ_VENDAGERALTELEVENDAS[PORTE] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_fat",      [Faturamento Total],
			        "_clientes", [Total Clientes Ativos],
			        "_pedidos",  [Total de Pedidos],
			        "_devRS",    [Total Devoluções (R$)]
			    )
			VAR _f = FILTER(_com, [_fat] > 0 || [_devRS] > 0)
			RETURN
			"[" & CONCATENATEX(
			    _f,
			    "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PORTE], """""", ""), "\", "") &
			    """,""clientes"":"   & COALESCE([_clientes], 0) &
			    ",""fat"":"          & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""ticketMedio"":"  & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_fat], 0), COALESCE([_clientes], 0), 0), "0.00"), ",", ".") &
			    ",""pedidos"":"      & COALESCE([_pedidos], 0) &
			    ",""devRS"":"        & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""taxaDev"":"      & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_devRS], 0), COALESCE([_fat], 0) + COALESCE([_devRS], 0), 0) * 100, "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Clientes
		lineageTag: 36ecc8e1-d26b-4663-8e88-aaf4d341535c

	/// Tabela detalhada por CIDADE (top 50 por faturamento) - nome, UF, fat, clientes, pedidos, devRS, taxa dev.
	measure '_JSON Tabela Cidade Clientes' =
			VAR _todos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[CIDADE]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[CIDADE]) && DCVVQ_VENDAGERALTELEVENDAS[CIDADE] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _todos,
			        "_uf",       CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[UF])),
			        "_fat",      [Faturamento Total],
			        "_clientes", [Total Clientes Ativos],
			        "_pedidos",  [Total de Pedidos],
			        "_devRS",    [Total Devoluções (R$)]
			    )
			VAR _top =
			    TOPN(50, FILTER(_com, [_fat] > 0 || [_devRS] > 0), [_fat], DESC)
			RETURN
			"[" & CONCATENATEX(
			    _top,
			    "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CIDADE], """""", ""), "\", "") &
			    """,""uf"":"""        & SUBSTITUTE(SUBSTITUTE(COALESCE([_uf], "-"), """""", ""), "\", "") &
			    """,""fat"":"         & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""clientes"":"     & COALESCE([_clientes], 0) &
			    ",""pedidos"":"      & COALESCE([_pedidos], 0) &
			    ",""devRS"":"        & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""taxaDev"":"      & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_devRS], 0), COALESCE([_fat], 0) + COALESCE([_devRS], 0), 0) * 100, "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Clientes
		lineageTag: 1c8af245-6c79-4aba-b9b1-50dcd576a369

	/// JS Clientes v4 - card de Recorrencia agora mostra descricao curta da metrica ao inves do MoM.
	measure '_JS Clientes' =
			"<script>" & "(function () {
			  'use strict';
			  function rJ(id) { var e = document.getElementById(id); try { return JSON.parse((e && e.textContent) || 'null'); } catch (ex) { return null; } }
			  function esc(v) { return String(v == null ? '' : v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
			  function escT(v) { return esc(v).replace(/'/g,'&#39;'); }
			  function fN(v) { return (Number(v) || 0).toLocaleString('pt-BR'); }
			  function fA(v) { v = Number(v) || 0; if (Math.abs(v) >= 1e6) return (v/1e6).toFixed(1).replace('.',',') + ' M'; if (Math.abs(v) >= 1e3) return (v/1e3).toFixed(1).replace('.',',') + ' mil'; return fN(v); }
			  function fM(v) { v = Number(v) || 0; return 'R$ ' + v.toLocaleString('pt-BR', {minimumFractionDigits:2, maximumFractionDigits:2}); }
			  function fMK(v) { v = Number(v) || 0; if (Math.abs(v) >= 1e6) return 'R$ ' + (v/1e6).toFixed(2).replace('.',',') + ' M'; if (Math.abs(v) >= 1e3) return 'R$ ' + (v/1e3).toFixed(1).replace('.',',') + ' mil'; return fM(v); }
			  function fPct(v) { return (Number(v)||0).toFixed(2).replace('.',',') + '%'; }
			  function fDec(v) { return (Number(v)||0).toFixed(2).replace('.',','); }
			  function momCls(s) { if (!s || s === '--') return 'neu'; return s.indexOf('+') === 0 ? 'up' : (s.indexOf('-') === 0 ? 'down' : 'neu'); }
			  function tagColor(str) {
			    if (!str) return {bg:'rgba(139,139,139,.12)',fg:'#5A5A5A'};
			    var h=0; for (var i=0;i<str.length;i++) h = ((h<<5)-h) + str.charCodeAt(i);
			    var palette = [
			      {bg:'rgba(184,147,90,.15)',fg:'#8A6740'},
			      {bg:'rgba(78,125,98,.15)',fg:'#3D6049'},
			      {bg:'rgba(74,110,138,.15)',fg:'#3A5872'},
			      {bg:'rgba(192,124,58,.15)',fg:'#995F2C'},
			      {bg:'rgba(58,36,16,.12)',fg:'#3A2410'},
			      {bg:'rgba(90,90,90,.15)',fg:'#5A5A5A'}
			    ];
			    return palette[Math.abs(h) % palette.length];
			  }
			  var ttEl = document.getElementById('tt');
			  window.tip = function(e,h){ if (!ttEl) return; ttEl.innerHTML = h; ttEl.classList.add('on'); ttEl.style.left = (e.clientX+14)+'px'; ttEl.style.top = (e.clientY-36)+'px'; };
			  window.tipOff = function(){ ttEl && ttEl.classList.remove('on'); };
			  var kpiIcons = {
			    users: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><path d='M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2'/><circle cx='9' cy='7' r='4'/><path d='M23 21v-2a4 4 0 0 0-3-3.87'/><path d='M16 3.13a4 4 0 0 1 0 7.75'/></svg>"",
			    target: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><circle cx='12' cy='12' r='10'/><circle cx='12' cy='12' r='6'/><circle cx='12' cy='12' r='2'/></svg>"",
			    bag: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><path d='M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z'/><line x1='3' y1='6' x2='21' y2='6'/><path d='M16 10a4 4 0 0 1-8 0'/></svg>"",
			    refresh: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2' stroke-linecap='round' stroke-linejoin='round'><polyline points='23 4 23 10 17 10'/><polyline points='1 20 1 14 7 14'/><path d='M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15'/></svg>""
			  };
			  function buildKPIs(){
			    var K=rJ('jKpi')||{}; var el=document.getElementById('kpiGrid'); if(!el) return;
			    var cards=[
			      {icon:'users',  label:'Clientes Ativos',          val:fN(K.clientes||0),     sub:'MoM = <span class=\''+momCls(K.momClientes)+'\'>'+(K.momClientes||'-')+'</span>'},
			      {icon:'target', label:'Ticket Médio / Cliente',   val:fMK(K.ticketMed||0),   sub:'MoM = <span class=\''+momCls(K.momTicket)+'\'>'+(K.momTicket||'-')+'</span>'},
			      {icon:'bag',    label:'Pedidos / Cliente',        val:fDec(K.pedPorCli||0),  sub:'MoM = <span class=\''+momCls(K.momPed)+'\'>'+(K.momPed||'-')+'</span>'},
			      {icon:'refresh',label:'Taxa de Recorrência',      val:fPct(K.recorrencia||0),sub:'Compraram nos 2 meses anteriores'}
			    ];
			    el.innerHTML=cards.map(function(c){ return ""<div class='kpi'><div class='kpi-top'><span class='kpi-label'>""+c.label+""</span><div class='kpi-icon'>""+kpiIcons[c.icon]+""</div></div><div class='kpi-val'>""+c.val+""</div><div class='kpi-sub'>""+c.sub+""</div></div>""; }).join('');
			  }
			  var _modoAt='venda';
			  window.setModoAt=function(m){ _modoAt=m; document.querySelectorAll('#atvModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderAtividade(); };
			  function renderAtividade(){
			    var el=document.getElementById('atvList'); if(!el) return;
			    var data=rJ('jAt')||{venda:[],devolucao:[]};
			    var arr=data[_modoAt]||[];
			    if(!arr.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Math.max.apply(null,arr.map(function(d){ return Number(d.val)||0; }).concat([1]));
			    var lbl=_modoAt==='venda'?'Faturamento':'Devolução';
			    el.innerHTML=arr.map(function(d){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      var tt='<b>'+escT(d.nome)+'</b><br>'+lbl+': '+fMK(v)+'<br>Peso: '+fA(Number(d.peso)||0)+' kg<br>Clientes: '+fN(Number(d.clientes)||0)+'<br>Pedidos: '+fN(Number(d.pedidos)||0);
			      return ""<div class='bar-row' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'><div class='bar-head'><div class='bar-name'>""+esc(d.nome)+""</div><div class='bar-val'>""+fMK(v)+""</div></div><div class='bar-track'><div class='bar-fill' data-w='""+w+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.bar-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  var _modoPt='venda';
			  window.setModoPt=function(m){ _modoPt=m; document.querySelectorAll('#prtModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderPorte(); };
			  function renderPorte(){
			    var el=document.getElementById('prtList'); if(!el) return;
			    var data=rJ('jPt')||{venda:[],devolucao:[]};
			    var arr=data[_modoPt]||[];
			    if(!arr.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Math.max.apply(null,arr.map(function(d){ return Number(d.val)||0; }).concat([1]));
			    var lbl=_modoPt==='venda'?'Faturamento':'Devolução';
			    el.innerHTML=arr.map(function(d){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      var tt='<b>'+escT(d.nome)+'</b><br>'+lbl+': '+fMK(v)+'<br>Peso: '+fA(Number(d.peso)||0)+' kg<br>Clientes: '+fN(Number(d.clientes)||0)+'<br>Pedidos: '+fN(Number(d.pedidos)||0);
			      return ""<div class='bar-row' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'><div class='bar-head'><div class='bar-name'>""+esc(d.nome)+""</div><div class='bar-val'>""+fMK(v)+""</div></div><div class='bar-track'><div class='bar-fill' data-w='""+w+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.bar-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  var _modoGh='cidade', _modoGr='venda';
			  window.setModoGh=function(m){ _modoGh=m; document.querySelectorAll('#geoHierToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.h===m); }); renderGeografica(); };
			  window.setModoGr=function(m){ _modoGr=m; document.querySelectorAll('#geoModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderGeografica(); };
			  function renderGeografica(){
			    var el=document.getElementById('geoChart'); if(!el) return;
			    var sources={cidade:'jGcd', uf:'jGuf'};
			    var data=rJ(sources[_modoGh])||{venda:[],devolucao:[]};
			    var arr=(data[_modoGr]||[]).slice(0,15);
			    if(!arr.length){ el.innerHTML=""<div style='padding:30px;color:#8B8B8B;text-align:center'>Sem dados</div>""; return; }
			    var H=500;
			    var P={t:38, r:24, b:70, l:68};
			    var n=arr.length;
			    var containerW = el.clientWidth || 900;
			    var availW = containerW - P.l - P.r;
			    var minBarW = 30;
			    var maxBarW = 56;
			    var defaultGap = 18;
			    var maxGap = 40;
			    var idealBarW = (availW - (n-1)*defaultGap) / Math.max(n,1);
			    var barW, gap, contentW, startX;
			    if (idealBarW >= maxBarW) {
			      barW = maxBarW;
			      var remaining = availW - n*barW;
			      gap = n > 1 ? Math.min(maxGap, remaining / (n-1)) : 0;
			      var totalBarsW = n*barW + (n-1)*gap;
			      startX = P.l + Math.max(0, (availW - totalBarsW) / 2);
			      contentW = containerW;
			    } else if (idealBarW >= minBarW) {
			      barW = idealBarW;
			      gap = defaultGap;
			      startX = P.l;
			      contentW = containerW;
			    } else {
			      barW = minBarW;
			      gap = defaultGap;
			      startX = P.l;
			      contentW = n*barW + (n-1)*gap + P.l + P.r;
			    }
			    var W = Math.max(contentW, containerW);
			    var mx = Math.max.apply(null, arr.map(function(d){ return Number(d.val)||0; }).concat([1])) * 1.10;
			    var lblFn = _modoGr==='venda' ? 'Faturamento' : 'Devolução';
			    var uid = 'g' + Math.floor(Math.random()*99999);
			    var maxWordChars = barW < 40 ? 10 : 14;
			    var svg = ""<defs><linearGradient id='bg""+uid+""' x1='0%' y1='0%' x2='0%' y2='100%'><stop offset='0%' stop-color='#B8935A' stop-opacity='1'/><stop offset='100%' stop-color='#1A1A1A' stop-opacity='1'/></linearGradient></defs>"";
			    for (var i=0; i<=4; i++){
			      var y = P.t + (H - P.t - P.b) * i / 4;
			      var v = mx * (1 - i/4);
			      svg += ""<line x1='""+P.l+""' x2='""+(W-P.r)+""' y1='""+y.toFixed(1)+""' y2='""+y.toFixed(1)+""' stroke='rgba(0,0,0,.06)' stroke-dasharray='3,4'/>"";
			      if (i<4) svg += ""<text x='""+(P.l-6)+""' y='""+(y+4).toFixed(1)+""' text-anchor='end' fill='#8B8B8B' style='font-size:12.5px;font-family:Segoe UI,system-ui;font-weight:500'>""+fA(v)+""</text>"";
			    }
			    arr.forEach(function(d, i){
			      var v = Number(d.val)||0;
			      var bh = Math.max(2, (v/mx) * (H - P.t - P.b));
			      var bx = startX + i*(barW+gap);
			      var by = H - P.b - bh;
			      var labelX = bx + barW/2;
			      var tt = '<b>'+escT(d.nome)+'</b><br>'+lblFn+': '+fMK(v)+'<br>Clientes: '+fN(Number(d.clientes)||0)+'<br>Pedidos: '+fN(Number(d.pedidos)||0);
			      svg += ""<rect class='vbar' x='""+bx.toFixed(1)+""' y='""+by.toFixed(1)+""' width='""+barW.toFixed(1)+""' height='""+bh.toFixed(1)+""' rx='3' fill='url(#bg""+uid+"")' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'/>"";
			      svg += ""<text x='""+labelX.toFixed(1)+""' y='""+(by-8).toFixed(1)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:11.5px;font-weight:700;font-variant-numeric:tabular-nums;font-family:Segoe UI,system-ui;pointer-events:none'>R$ ""+fA(v)+""</text>"";
			      var words = d.nome.split(/\s+/);
			      var displayWords = words.slice(0, 4).map(function(w){ return w.length > maxWordChars ? w.slice(0, maxWordChars-2) + '..' : w; });
			      var nameY = H - P.b + 16;
			      displayWords.forEach(function(w, j){
			        svg += ""<text x='""+labelX.toFixed(1)+""' y='""+(nameY + j*14)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:11.5px;font-weight:500;font-family:Segoe UI,system-ui'>""+esc(w)+""</text>"";
			      });
			    });
			    el.innerHTML = ""<svg width='""+W+""' height='""+H+""' xmlns='http://www.w3.org/2000/svg'>""+svg+""</svg>"";
			  }
			  var _aba='cliente';
			  window.setAba=function(aba){ _aba=aba; document.querySelectorAll('#abasTabs .tab').forEach(function(t){ t.classList.toggle('on', t.dataset.aba===aba); }); renderTabela(); };
			  function renderTabela(){
			    var el=document.getElementById('tabelaBox'); if(!el) return;
			    var data, cols;
			    if(_aba==='cliente'){ data=rJ('jTcl')||[]; cols=[{k:'cliente',t:'Cliente',cls:'name'},{k:'atividade',t:'Atividade',cls:'tag'},{k:'porte',t:'Porte',cls:'tag'},{k:'cidade',t:'Cidade',cls:'name'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'devRS',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else if(_aba==='atividade'){ data=rJ('jTat')||[]; cols=[{k:'nome',t:'Atividade',cls:'name'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'peso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'clientes',t:'Clientes',cls:'num',fmt:fN},{k:'devRS',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else if(_aba==='porte'){ data=rJ('jTpt')||[]; cols=[{k:'nome',t:'Porte',cls:'name'},{k:'clientes',t:'Clientes',cls:'num',fmt:fN},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'ticketMedio',t:'Ticket Médio',cls:'num',fmt:fMK},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'devRS',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else { data=rJ('jTcd')||[]; cols=[{k:'nome',t:'Cidade',cls:'name'},{k:'uf',t:'UF',cls:'tag'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'clientes',t:'Clientes',cls:'num',fmt:fN},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'devRS',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    if(!data.length){ el.innerHTML=""<div style='padding:20px;color:#8B8B8B;text-align:center'>Sem dados</div>""; return; }
			    var maxNum={};
			    cols.forEach(function(c){ if(c.cls==='num' && c.bar){ maxNum[c.k]=Math.max.apply(null, data.map(function(d){return Number(d[c.k])||0;}).concat([1])); } });
			    var head=""<thead><tr>"" + cols.map(function(c){ return ""<th class='th-""+c.cls+""'>""+c.t+""</th>""; }).join('') + ""</tr></thead>"";
			    var body=""<tbody>"" + data.map(function(d){
			      return ""<tr>"" + cols.map(function(c){
			        var v=d[c.k]; var text=c.fmt?c.fmt(v):esc(v);
			        if(c.cls==='num' && c.bar){
			          var n=Number(v)||0; var pct=Math.max(0,(n/maxNum[c.k])*100);
			          return ""<td class='td-num'><div class='cell-val'>""+text+""</div><div class='cell-bar'><div class='cell-fill' style='width:""+pct.toFixed(1)+""%'></div></div></td>"";
			        }
			        if(c.cls==='tag'){
			          var clr=tagColor(v);
			          return ""<td class='td-tag'><span class='tag-badge' style='background:""+clr.bg+"";color:""+clr.fg+""'>""+esc(v||'-')+""</span></td>"";
			        }
			        return ""<td class='td-""+c.cls+""'>""+text+""</td>"";
			      }).join('') + ""</tr>"";
			    }).join('') + ""</tbody>"";
			    el.innerHTML=""<table class='tbl'>"" + head + body + ""</table>"";
			  }
			  function renderAll(){
			    if(!document.getElementById('kpiGrid')) return false;
			    try { buildKPIs(); renderAtividade(); renderPorte(); renderGeografica(); renderTabela(); return true; }
			    catch(e){ console.error(e); return false; }
			  }
			  var _prevHash='';
			  function dataHash(){
			    return ['jKpi','jAt','jPt','jGcd','jGuf','jTcl','jTat','jTpt','jTcd'].map(function(id){
			      var e=document.getElementById(id); if(!e) return '';
			      return e.textContent.length+'|'+e.textContent.slice(0,20);
			    }).join('~');
			  }
			  setInterval(function(){ var h=dataHash(); if(h!==_prevHash){ _prevHash=h; renderAll(); } }, 350);
			  var rt;
			  window.addEventListener('resize', function(){ clearTimeout(rt); rt=setTimeout(renderAll,120); });
			  function tryRender(a){ a=a||0; if(renderAll()) return; if(a<25) setTimeout(function(){ tryRender(a+1); }, 100); }
			  if(document.readyState==='loading'){ document.addEventListener('DOMContentLoaded', function(){ tryRender(); }); } else { tryRender(); }
			  window.addEventListener('load', function(){ tryRender(); });
			})();" & "</script>"
		displayFolder: HTML Clientes
		lineageTag: f89f5d7e-835d-4b57-8b47-fe01bf83fa73

	/// Dashboard HTML Content da pagina Clientes - layout completo + JSONs + chama _JS Clientes.
	measure 'HTML Clientes' =
			"<style>:root {
			  --bg:    #EEEAE2;
			  --surf:  #FFFFFF;
			  --surf2: #F7F3EB;
			  --bd:    rgba(26,26,26,.07);
			  --bd2:   rgba(26,26,26,.15);
			  --t1:    #1A1A1A;
			  --t2:    #5A5A5A;
			  --t3:    #8B8B8B;
			  --gold:  #B8935A;
			  --goldS: #EAD9BE;
			  --dark:  #1E1E1E;
			  --grn:   #4E7D62;
			  --org:   #C07C3A;
			  --blu:   #4A6E8A;
			  --red:   #A04848;
			  --sh1:   0 1px 3px rgba(0,0,0,.06);
			  --sh2:   0 2px 10px rgba(0,0,0,.1);
			  --r:     10px;
			  --ease:  cubic-bezier(.4,0,.2,1);
			}
			* { box-sizing: border-box; margin: 0; padding: 0; }
			html, body {
			  background: var(--bg);
			  font-family: 'Segoe UI', system-ui, sans-serif;
			  font-size: 14px; color: var(--t1);
			  -webkit-font-smoothing: antialiased;
			  min-height: 100vh;
			}
			.dash { padding: 14px 16px; display: flex; flex-direction: column; gap: 12px; }
			.hdr { display: flex; align-items: center; justify-content: space-between; padding: 0 2px; }
			.hdr-title { font-size: 25px; font-weight: 700; letter-spacing: -.5px; }
			.hdr-sub { font-size: 13px; color: var(--t3); margin-left: 8px; }
			.kpi-row { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; }
			.kpi { background: var(--surf); border-radius: var(--r); padding: 14px 16px; box-shadow: var(--sh1); border: 1px solid var(--bd); }
			.kpi-top { display: flex; align-items: flex-start; justify-content: space-between; gap: 8px; }
			.kpi-label { font-size: 12.5px; color: var(--t2); font-weight: 500; }
			.kpi-icon { width: 30px; height: 30px; border-radius: 8px; background: linear-gradient(135deg, var(--goldS), #F0E4CC); display: flex; align-items: center; justify-content: center; color: var(--gold); flex-shrink: 0; }
			.kpi-icon svg { width: 14px; height: 14px; }
			.kpi-val { font-size: 32px; font-weight: 700; letter-spacing: -.6px; line-height: 1.1; font-variant-numeric: tabular-nums; margin-top: 6px; }
			.kpi-sub { font-size: 12.5px; color: var(--t3); margin-top: 4px; }
			.kpi-sub .up { color: var(--grn); font-weight: 600; }
			.kpi-sub .down { color: var(--red); font-weight: 600; }
			.kpi-sub .neu { color: var(--gold); font-weight: 600; }
			.card { background: var(--surf); border-radius: var(--r); padding: 12px 14px; box-shadow: var(--sh1); border: 1px solid var(--bd); }
			.card-head { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 10px; gap: 10px; flex-wrap: wrap; }
			.card-title { font-size: 16px; font-weight: 600; letter-spacing: -.2px; }
			.card-sub { font-size: 12px; color: var(--t3); margin-top: 1px; }
			.toggle-group { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
			.mini-toggle, .tri-toggle { display: flex; background: var(--surf2); border: 1px solid var(--bd2); border-radius: 100px; overflow: hidden; }
			.mini-toggle button, .tri-toggle button { padding: 5px 13px; font-size: 12px; font-weight: 600; border: none; background: transparent; color: var(--t2); cursor: pointer; font-family: inherit; transition: all .15s; }
			.mini-toggle button.on, .tri-toggle button.on { background: var(--dark); color: #fff; border-radius: 100px; }
			.two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; align-items: stretch; }
			.two-col > .card { display: flex; flex-direction: column; }
			.bars-list-scroll { display: flex; flex-direction: column; gap: 9px; max-height: 380px; overflow-y: auto; padding-right: 6px; }
			.bars-list-scroll::-webkit-scrollbar { width: 6px; }
			.bars-list-scroll::-webkit-scrollbar-track { background: rgba(26,26,26,.04); border-radius: 100px; }
			.bars-list-scroll::-webkit-scrollbar-thumb { background: var(--goldS); border-radius: 100px; }
			.bars-list-scroll::-webkit-scrollbar-thumb:hover { background: var(--gold); }
			.bar-row { cursor: default; }
			.bar-head { display: flex; justify-content: space-between; gap: 8px; margin-bottom: 4px; }
			.bar-name { font-size: 13px; color: #1A1A1A; font-weight: 500; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; flex: 1; min-width: 0; }
			.bar-val { font-size: 13px; font-weight: 700; font-variant-numeric: tabular-nums; color: var(--t1); }
			.bar-track { height: 6px; background: #EAD9BE; border-radius: 100px; overflow: hidden; }
			.bar-fill { height: 100%; border-radius: 100px; background: linear-gradient(90deg, #1A1A1A, var(--gold)); width: 0; transition: width .8s var(--ease); }
			.chart-vert-wrap { overflow-x: auto; overflow-y: hidden; padding-bottom: 4px; }
			.chart-vert-wrap::-webkit-scrollbar { height: 8px; }
			.chart-vert-wrap::-webkit-scrollbar-track { background: rgba(26,26,26,.04); border-radius: 100px; }
			.chart-vert-wrap::-webkit-scrollbar-thumb { background: var(--goldS); border-radius: 100px; }
			.chart-vert-wrap::-webkit-scrollbar-thumb:hover { background: var(--gold); }
			.chart-vert-wrap svg .vbar { transition: opacity .2s; cursor: pointer; }
			.chart-vert-wrap svg .vbar:hover { opacity: .80; }
			.tabs { display: flex; gap: 4px; background: var(--surf2); padding: 3px; border-radius: 100px; border: 1px solid var(--bd2); flex-wrap: wrap; }
			.tab { padding: 6px 15px; font-size: 12.5px; font-weight: 600; border: none; background: transparent; color: var(--t2); cursor: pointer; font-family: inherit; border-radius: 100px; transition: all .15s; }
			.tab.on { background: var(--dark); color: #fff; }
			.table-wrap { overflow-x: auto; max-height: 460px; overflow-y: auto; border-radius: 8px; }
			.tbl { width: 100%; border-collapse: collapse; font-size: 13px; }
			.tbl th { position: sticky; top: 0; background: var(--surf2); padding: 10px 12px; text-align: left; font-weight: 600; color: var(--t2); border-bottom: 1px solid var(--bd2); font-size: 12px; text-transform: uppercase; letter-spacing: .3px; z-index: 2; }
			.tbl th.th-num { text-align: right; }
			.tbl td { padding: 7px 10px; border-bottom: 1px solid var(--bd); vertical-align: middle; }
			.tbl tr:hover td { background: var(--surf2); }
			.tbl td.td-name { font-weight: 500; color: var(--t1); }
			.tbl td.td-tag { color: var(--t2); font-size: 12px; }
			.tbl td.td-num { text-align: right; font-variant-numeric: tabular-nums; font-weight: 600; color: var(--t1); min-width: 100px; }
			.cell-val { display: block; }
			.cell-bar { height: 3px; background: rgba(26,26,26,.04); border-radius: 100px; overflow: hidden; margin-top: 3px; }
			.cell-fill { height: 100%; background: linear-gradient(90deg, #1A1A1A, var(--gold)); border-radius: 100px; }
			.tag-badge { display: inline-block; padding: 3px 10px; border-radius: 100px; font-size: 11.5px; font-weight: 600; letter-spacing: .2px; white-space: nowrap; }
			.tt { position: fixed; background: #1E1E1E; color: #fff; padding: 7px 12px; border-radius: 7px; font-size: 12.5px; pointer-events: none; opacity: 0; transition: opacity .15s; z-index: 9999; white-space: nowrap; box-shadow: 0 4px 20px rgba(0,0,0,.2); }
			.tt.on { opacity: 1; }
			.tt b { color: #D4B687; }
			</style>" &
			"<div class='dash'>
			  <div class='hdr'>
			    <div>
			      <span class='hdr-title'>Clientes</span>
			      <span class='hdr-sub'>Carteira e comportamento de compra</span>
			    </div>
			  </div>
			  <div class='kpi-row' id='kpiGrid'></div>
			  <div class='two-col'>
			    <div class='card'>
			      <div class='card-head'>
			        <div>
			          <div class='card-title'>Distribuição por Atividade</div>
			          <div class='card-sub'>Todas as atividades - rolagem vertical</div>
			        </div>
			        <div class='mini-toggle' id='atvModoToggle'>
			          <button class='on' data-m='venda' onclick='setModoAt(&quot;venda&quot;)'>Venda</button>
			          <button data-m='devolucao' onclick='setModoAt(&quot;devolucao&quot;)'>Devolução</button>
			        </div>
			      </div>
			      <div class='bars-list-scroll' id='atvList'></div>
			    </div>
			    <div class='card'>
			      <div class='card-head'>
			        <div>
			          <div class='card-title'>Distribuição por Porte</div>
			          <div class='card-sub'>11 categorias de cliente - rolagem vertical</div>
			        </div>
			        <div class='mini-toggle' id='prtModoToggle'>
			          <button class='on' data-m='venda' onclick='setModoPt(&quot;venda&quot;)'>Venda</button>
			          <button data-m='devolucao' onclick='setModoPt(&quot;devolucao&quot;)'>Devolução</button>
			        </div>
			      </div>
			      <div class='bars-list-scroll' id='prtList'></div>
			    </div>
			  </div>
			  <div class='card'>
			    <div class='card-head'>
			      <div>
			        <div class='card-title'>Top 15 - Análise Geográfica</div>
			        <div class='card-sub'>Barras verticais com rótulo de dados - escolha o nível e o modo</div>
			      </div>
			      <div class='toggle-group'>
			        <div class='mini-toggle' id='geoHierToggle'>
			          <button class='on' data-h='cidade' onclick='setModoGh(&quot;cidade&quot;)'>Cidade</button>
			          <button data-h='uf' onclick='setModoGh(&quot;uf&quot;)'>UF</button>
			        </div>
			        <div class='mini-toggle' id='geoModoToggle'>
			          <button class='on' data-m='venda' onclick='setModoGr(&quot;venda&quot;)'>Venda</button>
			          <button data-m='devolucao' onclick='setModoGr(&quot;devolucao&quot;)'>Devolução</button>
			        </div>
			      </div>
			    </div>
			    <div class='chart-vert-wrap' id='geoChart'></div>
			  </div>
			  <div class='card'>
			    <div class='card-head'>
			      <div><div class='card-title'>Detalhamento</div><div class='card-sub'>Análise por dimensão - mini-barras nas colunas R$</div></div>
			      <div class='tabs' id='abasTabs'>
			        <button class='tab on' data-aba='cliente' onclick='setAba(&quot;cliente&quot;)'>Cliente</button>
			        <button class='tab' data-aba='atividade' onclick='setAba(&quot;atividade&quot;)'>Atividade</button>
			        <button class='tab' data-aba='porte' onclick='setAba(&quot;porte&quot;)'>Porte</button>
			        <button class='tab' data-aba='cidade' onclick='setAba(&quot;cidade&quot;)'>Cidade</button>
			      </div>
			    </div>
			    <div class='table-wrap' id='tabelaBox'></div>
			  </div>
			</div>
			<div class='tt' id='tt'></div>" &
			"<script type='application/json' id='jKpi'>" & [_JSON KPIs Clientes] & "</script>" &
			"<script type='application/json' id='jAt'>"  & [_JSON Distribuicao Atividade Clientes] & "</script>" &
			"<script type='application/json' id='jPt'>"  & [_JSON Distribuicao Porte Clientes] & "</script>" &
			"<script type='application/json' id='jGcd'>" & [_JSON Ranking Cidade Clientes] & "</script>" &
			"<script type='application/json' id='jGuf'>" & [_JSON Ranking UF Clientes] & "</script>" &
			"<script type='application/json' id='jTcl'>" & [_JSON Tabela Cliente Clientes] & "</script>" &
			"<script type='application/json' id='jTat'>" & [_JSON Tabela Atividade Clientes] & "</script>" &
			"<script type='application/json' id='jTpt'>" & [_JSON Tabela Porte Clientes] & "</script>" &
			"<script type='application/json' id='jTcd'>" & [_JSON Tabela Cidade Clientes] & "</script>" &
			[_JS Clientes]
		displayFolder: HTML Clientes
		lineageTag: f352ed6a-f1be-4d4c-98c8-0ed15e2bf8c3

	/// Quantidade de clientes distintos com algum valor de devolucao no periodo filtrado.
	measure 'Clientes com Devolução' =
			CALCULATE(
			    DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]),
			    DCVVQ_VENDAGERALTELEVENDAS[VLRDEVOLUCAO] > 0
			)
		formatString: 0
		lineageTag: b99496b8-7174-483e-907b-b823d66f9eab

	/// Variacao percentual MoM da quantidade de clientes com devolucao.
	measure 'MoM Clientes com Devolução %' =
			VAR Atual = [Clientes com Devolução]
			VAR Anterior = CALCULATE([Clientes com Devolução], DATEADD(D_Calendario[Data], -1, MONTH))
			VAR Variacao = DIVIDE(Atual - Anterior, Anterior, 0)
			RETURN FORMAT(Variacao, "+0.0%;-0.0%;0.0%")
		lineageTag: 8723ab9b-8c0e-4c24-9274-5dee75ed51a2

	/// Variacao percentual MoM da Taxa de Devolucao (R$). Compara fracao atual vs mes anterior.
	measure 'MoM Taxa de Devolução %' =
			VAR Atual = [Taxa de Devolução (R$)]
			VAR Anterior = CALCULATE([Taxa de Devolução (R$)], DATEADD(D_Calendario[Data], -1, MONTH))
			VAR Variacao = DIVIDE(Atual - Anterior, Anterior, 0)
			RETURN FORMAT(Variacao, "+0.0%;-0.0%;0.0%")
		lineageTag: f51f6846-cfe7-4fe5-b2f4-b114b4b7cd88

	/// JSON com dados dos 4 KPIs do HTML Devolucoes. v2 - corrigido espaco extra em momClientes.
	measure '_JSON KPIs Devolucoes' =
			"{""totalRS"":"     & SUBSTITUTE(FORMAT(COALESCE([Total Devoluções (R$)], 0), "0.00"), ",", ".") &
			",""momRS"":"""      & COALESCE([MoM Devoluções %], "--") & """" &
			",""totalPeso"":"   & SUBSTITUTE(FORMAT(COALESCE([Peso Total Devolvido], 0), "0.00"), ",", ".") &
			",""momPeso"":"""    & COALESCE([MoM Peso Total Devolvido %], "--") & """" &
			",""taxaDev"":"     & SUBSTITUTE(FORMAT(COALESCE([Taxa de Devolução (R$)], 0) * 100, "0.00"), ",", ".") &
			",""momTaxa"":"""    & COALESCE([MoM Taxa de Devolução %], "--") & """" &
			",""clientesDev"":" & COALESCE([Clientes com Devolução], 0) &
			",""momClientes"":""" & COALESCE([MoM Clientes com Devolução %], "--") & """" &
			"}"
		displayFolder: HTML Devolucoes
		lineageTag: 92c95d87-5ea2-404a-b29a-f795629d0644

	/// Mix por Categoria de Devolucao (Comercial, Qualidade, Logistica, Industria, etc.). Para a rosca de gargalo - somente perspectiva de devolucao (sem toggle V/D).
	measure '_JSON Mix Categoria Devolucoes' =
			VAR _cats =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução]) &&
			        DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução] <> "Sem tipo"
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _cats,
			        "_devRS",   [Total Devoluções (R$)],
			        "_devPeso", [Peso Total Devolvido],
			        "_qtdTipos", CALCULATE(DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO]), DCVVQ_VENDAGERALTELEVENDAS[VLRDEVOLUCAO] > 0)
			    )
			VAR _f = FILTER(_com, [_devRS] > 0)
			RETURN
			"[" & CONCATENATEX(
			    _f,
			    "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução], """""", ""), "\", "") &
			    """,""val"":"      & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""peso"":"       & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			    ",""qtdTipos"":"   & COALESCE([_qtdTipos], 0) &
			    "}",
			    ",",
			    [_devRS], DESC
			) & "]"
		displayFolder: HTML Devolucoes
		lineageTag: e303af03-8463-4b19-961a-f4a98bcb2715

	/// Top motivos de devolucao (TIPODEVOLUCAO especifico) com tag de categoria. Para o card Top 10 Motivos.
	measure '_JSON Top Motivos Devolucoes' =
			VAR _tipos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO]) &&
			        DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _tipos,
			        "_categoria", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução])),
			        "_devRS",     [Total Devoluções (R$)],
			        "_devPeso",   [Peso Total Devolvido],
			        "_clientes",  [Clientes com Devolução]
			    )
			VAR _top = TOPN(20, FILTER(_com, [_devRS] > 0), [_devRS], DESC)
			RETURN
			"[" & CONCATENATEX(
			    _top,
			    "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO], """""", ""), "\", "") &
			    """,""categoria"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_categoria], "-"), """""", ""), "\", "") &
			    """,""val"":"      & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""peso"":"       & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			    ",""clientes"":"   & COALESCE([_clientes], 0) &
			    "}",
			    ",",
			    [_devRS], DESC
			) & "]"
		displayFolder: HTML Devolucoes
		lineageTag: 660d2efb-45a6-4209-9e72-d8be75c91857

	/// Evolucao mensal de devolucoes. v3 - ignora filtro de D_Calendario (mostra todos os meses do dataset). Outros filtros (cliente, vendedor, atividade, etc.) ainda se aplicam.
	measure '_JSON Evolucao Mensal Devolucoes' =
			VAR _meses =
			    CALCULATETABLE(
			        FILTER(
			            SUMMARIZE(D_Calendario, D_Calendario[Mês/Ano]),
			            CALCULATE([Faturamento Total]) > 0
			        ),
			        REMOVEFILTERS(D_Calendario)
			    )
			VAR _com =
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            _meses,
			            "_devRS",   CALCULATE([Total Devoluções (R$)]),
			            "_devPeso", CALCULATE([Peso Total Devolvido]),
			            "_taxaDev", CALCULATE([Taxa de Devolução (R$)]) * 100,
			            "_ordem",   CALCULATE(MIN(D_Calendario[Data]))
			        ),
			        REMOVEFILTERS(D_Calendario)
			    )
			VAR _ordenado = TOPN(24, _com, [_ordem], ASC)
			RETURN
			"[" & CONCATENATEX(
			    _ordenado,
			    "{""mes"":""" & SUBSTITUTE(D_Calendario[Mês/Ano], """""", "") &
			    """,""val"":"   & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""peso"":"    & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			    ",""taxa"":"    & SUBSTITUTE(FORMAT(COALESCE([_taxaDev], 0), "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_ordem], ASC
			) & "]"
		displayFolder: HTML Devolucoes
		lineageTag: f0f0f3cf-f507-4e29-9969-491dc6537af6

	/// Top clientes por devolucao (top 50, JS faz slice 0,15). Estrutura {rs:[...], peso:[...]} para toggle R$/Peso.
	measure '_JSON Top Cliente Devolucoes' =
			VAR _clientes =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE]) &&
			        DCVVQ_VENDAGERALTELEVENDAS[CLIENTE] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _clientes,
			        "_cidade",    CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[CIDADE])),
			        "_atividade", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE])),
			        "_devRS",     [Total Devoluções (R$)],
			        "_devPeso",   [Peso Total Devolvido],
			        "_pedidos",   [Total de Pedidos]
			    )
			VAR _topRS   = TOPN(50, FILTER(_com, [_devRS] > 0),   [_devRS], DESC)
			VAR _topPeso = TOPN(50, FILTER(_com, [_devPeso] > 0), [_devPeso], DESC)
			VAR _arrRS =
			    "[" & CONCATENATEX(
			        _topRS,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE], """""", ""), "\", "") &
			        """,""val"":"      & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""peso"":"       & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""cidade"":"""   & SUBSTITUTE(SUBSTITUTE(COALESCE([_cidade], "-"), """""", ""), "\", "") &
			        """,""atividade"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_atividade], "-"), """""", ""), "\", "") &
			        """,""pedidos"":"  & COALESCE([_pedidos], 0) &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			VAR _arrPeso =
			    "[" & CONCATENATEX(
			        _topPeso,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE], """""", ""), "\", "") &
			        """,""val"":"      & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""rs"":"         & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""cidade"":"""   & SUBSTITUTE(SUBSTITUTE(COALESCE([_cidade], "-"), """""", ""), "\", "") &
			        """,""atividade"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_atividade], "-"), """""", ""), "\", "") &
			        """,""pedidos"":"  & COALESCE([_pedidos], 0) &
			        "}",
			        ",",
			        [_devPeso], DESC
			    ) & "]"
			RETURN
			"{""rs"":" & _arrRS & ",""peso"":" & _arrPeso & "}"
		displayFolder: HTML Devolucoes
		lineageTag: b6eead80-f170-4b17-953e-6b01da0d6f21

	/// Top produtos por devolucao (top 50, JS faz slice 0,15). Estrutura {rs:[...], peso:[...]} para toggle R$/Peso.
	measure '_JSON Top Produto Devolucoes' =
			VAR _produtos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO]) &&
			        DCVVQ_VENDAGERALTELEVENDAS[PRODUTO] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _produtos,
			        "_grupo",   CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO])),
			        "_devRS",   [Total Devoluções (R$)],
			        "_devPeso", [Peso Total Devolvido],
			        "_qtdLinhas", CALCULATE(COUNTROWS(DCVVQ_VENDAGERALTELEVENDAS), DCVVQ_VENDAGERALTELEVENDAS[VLRDEVOLUCAO] > 0)
			    )
			VAR _topRS   = TOPN(50, FILTER(_com, [_devRS] > 0),   [_devRS], DESC)
			VAR _topPeso = TOPN(50, FILTER(_com, [_devPeso] > 0), [_devPeso], DESC)
			VAR _arrRS =
			    "[" & CONCATENATEX(
			        _topRS,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO], """""", ""), "\", "") &
			        """,""val"":"      & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""peso"":"       & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""grupo"":"""    & SUBSTITUTE(SUBSTITUTE(COALESCE([_grupo], "-"), """""", ""), "\", "") &
			        """,""qtd"":"      & COALESCE([_qtdLinhas], 0) &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			VAR _arrPeso =
			    "[" & CONCATENATEX(
			        _topPeso,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO], """""", ""), "\", "") &
			        """,""val"":"      & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""rs"":"         & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""grupo"":"""    & SUBSTITUTE(SUBSTITUTE(COALESCE([_grupo], "-"), """""", ""), "\", "") &
			        """,""qtd"":"      & COALESCE([_qtdLinhas], 0) &
			        "}",
			        ",",
			        [_devPeso], DESC
			    ) & "]"
			RETURN
			"{""rs"":" & _arrRS & ",""peso"":" & _arrPeso & "}"
		displayFolder: HTML Devolucoes
		lineageTag: 8cbcf2b1-075d-4b46-912e-fd50207923c7

	/// Top vendedores com devolucao (toggle R$/Peso). JS faz slice 0,15.
	measure '_JSON Top Vendedor Devolucoes' =
			VAR _vendedores =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR]) &&
			        DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _vendedores,
			        "_supervisor", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[SUPERVISOR])),
			        "_devRS",     [Total Devoluções (R$)],
			        "_devPeso",   [Peso Total Devolvido],
			        "_clientes",  [Clientes com Devolução]
			    )
			VAR _topRS   = TOPN(50, FILTER(_com, [_devRS] > 0),   [_devRS], DESC)
			VAR _topPeso = TOPN(50, FILTER(_com, [_devPeso] > 0), [_devPeso], DESC)
			VAR _arrRS =
			    "[" & CONCATENATEX(
			        _topRS,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR], """""", ""), "\", "") &
			        """,""val"":"       & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""peso"":"        & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""supervisor"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_supervisor], "-"), """""", ""), "\", "") &
			        """,""clientes"":"  & COALESCE([_clientes], 0) &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			VAR _arrPeso =
			    "[" & CONCATENATEX(
			        _topPeso,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR], """""", ""), "\", "") &
			        """,""val"":"       & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""rs"":"          & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""supervisor"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_supervisor], "-"), """""", ""), "\", "") &
			        """,""clientes"":"  & COALESCE([_clientes], 0) &
			        "}",
			        ",",
			        [_devPeso], DESC
			    ) & "]"
			RETURN
			"{""rs"":" & _arrRS & ",""peso"":" & _arrPeso & "}"
		displayFolder: HTML Devolucoes
		lineageTag: 7daa026f-6f4f-44af-90f5-b0ce2169f8d2

	/// Top cidades com devolucao (toggle R$/Peso). JS faz slice 0,15. Para o card two-col esquerda.
	measure '_JSON Top Cidade Devolucoes' =
			VAR _cidades =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[CIDADE]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[CIDADE]) &&
			        DCVVQ_VENDAGERALTELEVENDAS[CIDADE] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _cidades,
			        "_uf",        CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[UF])),
			        "_devRS",     [Total Devoluções (R$)],
			        "_devPeso",   [Peso Total Devolvido],
			        "_clientes",  [Clientes com Devolução]
			    )
			VAR _topRS   = TOPN(50, FILTER(_com, [_devRS] > 0),   [_devRS], DESC)
			VAR _topPeso = TOPN(50, FILTER(_com, [_devPeso] > 0), [_devPeso], DESC)
			VAR _arrRS =
			    "[" & CONCATENATEX(
			        _topRS,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CIDADE], """""", ""), "\", "") &
			        """,""val"":"       & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""peso"":"        & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""uf"":"""        & SUBSTITUTE(SUBSTITUTE(COALESCE([_uf], "-"), """""", ""), "\", "") &
			        """,""clientes"":"  & COALESCE([_clientes], 0) &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			VAR _arrPeso =
			    "[" & CONCATENATEX(
			        _topPeso,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CIDADE], """""", ""), "\", "") &
			        """,""val"":"       & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""rs"":"          & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""uf"":"""        & SUBSTITUTE(SUBSTITUTE(COALESCE([_uf], "-"), """""", ""), "\", "") &
			        """,""clientes"":"  & COALESCE([_clientes], 0) &
			        "}",
			        ",",
			        [_devPeso], DESC
			    ) & "]"
			RETURN
			"{""rs"":" & _arrRS & ",""peso"":" & _arrPeso & "}"
		displayFolder: HTML Devolucoes
		lineageTag: 042f1937-6116-4360-aeca-4779d91e0e2b

	/// Top atividades com devolucao (toggle R$/Peso). Para o card two-col direita.
	measure '_JSON Top Atividade Devolucoes' =
			VAR _ativs =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE]) &&
			        DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _ativs,
			        "_devRS",     [Total Devoluções (R$)],
			        "_devPeso",   [Peso Total Devolvido],
			        "_clientes",  [Clientes com Devolução]
			    )
			VAR _comRS   = FILTER(_com, [_devRS] > 0)
			VAR _comPeso = FILTER(_com, [_devPeso] > 0)
			VAR _arrRS =
			    "[" & CONCATENATEX(
			        _comRS,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE], """""", ""), "\", "") &
			        """,""val"":"       & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""peso"":"        & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""clientes"":"   & COALESCE([_clientes], 0) &
			        "}",
			        ",",
			        [_devRS], DESC
			    ) & "]"
			VAR _arrPeso =
			    "[" & CONCATENATEX(
			        _comPeso,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE], """""", ""), "\", "") &
			        """,""val"":"       & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			        ",""rs"":"          & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			        ",""clientes"":"   & COALESCE([_clientes], 0) &
			        "}",
			        ",",
			        [_devPeso], DESC
			    ) & "]"
			RETURN
			"{""rs"":" & _arrRS & ",""peso"":" & _arrPeso & "}"
		displayFolder: HTML Devolucoes
		lineageTag: f12108b4-d709-4d9c-be04-6d42179087db

	/// Tabela detalhada por MOTIVO (TIPODEVOLUCAO) - todos os tipos. Coluna categoria como tag.
	measure '_JSON Tabela Motivo Devolucoes' =
			VAR _tipos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO]) &&
			        DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _tipos,
			        "_categoria", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução])),
			        "_devRS",     [Total Devoluções (R$)],
			        "_devPeso",   [Peso Total Devolvido],
			        "_qtdLinhas", CALCULATE(COUNTROWS(DCVVQ_VENDAGERALTELEVENDAS), DCVVQ_VENDAGERALTELEVENDAS[VLRDEVOLUCAO] > 0),
			        "_clientes",  [Clientes com Devolução]
			    )
			VAR _f = FILTER(_com, [_devRS] > 0)
			RETURN
			"[" & CONCATENATEX(
			    _f,
			    "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO], """""", ""), "\", "") &
			    """,""categoria"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_categoria], "-"), """""", ""), "\", "") &
			    """,""devRS"":"    & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""devPeso"":"    & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			    ",""qtdLinhas"":"  & COALESCE([_qtdLinhas], 0) &
			    ",""clientes"":"   & COALESCE([_clientes], 0) &
			    "}",
			    ",",
			    [_devRS], DESC
			) & "]"
		displayFolder: HTML Devolucoes
		lineageTag: 87cc4fa9-654e-4a45-b30a-03b5f676eb8c

	/// Tabela detalhada de clientes com devolucao (top 200 por devolucao R$). Inclui categoria dominante do problema.
	measure '_JSON Tabela Cliente Devolucoes' =
			VAR _clientes =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE]) &&
			        DCVVQ_VENDAGERALTELEVENDAS[CLIENTE] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _clientes,
			        "_cidade",     CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[CIDADE])),
			        "_atividade",  CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE])),
			        "_porte",      CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[PORTE])),
			        "_fat",        [Faturamento Total],
			        "_devRS",      [Total Devoluções (R$)],
			        "_devPeso",    [Peso Total Devolvido],
			        "_catDominante",
			            CALCULATE(
			                MAXX(
			                    TOPN(
			                        1,
			                        FILTER(VALUES(DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução]), [Total Devoluções (R$)] > 0),
			                        [Total Devoluções (R$)],
			                        DESC
			                    ),
			                    DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução]
			                )
			            )
			    )
			VAR _top = TOPN(200, FILTER(_com, [_devRS] > 0), [_devRS], DESC)
			RETURN
			"[" & CONCATENATEX(
			    _top,
			    "{""cliente"":"""   & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE], """""", ""), "\", "") &
			    """,""cidade"":"""   & SUBSTITUTE(SUBSTITUTE(COALESCE([_cidade], "-"), """""", ""), "\", "") &
			    """,""atividade"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_atividade], "-"), """""", ""), "\", "") &
			    """,""porte"":"""     & SUBSTITUTE(SUBSTITUTE(COALESCE([_porte], "-"), """""", ""), "\", "") &
			    """,""categoria"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_catDominante], "-"), """""", ""), "\", "") &
			    """,""devRS"":"     & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""devPeso"":"     & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			    ",""taxaDev"":"     & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_devRS], 0), COALESCE([_fat], 0) + COALESCE([_devRS], 0), 0) * 100, "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_devRS], DESC
			) & "]"
		displayFolder: HTML Devolucoes
		lineageTag: 3386b876-035b-42cf-b551-4f7e103054ba

	/// Tabela detalhada de produtos com devolucao (top 100). Grupo como tag.
	measure '_JSON Tabela Produto Devolucoes' =
			VAR _produtos =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO]) &&
			        DCVVQ_VENDAGERALTELEVENDAS[PRODUTO] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _produtos,
			        "_grupo",     CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO])),
			        "_subgrupo",  CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[SUBGRUPOPROD])),
			        "_fat",       [Faturamento Total],
			        "_devRS",     [Total Devoluções (R$)],
			        "_devPeso",   [Peso Total Devolvido],
			        "_qtdLinhas", CALCULATE(COUNTROWS(DCVVQ_VENDAGERALTELEVENDAS), DCVVQ_VENDAGERALTELEVENDAS[VLRDEVOLUCAO] > 0),
			        "_clientes",  [Clientes com Devolução]
			    )
			VAR _top = TOPN(100, FILTER(_com, [_devRS] > 0), [_devRS], DESC)
			RETURN
			"[" & CONCATENATEX(
			    _top,
			    "{""produto"":"""   & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO], """""", ""), "\", "") &
			    """,""grupo"":"""    & SUBSTITUTE(SUBSTITUTE(COALESCE([_grupo], "-"), """""", ""), "\", "") &
			    """,""subgrupo"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_subgrupo], "-"), """""", ""), "\", "") &
			    """,""devRS"":"     & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""devPeso"":"     & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			    ",""qtdLinhas"":"   & COALESCE([_qtdLinhas], 0) &
			    ",""clientes"":"    & COALESCE([_clientes], 0) &
			    ",""taxaDev"":"     & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_devRS], 0), COALESCE([_fat], 0) + COALESCE([_devRS], 0), 0) * 100, "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_devRS], DESC
			) & "]"
		displayFolder: HTML Devolucoes
		lineageTag: b8cc5a3a-41f2-402f-b961-a5cbfa5ee1a1

	/// Tabela detalhada de vendedores com devolucao. Supervisor e gerente como tags.
	measure '_JSON Tabela Vendedor Devolucoes' =
			VAR _vendedores =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR]) &&
			        DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _vendedores,
			        "_supervisor", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[SUPERVISOR])),
			        "_gerente",    CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[GERENTE])),
			        "_fat",        [Faturamento Total],
			        "_devRS",      [Total Devoluções (R$)],
			        "_devPeso",    [Peso Total Devolvido],
			        "_clientes",   [Clientes com Devolução]
			    )
			VAR _f = FILTER(_com, [_devRS] > 0)
			RETURN
			"[" & CONCATENATEX(
			    _f,
			    "{""vendedor"":"""  & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR], """""", ""), "\", "") &
			    """,""supervisor"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_supervisor], "-"), """""", ""), "\", "") &
			    """,""gerente"":"""  & SUBSTITUTE(SUBSTITUTE(COALESCE([_gerente], "-"), """""", ""), "\", "") &
			    """,""devRS"":"     & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""devPeso"":"     & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			    ",""clientes"":"    & COALESCE([_clientes], 0) &
			    ",""taxaDev"":"     & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_devRS], 0), COALESCE([_fat], 0) + COALESCE([_devRS], 0), 0) * 100, "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_devRS], DESC
			) & "]"
		displayFolder: HTML Devolucoes
		lineageTag: 245faed8-77f6-43d9-9462-3b7af2c7ed69

	/// Tabela detalhada de cidades com devolucao (top 50). UF como tag.
	measure '_JSON Tabela Cidade Devolucoes' =
			VAR _cidades =
			    FILTER(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[CIDADE]),
			        NOT ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[CIDADE]) &&
			        DCVVQ_VENDAGERALTELEVENDAS[CIDADE] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _cidades,
			        "_uf",        CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[UF])),
			        "_fat",       [Faturamento Total],
			        "_devRS",     [Total Devoluções (R$)],
			        "_devPeso",   [Peso Total Devolvido],
			        "_clientes",  [Clientes com Devolução],
			        "_produtos",  CALCULATE(DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO]), DCVVQ_VENDAGERALTELEVENDAS[VLRDEVOLUCAO] > 0)
			    )
			VAR _top = TOPN(50, FILTER(_com, [_devRS] > 0), [_devRS], DESC)
			RETURN
			"[" & CONCATENATEX(
			    _top,
			    "{""cidade"":"""    & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CIDADE], """""", ""), "\", "") &
			    """,""uf"":"""       & SUBSTITUTE(SUBSTITUTE(COALESCE([_uf], "-"), """""", ""), "\", "") &
			    """,""devRS"":"     & SUBSTITUTE(FORMAT(COALESCE([_devRS], 0), "0.00"), ",", ".") &
			    ",""devPeso"":"     & SUBSTITUTE(FORMAT(COALESCE([_devPeso], 0), "0.00"), ",", ".") &
			    ",""clientes"":"    & COALESCE([_clientes], 0) &
			    ",""produtos"":"    & COALESCE([_produtos], 0) &
			    ",""taxaDev"":"     & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_devRS], 0), COALESCE([_fat], 0) + COALESCE([_devRS], 0), 0) * 100, "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_devRS], DESC
			) & "]"
		displayFolder: HTML Devolucoes
		lineageTag: f1ade644-e310-4e43-b9ab-1b5d82fdbc5e

	/// Script JS - v2. Ajustes: (1) fontes maiores na legenda da rosca; (2) rotulos de dados sobre cada ponto na evolucao mensal; (3) tooltip viewport-aware (reposiciona pra esquerda/cima quando ultrapassa borda).
	measure '_JS Devolucoes' =
			"<script>" & "(function () {
			  'use strict';
			  function rJ(id) { var e = document.getElementById(id); try { return JSON.parse((e && e.textContent) || 'null'); } catch (ex) { return null; } }
			  function esc(v) { return String(v == null ? '' : v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
			  function escT(v) { return esc(v).replace(/'/g,'&#39;'); }
			  function fN(v) { return (Number(v) || 0).toLocaleString('pt-BR'); }
			  function fA(v) { v = Number(v) || 0; if (Math.abs(v) >= 1e6) return (v/1e6).toFixed(1).replace('.',',') + ' M'; if (Math.abs(v) >= 1e3) return (v/1e3).toFixed(1).replace('.',',') + ' mil'; return fN(v); }
			  function fM(v) { v = Number(v) || 0; return 'R$ ' + v.toLocaleString('pt-BR', {minimumFractionDigits:2, maximumFractionDigits:2}); }
			  function fMK(v) { v = Number(v) || 0; if (Math.abs(v) >= 1e6) return 'R$ ' + (v/1e6).toFixed(2).replace('.',',') + ' M'; if (Math.abs(v) >= 1e3) return 'R$ ' + (v/1e3).toFixed(1).replace('.',',') + ' mil'; return fM(v); }
			  function fPct(v) { return (Number(v)||0).toFixed(2).replace('.',',') + '%'; }
			  function momCls(s) { if (!s || s === '--') return 'neu'; return s.indexOf('+') === 0 ? 'up' : (s.indexOf('-') === 0 ? 'down' : 'neu'); }
			  function momClsInv(s) { if (!s || s === '--') return 'neu'; return s.indexOf('-') === 0 ? 'up' : (s.indexOf('+') === 0 ? 'down' : 'neu'); }
			  function svgDim(el, fbW, fbH) { var bb = el.getBoundingClientRect(); return [Math.round(bb.width) || fbW, Math.round(bb.height) || fbH]; }
			  function catColor(cat) {
			    var map = {
			      'Comercial':      {bg:'rgba(192,124,58,.15)', fg:'#995F2C'},
			      'Qualidade':      {bg:'rgba(160,72,72,.15)',  fg:'#7A2E2E'},
			      'Logística':      {bg:'rgba(74,110,138,.15)', fg:'#3A5872'},
			      'Indústria':      {bg:'rgba(78,125,98,.15)',  fg:'#3D6049'},
			      'Multi/Misto':    {bg:'rgba(184,147,90,.18)', fg:'#8A6740'},
			      'Fiscal':         {bg:'rgba(90,90,90,.15)',   fg:'#5A5A5A'},
			      'Administrativo': {bg:'rgba(58,36,16,.12)',   fg:'#3A2410'}
			    };
			    return map[cat] || {bg:'rgba(139,139,139,.12)', fg:'#5A5A5A'};
			  }
			  function tagColor(str) {
			    if (!str) return {bg:'rgba(139,139,139,.12)',fg:'#5A5A5A'};
			    var h=0; for (var i=0;i<str.length;i++) h = ((h<<5)-h) + str.charCodeAt(i);
			    var palette = [
			      {bg:'rgba(184,147,90,.15)',fg:'#8A6740'},
			      {bg:'rgba(78,125,98,.15)',fg:'#3D6049'},
			      {bg:'rgba(74,110,138,.15)',fg:'#3A5872'},
			      {bg:'rgba(192,124,58,.15)',fg:'#995F2C'},
			      {bg:'rgba(58,36,16,.12)',fg:'#3A2410'},
			      {bg:'rgba(90,90,90,.15)',fg:'#5A5A5A'}
			    ];
			    return palette[Math.abs(h) % palette.length];
			  }
			  var ttEl = document.getElementById('tt');
			  window.tip = function(e,h){
			    if (!ttEl) return;
			    ttEl.innerHTML = h;
			    ttEl.classList.add('on');
			    var ttW = ttEl.offsetWidth;
			    var ttH = ttEl.offsetHeight;
			    var vw = window.innerWidth || document.documentElement.clientWidth;
			    var vh = window.innerHeight || document.documentElement.clientHeight;
			    var x = e.clientX + 14;
			    var y = e.clientY - ttH - 10;
			    if (x + ttW > vw - 8) x = e.clientX - ttW - 14;
			    if (x < 8) x = 8;
			    if (y < 8) y = e.clientY + 18;
			    if (y + ttH > vh - 8) y = vh - ttH - 8;
			    ttEl.style.left = x + 'px';
			    ttEl.style.top = y + 'px';
			  };
			  window.tipOff = function(){ ttEl && ttEl.classList.remove('on'); };
			  var kpiIcons = {
			    money:    ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><line x1='12' y1='1' x2='12' y2='23'/><path d='M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6'/></svg>"",
			    scale:    ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><path d='M12 3v18M3 12h18M5 7l14 10M5 17L19 7'/></svg>"",
			    percent:  ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><line x1='19' y1='5' x2='5' y2='19'/><circle cx='6.5' cy='6.5' r='2.5'/><circle cx='17.5' cy='17.5' r='2.5'/></svg>"",
			    users:    ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><path d='M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2'/><circle cx='9' cy='7' r='4'/><path d='M23 21v-2a4 4 0 0 0-3-3.87'/><path d='M16 3.13a4 4 0 0 1 0 7.75'/></svg>""
			  };
			  function buildKPIs(){
			    var K=rJ('jKpi')||{}; var el=document.getElementById('kpiGrid'); if(!el) return;
			    var cards=[
			      {icon:'money',  label:'Total Devolvido',       val:fMK(K.totalRS||0),    sub:'MoM = <span class=\''+momClsInv(K.momRS)+'\'>'+(K.momRS||'-')+'</span>'},
			      {icon:'scale',  label:'Peso Devolvido (kg)',   val:fA(K.totalPeso||0),   sub:'MoM = <span class=\''+momClsInv(K.momPeso)+'\'>'+(K.momPeso||'-')+'</span>'},
			      {icon:'percent',label:'Taxa de Devolução',     val:fPct(K.taxaDev||0),   sub:'MoM = <span class=\''+momClsInv(K.momTaxa)+'\'>'+(K.momTaxa||'-')+'</span>'},
			      {icon:'users',  label:'Clientes com Devolução',val:fN(K.clientesDev||0), sub:'MoM = <span class=\''+momClsInv(K.momClientes)+'\'>'+(K.momClientes||'-')+'</span>'}
			    ];
			    el.innerHTML=cards.map(function(c){ return ""<div class='kpi'><div class='kpi-top'><span class='kpi-label'>""+c.label+""</span><div class='kpi-icon'>""+kpiIcons[c.icon]+""</div></div><div class='kpi-val'>""+c.val+""</div><div class='kpi-sub'>""+c.sub+""</div></div>""; }).join('');
			  }
			  function renderRoscaCat(){
			    var el=document.getElementById('svgCat'); if(!el) return;
			    var d=svgDim(el,420,360); var W=d[0],H=d[1];
			    el.setAttribute('viewBox','0 0 '+W+' '+H);
			    var arr=(rJ('jMix')||[]).filter(function(d2){ return (Number(d2.val)||0) > 0; });
			    if(!arr.length){ el.innerHTML=""<text x='""+(W/2)+""' y='""+(H/2)+""' text-anchor='middle' fill='#999'>Sem dados</text>""; return; }
			    var total=arr.reduce(function(s,d2){ return s + (Number(d2.val)||0); }, 0);
			    if(total<=0) total=1;
			    var cx=W*0.30, cy=H/2;
			    var r=Math.min(W*0.26, H*0.40), ri=r*0.58;
			    var start=-Math.PI/2;
			    var svg='';
			    arr.forEach(function(d2){
			      var v=Number(d2.val)||0;
			      var ang=(v/total)*Math.PI*2;
			      var end=start+ang;
			      var largeArc = ang > Math.PI ? 1 : 0;
			      var x1=cx+r*Math.cos(start), y1=cy+r*Math.sin(start);
			      var x2=cx+r*Math.cos(end),   y2=cy+r*Math.sin(end);
			      var xi1=cx+ri*Math.cos(end), yi1=cy+ri*Math.sin(end);
			      var xi2=cx+ri*Math.cos(start), yi2=cy+ri*Math.sin(start);
			      var dPath='M '+x1.toFixed(2)+' '+y1.toFixed(2) +
			                ' A '+r.toFixed(2)+' '+r.toFixed(2)+' 0 '+largeArc+' 1 '+x2.toFixed(2)+' '+y2.toFixed(2) +
			                ' L '+xi1.toFixed(2)+' '+yi1.toFixed(2) +
			                ' A '+ri.toFixed(2)+' '+ri.toFixed(2)+' 0 '+largeArc+' 0 '+xi2.toFixed(2)+' '+yi2.toFixed(2) +
			                ' Z';
			      var pct=(v/total*100).toFixed(1).replace('.',',');
			      var clr=catColor(d2.nome).fg;
			      var ttHtml='<b>'+escT(d2.nome)+'</b><br>Devolução: '+fMK(v)+'<br>Peso: '+fA(Number(d2.peso)||0)+' kg<br>'+pct+'% do total<br>'+(Number(d2.qtdTipos)||0)+' motivos distintos';
			      svg += ""<path class='donut-slice' d='""+dPath+""' fill='""+clr+""' stroke='#FFFFFF' stroke-width='2' onmousemove=\""tip(event,'""+ttHtml+""')\"" onmouseleave='tipOff()'/>"";
			      start=end;
			    });
			    svg += ""<text x='""+cx+""' y='""+(cy-4)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:24px;font-weight:700;font-family:Segoe UI,system-ui'>""+fMK(total)+""</text>"";
			    svg += ""<text x='""+cx+""' y='""+(cy+18)+""' text-anchor='middle' fill='#8B8B8B' style='font-size:12px;font-weight:600;letter-spacing:1.8px;font-family:Segoe UI,system-ui'>DEVOLUÇÃO</text>"";
			    var lx=W*0.58;
			    var step=48;
			    var ly=Math.max(32, (H - arr.length*step)/2 + 14);
			    arr.forEach(function(d2,i){
			      var v=Number(d2.val)||0;
			      var pct=(v/total*100).toFixed(1).replace('.',',');
			      var clr=catColor(d2.nome).fg;
			      var y=ly + i*step;
			      svg += ""<rect x='""+lx+""' y='""+(y-12)+""' width='15' height='15' rx='3' fill='""+clr+""'/>"";
			      svg += ""<text x='""+(lx+22)+""' y='""+y+""' fill='#1A1A1A' style='font-size:15px;font-weight:600;font-family:Segoe UI,system-ui'>""+esc(d2.nome)+""</text>"";
			      svg += ""<text x='""+(lx+22)+""' y='""+(y+18)+""' style='font-size:14px;font-family:Segoe UI,system-ui'><tspan fill='#5A5A5A'>""+fMK(v)+""</tspan> <tspan fill='#B8935A' font-weight='700'>""+pct+""%</tspan></text>"";
			    });
			    el.innerHTML=svg;
			  }
			  function renderTopMotivos(){
			    var el=document.getElementById('motivosList'); if(!el) return;
			    var arr=(rJ('jMot')||[]).slice(0,10);
			    if(!arr.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Math.max.apply(null,arr.map(function(d){ return Number(d.val)||0; }).concat([1]));
			    el.innerHTML=arr.map(function(d){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      var clr=catColor(d.categoria);
			      var tt='<b>'+escT(d.nome)+'</b><br>Categoria: '+escT(d.categoria)+'<br>Devolução: '+fMK(v)+'<br>Peso: '+fA(Number(d.peso)||0)+' kg<br>Clientes afetados: '+fN(Number(d.clientes)||0);
			      return ""<div class='bar-row' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'><div class='bar-head'><div class='bar-name'><span class='cat-pill' style='background:""+clr.bg+"";color:""+clr.fg+""'>""+esc(d.categoria)+""</span> ""+esc(d.nome)+""</div><div class='bar-val'>""+fMK(v)+""</div></div><div class='bar-track'><div class='bar-fill' data-w='""+w+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.bar-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  var _modoEvo='val';
			  window.setModoEvo=function(m){ _modoEvo=m; document.querySelectorAll('#evoModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderEvolucao(); };
			  function renderEvolucao(){
			    var el=document.getElementById('evoChart'); if(!el) return;
			    var arr=rJ('jEvo')||[];
			    if(!arr.length){ el.innerHTML=""<div style='padding:30px;color:#8B8B8B;text-align:center'>Sem dados</div>""; return; }
			    var containerW = el.clientWidth || 900;
			    var minW = Math.max(containerW, arr.length * 64);
			    var W = minW, H = 320;
			    var P = {t:46, r:30, b:50, l:65};
			    var maxV = Math.max.apply(null, arr.map(function(d){ return Number(d[_modoEvo])||0; }).concat([1])) * 1.15;
			    var stepX = (W - P.l - P.r) / Math.max(arr.length - 1, 1);
			    var fmt = _modoEvo==='val' ? fMK : (_modoEvo==='peso' ? function(v){return fA(v)+' kg';} : fPct);
			    var fmtAxis = _modoEvo==='val' ? function(v){return 'R$ '+fA(v);} : (_modoEvo==='peso' ? function(v){return fA(v);} : function(v){return (Number(v)||0).toFixed(1).replace('.',',')+'%';});
			    var fmtLabel = _modoEvo==='val' ? function(v){return 'R$ '+fA(v);} : (_modoEvo==='peso' ? function(v){return fA(v);} : function(v){return (Number(v)||0).toFixed(2).replace('.',',')+'%';});
			    var label = _modoEvo==='val' ? 'Devolução R$' : (_modoEvo==='peso' ? 'Peso Devolvido' : 'Taxa de Devolução');
			    var uid='ev'+Math.floor(Math.random()*99999);
			    var svg = ""<defs><linearGradient id='area""+uid+""' x1='0%' y1='0%' x2='0%' y2='100%'><stop offset='0%' stop-color='#B8935A' stop-opacity='.35'/><stop offset='100%' stop-color='#B8935A' stop-opacity='0'/></linearGradient></defs>"";
			    for (var i=0; i<=4; i++){
			      var y = P.t + (H - P.t - P.b) * i / 4;
			      var v = maxV * (1 - i/4);
			      svg += ""<line x1='""+P.l+""' x2='""+(W-P.r)+""' y1='""+y.toFixed(1)+""' y2='""+y.toFixed(1)+""' stroke='rgba(0,0,0,.06)' stroke-dasharray='3,4'/>"";
			      svg += ""<text x='""+(P.l-6)+""' y='""+(y+4).toFixed(1)+""' text-anchor='end' fill='#8B8B8B' style='font-size:12px;font-family:Segoe UI,system-ui;font-weight:500'>""+fmtAxis(v)+""</text>"";
			    }
			    var pts = arr.map(function(d, i){
			      var v = Number(d[_modoEvo])||0;
			      var x = P.l + i * stepX;
			      var y = H - P.b - (v / maxV) * (H - P.t - P.b);
			      return {x:x, y:y, mes:d.mes, v:v, peso:d.peso, taxa:d.taxa, val:d.val};
			    });
			    var areaD = pts.map(function(p, i){ return (i===0?'M':'L')+p.x.toFixed(1)+','+p.y.toFixed(1); }).join(' ');
			    areaD += ' L'+pts[pts.length-1].x.toFixed(1)+','+(H-P.b)+' L'+pts[0].x.toFixed(1)+','+(H-P.b)+' Z';
			    var pathD = pts.map(function(p, i){ return (i===0?'M':'L')+p.x.toFixed(1)+','+p.y.toFixed(1); }).join(' ');
			    svg += ""<path d='""+areaD+""' fill='url(#area""+uid+"")' stroke='none'/>"";
			    svg += ""<path d='""+pathD+""' fill='none' stroke='#1A1A1A' stroke-width='2.5' stroke-linejoin='round' stroke-linecap='round'/>"";
			    pts.forEach(function(p){
			      var tt='<b>'+escT(p.mes)+'</b><br>Devolução: '+fMK(Number(p.val)||0)+'<br>Peso: '+fA(Number(p.peso)||0)+' kg<br>Taxa: '+fPct(Number(p.taxa)||0);
			      svg += ""<circle class='evo-pt' cx='""+p.x.toFixed(1)+""' cy='""+p.y.toFixed(1)+""' r='5' fill='#B8935A' stroke='#FFFFFF' stroke-width='2' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'/>"";
			    });
			    pts.forEach(function(p, i){
			      var lblY = Math.max(14, p.y - 14);
			      var lblAnchor = 'middle';
			      var lblX = p.x;
			      if (i === 0) { lblAnchor = 'start'; lblX = p.x - 4; }
			      else if (i === pts.length - 1) { lblAnchor = 'end'; lblX = p.x + 4; }
			      svg += ""<text x='""+lblX.toFixed(1)+""' y='""+lblY.toFixed(1)+""' text-anchor='""+lblAnchor+""' fill='#1A1A1A' style='font-size:11px;font-weight:700;font-family:Segoe UI,system-ui;font-variant-numeric:tabular-nums;pointer-events:none'>""+fmtLabel(p.v)+""</text>"";
			    });
			    pts.forEach(function(p){
			      svg += ""<text x='""+p.x.toFixed(1)+""' y='""+(H - P.b + 18)+""' text-anchor='middle' fill='#5A5A5A' style='font-size:11px;font-weight:500;font-family:Segoe UI,system-ui'>""+esc(p.mes)+""</text>"";
			    });
			    el.innerHTML = ""<svg width='""+W+""' height='""+H+""' xmlns='http://www.w3.org/2000/svg'>""+svg+""</svg>"";
			  }
			  var _modoHier='cliente', _modoHierMm='rs';
			  window.setModoHier=function(m){ _modoHier=m; document.querySelectorAll('#hierToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.h===m); }); renderHierarchico(); };
			  window.setModoHierMm=function(m){ _modoHierMm=m; document.querySelectorAll('#hierModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderHierarchico(); };
			  function renderHierarchico(){
			    var el=document.getElementById('hierChart'); if(!el) return;
			    var sources={cliente:'jHc', produto:'jHp', vendedor:'jHv'};
			    var data=rJ(sources[_modoHier])||{rs:[],peso:[]};
			    var arr=(data[_modoHierMm]||[]).slice(0,15);
			    if(!arr.length){ el.innerHTML=""<div style='padding:30px;color:#8B8B8B;text-align:center'>Sem dados</div>""; return; }
			    var H=500;
			    var P={t:38, r:24, b:70, l:68};
			    var n=arr.length;
			    var containerW = el.clientWidth || 900;
			    var availW = containerW - P.l - P.r;
			    var minBarW = 30, maxBarW = 56, defaultGap = 18, maxGap = 40;
			    var idealBarW = (availW - (n-1)*defaultGap) / Math.max(n,1);
			    var barW, gap, contentW, startX;
			    if (idealBarW >= maxBarW) { barW=maxBarW; var rem=availW-n*barW; gap=n>1?Math.min(maxGap, rem/(n-1)):0; var totalBars=n*barW+(n-1)*gap; startX=P.l+Math.max(0,(availW-totalBars)/2); contentW=containerW; }
			    else if (idealBarW >= minBarW) { barW=idealBarW; gap=defaultGap; startX=P.l; contentW=containerW; }
			    else { barW=minBarW; gap=defaultGap; startX=P.l; contentW=n*barW+(n-1)*gap+P.l+P.r; }
			    var W = Math.max(contentW, containerW);
			    var mx = Math.max.apply(null, arr.map(function(d){ return Number(d.val)||0; }).concat([1])) * 1.10;
			    var isRS = _modoHierMm==='rs';
			    var fmtVal = isRS ? fMK : function(v){return fA(v)+' kg';};
			    var fmtAxis = isRS ? function(v){return 'R$ '+fA(v);} : fA;
			    var lblMm = isRS ? 'Devolução R$' : 'Peso Devolvido';
			    var uid='h'+Math.floor(Math.random()*99999);
			    var maxWordChars = barW < 40 ? 10 : 14;
			    var svg = ""<defs><linearGradient id='bg""+uid+""' x1='0%' y1='0%' x2='0%' y2='100%'><stop offset='0%' stop-color='#A04848' stop-opacity='1'/><stop offset='100%' stop-color='#1A1A1A' stop-opacity='1'/></linearGradient></defs>"";
			    for (var i=0; i<=4; i++){
			      var y = P.t + (H - P.t - P.b) * i / 4;
			      var v = mx * (1 - i/4);
			      svg += ""<line x1='""+P.l+""' x2='""+(W-P.r)+""' y1='""+y.toFixed(1)+""' y2='""+y.toFixed(1)+""' stroke='rgba(0,0,0,.06)' stroke-dasharray='3,4'/>"";
			      if (i<4) svg += ""<text x='""+(P.l-6)+""' y='""+(y+4).toFixed(1)+""' text-anchor='end' fill='#8B8B8B' style='font-size:12.5px;font-family:Segoe UI,system-ui;font-weight:500'>""+fmtAxis(v)+""</text>"";
			    }
			    arr.forEach(function(d, i){
			      var v = Number(d.val)||0;
			      var bh = Math.max(2, (v/mx) * (H - P.t - P.b));
			      var bx = startX + i*(barW+gap);
			      var by = H - P.b - bh;
			      var labelX = bx + barW/2;
			      var ctx = '';
			      if (_modoHier==='cliente') ctx = '<br>Cidade: '+escT(d.cidade||'-')+'<br>Atividade: '+escT(d.atividade||'-');
			      else if (_modoHier==='produto') ctx = '<br>Grupo: '+escT(d.grupo||'-');
			      else ctx = '<br>Supervisor: '+escT(d.supervisor||'-')+'<br>Clientes: '+fN(Number(d.clientes)||0);
			      var altMm = isRS ? ('<br>Peso: '+fA(Number(d.peso)||0)+' kg') : ('<br>Devolução R$: '+fMK(Number(d.rs)||0));
			      var tt = '<b>'+escT(d.nome)+'</b><br>'+lblMm+': '+fmtVal(v)+altMm+ctx;
			      svg += ""<rect class='vbar' x='""+bx.toFixed(1)+""' y='""+by.toFixed(1)+""' width='""+barW.toFixed(1)+""' height='""+bh.toFixed(1)+""' rx='3' fill='url(#bg""+uid+"")' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'/>"";
			      var labelTop = isRS ? ('R$ '+fA(v)) : (fA(v)+' kg');
			      svg += ""<text x='""+labelX.toFixed(1)+""' y='""+(by-8).toFixed(1)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:11.5px;font-weight:700;font-variant-numeric:tabular-nums;font-family:Segoe UI,system-ui;pointer-events:none'>""+labelTop+""</text>"";
			      var words = d.nome.split(/\s+/);
			      var displayWords = words.slice(0, 4).map(function(w){ return w.length > maxWordChars ? w.slice(0, maxWordChars-2) + '..' : w; });
			      var nameY = H - P.b + 16;
			      displayWords.forEach(function(w, j){
			        svg += ""<text x='""+labelX.toFixed(1)+""' y='""+(nameY + j*14)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:11.5px;font-weight:500;font-family:Segoe UI,system-ui'>""+esc(w)+""</text>"";
			      });
			    });
			    el.innerHTML = ""<svg width='""+W+""' height='""+H+""' xmlns='http://www.w3.org/2000/svg'>""+svg+""</svg>"";
			  }
			  function buildBarList(elId, jsonId, modoVar, contextFn){
			    var el=document.getElementById(elId); if(!el) return;
			    var data=rJ(jsonId)||{rs:[],peso:[]};
			    var arr=data[modoVar]||[];
			    if(!arr.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Math.max.apply(null,arr.map(function(d){ return Number(d.val)||0; }).concat([1]));
			    var isRS = modoVar==='rs';
			    var fmtVal = isRS ? fMK : function(v){return fA(v)+' kg';};
			    var lblMm = isRS ? 'Devolução R$' : 'Peso Devolvido';
			    el.innerHTML=arr.map(function(d){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      var altMm = isRS ? ('<br>Peso: '+fA(Number(d.peso)||0)+' kg') : ('<br>Devolução R$: '+fMK(Number(d.rs)||0));
			      var tt = '<b>'+escT(d.nome)+'</b><br>'+lblMm+': '+fmtVal(v)+altMm+contextFn(d);
			      return ""<div class='bar-row' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'><div class='bar-head'><div class='bar-name'>""+esc(d.nome)+""</div><div class='bar-val'>""+fmtVal(v)+""</div></div><div class='bar-track'><div class='bar-fill' data-w='""+w+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.bar-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  var _modoCid='rs';
			  window.setModoCid=function(m){ _modoCid=m; document.querySelectorAll('#cidModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderCidades(); };
			  function renderCidades(){ buildBarList('cidList','jCd',_modoCid, function(d){ return '<br>UF: '+escT(d.uf||'-')+'<br>Clientes: '+fN(Number(d.clientes)||0); }); }
			  var _modoAtv='rs';
			  window.setModoAtv=function(m){ _modoAtv=m; document.querySelectorAll('#atvModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderAtividades(); };
			  function renderAtividades(){ buildBarList('atvList','jAtv',_modoAtv, function(d){ return '<br>Clientes afetados: '+fN(Number(d.clientes)||0); }); }
			  var _aba='motivo';
			  window.setAba=function(aba){ _aba=aba; document.querySelectorAll('#abasTabs .tab').forEach(function(t){ t.classList.toggle('on', t.dataset.aba===aba); }); renderTabela(); };
			  function renderTabela(){
			    var el=document.getElementById('tabelaBox'); if(!el) return;
			    var data, cols;
			    if(_aba==='motivo'){ data=rJ('jTm')||[]; cols=[{k:'nome',t:'Motivo',cls:'name'},{k:'categoria',t:'Categoria',cls:'cat'},{k:'devRS',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'devPeso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'qtdLinhas',t:'Ocorrências',cls:'num',fmt:fN},{k:'clientes',t:'Clientes',cls:'num',fmt:fN}]; }
			    else if(_aba==='cliente'){ data=rJ('jTc')||[]; cols=[{k:'cliente',t:'Cliente',cls:'name'},{k:'cidade',t:'Cidade',cls:'name'},{k:'atividade',t:'Atividade',cls:'tag'},{k:'porte',t:'Porte',cls:'tag'},{k:'categoria',t:'Cat. dominante',cls:'cat'},{k:'devRS',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'devPeso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else if(_aba==='produto'){ data=rJ('jTp')||[]; cols=[{k:'produto',t:'Produto',cls:'name'},{k:'grupo',t:'Grupo',cls:'tag'},{k:'subgrupo',t:'Subgrupo',cls:'tag'},{k:'devRS',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'devPeso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'qtdLinhas',t:'Ocorrências',cls:'num',fmt:fN},{k:'clientes',t:'Clientes',cls:'num',fmt:fN},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else if(_aba==='vendedor'){ data=rJ('jTv')||[]; cols=[{k:'vendedor',t:'Vendedor',cls:'name'},{k:'supervisor',t:'Supervisor',cls:'tag'},{k:'gerente',t:'Gerente',cls:'tag'},{k:'devRS',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'devPeso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'clientes',t:'Clientes',cls:'num',fmt:fN},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else { data=rJ('jTcd')||[]; cols=[{k:'cidade',t:'Cidade',cls:'name'},{k:'uf',t:'UF',cls:'tag'},{k:'devRS',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'devPeso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'clientes',t:'Clientes',cls:'num',fmt:fN},{k:'produtos',t:'Produtos',cls:'num',fmt:fN},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    if(!data.length){ el.innerHTML=""<div style='padding:20px;color:#8B8B8B;text-align:center'>Sem dados</div>""; return; }
			    var maxNum={};
			    cols.forEach(function(c){ if(c.cls==='num' && c.bar){ maxNum[c.k]=Math.max.apply(null, data.map(function(d){return Number(d[c.k])||0;}).concat([1])); } });
			    var head=""<thead><tr>"" + cols.map(function(c){ return ""<th class='th-""+c.cls+""'>""+c.t+""</th>""; }).join('') + ""</tr></thead>"";
			    var body=""<tbody>"" + data.map(function(d){
			      return ""<tr>"" + cols.map(function(c){
			        var v=d[c.k]; var text=c.fmt?c.fmt(v):esc(v);
			        if(c.cls==='num' && c.bar){
			          var n=Number(v)||0; var pct=Math.max(0,(n/maxNum[c.k])*100);
			          return ""<td class='td-num'><div class='cell-val'>""+text+""</div><div class='cell-bar'><div class='cell-fill' style='width:""+pct.toFixed(1)+""%'></div></div></td>"";
			        }
			        if(c.cls==='tag'){ var clr=tagColor(v); return ""<td class='td-tag'><span class='tag-badge' style='background:""+clr.bg+"";color:""+clr.fg+""'>""+esc(v||'-')+""</span></td>""; }
			        if(c.cls==='cat'){ var ccr=catColor(v); return ""<td class='td-tag'><span class='tag-badge' style='background:""+ccr.bg+"";color:""+ccr.fg+""'>""+esc(v||'-')+""</span></td>""; }
			        return ""<td class='td-""+c.cls+""'>""+text+""</td>"";
			      }).join('') + ""</tr>"";
			    }).join('') + ""</tbody>"";
			    el.innerHTML=""<table class='tbl'>"" + head + body + ""</table>"";
			  }
			  function renderAll(){
			    if(!document.getElementById('kpiGrid')) return false;
			    try { buildKPIs(); renderRoscaCat(); renderTopMotivos(); renderEvolucao(); renderHierarchico(); renderCidades(); renderAtividades(); renderTabela(); return true; }
			    catch(e){ console.error(e); return false; }
			  }
			  var _prevHash='';
			  function dataHash(){
			    return ['jKpi','jMix','jMot','jEvo','jHc','jHp','jHv','jCd','jAtv','jTm','jTc','jTp','jTv','jTcd'].map(function(id){
			      var e=document.getElementById(id); if(!e) return '';
			      return e.textContent.length+'|'+e.textContent.slice(0,20);
			    }).join('~');
			  }
			  setInterval(function(){ var h=dataHash(); if(h!==_prevHash){ _prevHash=h; renderAll(); } }, 350);
			  var rt;
			  window.addEventListener('resize', function(){ clearTimeout(rt); rt=setTimeout(renderAll,120); });
			  function tryRender(a){ a=a||0; if(renderAll()) return; if(a<25) setTimeout(function(){ tryRender(a+1); }, 100); }
			  if(document.readyState==='loading'){ document.addEventListener('DOMContentLoaded', function(){ tryRender(); }); } else { tryRender(); }
			  window.addEventListener('load', function(){ tryRender(); });
			})();" & "</script>"
		displayFolder: HTML Devolucoes
		lineageTag: 7d863e1e-bf07-4d19-bece-82bff42c6fa7

	/// Dashboard HTML Content da pagina Devolucoes - layout completo + JSONs + chama _JS Devolucoes.
	measure 'HTML Devolucoes' =
			"<style>:root {
			  --bg:    #EEEAE2;
			  --surf:  #FFFFFF;
			  --surf2: #F7F3EB;
			  --bd:    rgba(26,26,26,.07);
			  --bd2:   rgba(26,26,26,.15);
			  --t1:    #1A1A1A;
			  --t2:    #5A5A5A;
			  --t3:    #8B8B8B;
			  --gold:  #B8935A;
			  --goldS: #EAD9BE;
			  --dark:  #1E1E1E;
			  --grn:   #4E7D62;
			  --org:   #C07C3A;
			  --blu:   #4A6E8A;
			  --red:   #A04848;
			  --sh1:   0 1px 3px rgba(0,0,0,.06);
			  --sh2:   0 2px 10px rgba(0,0,0,.1);
			  --r:     10px;
			  --ease:  cubic-bezier(.4,0,.2,1);
			}
			* { box-sizing: border-box; margin: 0; padding: 0; }
			html, body {
			  background: var(--bg);
			  font-family: 'Segoe UI', system-ui, sans-serif;
			  font-size: 14px; color: var(--t1);
			  -webkit-font-smoothing: antialiased;
			  min-height: 100vh;
			}
			.dash { padding: 14px 16px; display: flex; flex-direction: column; gap: 12px; }
			.hdr { display: flex; align-items: center; justify-content: space-between; padding: 0 2px; }
			.hdr-title { font-size: 25px; font-weight: 700; letter-spacing: -.5px; }
			.hdr-sub { font-size: 13px; color: var(--t3); margin-left: 8px; }
			.kpi-row { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; }
			.kpi { background: var(--surf); border-radius: var(--r); padding: 14px 16px; box-shadow: var(--sh1); border: 1px solid var(--bd); }
			.kpi-top { display: flex; align-items: flex-start; justify-content: space-between; gap: 8px; }
			.kpi-label { font-size: 12.5px; color: var(--t2); font-weight: 500; }
			.kpi-icon { width: 30px; height: 30px; border-radius: 8px; background: linear-gradient(135deg, var(--goldS), #F0E4CC); display: flex; align-items: center; justify-content: center; color: var(--gold); flex-shrink: 0; }
			.kpi-icon svg { width: 14px; height: 14px; }
			.kpi-val { font-size: 32px; font-weight: 700; letter-spacing: -.6px; line-height: 1.1; font-variant-numeric: tabular-nums; margin-top: 6px; }
			.kpi-sub { font-size: 12.5px; color: var(--t3); margin-top: 4px; }
			.kpi-sub .up { color: var(--grn); font-weight: 600; }
			.kpi-sub .down { color: var(--red); font-weight: 600; }
			.kpi-sub .neu { color: var(--gold); font-weight: 600; }
			.card { background: var(--surf); border-radius: var(--r); padding: 12px 14px; box-shadow: var(--sh1); border: 1px solid var(--bd); }
			.card-head { display: flex; align-items: flex-start; justify-content: space-between; margin-bottom: 10px; gap: 10px; flex-wrap: wrap; }
			.card-title { font-size: 16px; font-weight: 600; letter-spacing: -.2px; }
			.card-sub { font-size: 12px; color: var(--t3); margin-top: 1px; }
			.toggle-group { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
			.mini-toggle, .tri-toggle { display: flex; background: var(--surf2); border: 1px solid var(--bd2); border-radius: 100px; overflow: hidden; }
			.mini-toggle button, .tri-toggle button { padding: 5px 13px; font-size: 12px; font-weight: 600; border: none; background: transparent; color: var(--t2); cursor: pointer; font-family: inherit; transition: all .15s; }
			.mini-toggle button.on, .tri-toggle button.on { background: var(--dark); color: #fff; border-radius: 100px; }
			.two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; align-items: stretch; }
			.two-col > .card { display: flex; flex-direction: column; }
			.bars-list-scroll { display: flex; flex-direction: column; gap: 9px; max-height: 420px; overflow-y: auto; padding-right: 6px; }
			.bars-list-scroll::-webkit-scrollbar { width: 6px; }
			.bars-list-scroll::-webkit-scrollbar-track { background: rgba(26,26,26,.04); border-radius: 100px; }
			.bars-list-scroll::-webkit-scrollbar-thumb { background: var(--goldS); border-radius: 100px; }
			.bars-list-scroll::-webkit-scrollbar-thumb:hover { background: var(--gold); }
			.bar-row { cursor: default; }
			.bar-head { display: flex; justify-content: space-between; gap: 8px; margin-bottom: 4px; }
			.bar-name { font-size: 13px; color: #1A1A1A; font-weight: 500; flex: 1; min-width: 0; line-height: 1.4; }
			.bar-val { font-size: 13px; font-weight: 700; font-variant-numeric: tabular-nums; color: var(--t1); white-space: nowrap; }
			.bar-track { height: 6px; background: #EAD9BE; border-radius: 100px; overflow: hidden; }
			.bar-fill { height: 100%; border-radius: 100px; background: linear-gradient(90deg, #1A1A1A, var(--red)); width: 0; transition: width .8s var(--ease); }
			.cat-pill { display: inline-block; padding: 1px 8px; border-radius: 100px; font-size: 10.5px; font-weight: 700; letter-spacing: .2px; margin-right: 6px; vertical-align: middle; text-transform: uppercase; }
			.donut-card { display: flex; flex-direction: column; }
			.donut-svg-wrap { flex: 1; min-height: 320px; display: flex; }
			.donut-svg-wrap svg { width: 100%; height: 100%; display: block; }
			.donut-slice { transition: opacity .2s; cursor: pointer; }
			.donut-slice:hover { opacity: .85; }
			.chart-vert-wrap { overflow-x: auto; overflow-y: hidden; padding-bottom: 4px; }
			.chart-vert-wrap::-webkit-scrollbar { height: 8px; }
			.chart-vert-wrap::-webkit-scrollbar-track { background: rgba(26,26,26,.04); border-radius: 100px; }
			.chart-vert-wrap::-webkit-scrollbar-thumb { background: var(--goldS); border-radius: 100px; }
			.chart-vert-wrap::-webkit-scrollbar-thumb:hover { background: var(--gold); }
			.chart-vert-wrap svg .vbar { transition: opacity .2s; cursor: pointer; }
			.chart-vert-wrap svg .vbar:hover { opacity: .80; }
			.chart-vert-wrap svg .evo-pt { transition: r .2s, opacity .2s; cursor: pointer; }
			.chart-vert-wrap svg .evo-pt:hover { r: 7; }
			.tabs { display: flex; gap: 4px; background: var(--surf2); padding: 3px; border-radius: 100px; border: 1px solid var(--bd2); flex-wrap: wrap; }
			.tab { padding: 6px 15px; font-size: 12.5px; font-weight: 600; border: none; background: transparent; color: var(--t2); cursor: pointer; font-family: inherit; border-radius: 100px; transition: all .15s; }
			.tab.on { background: var(--dark); color: #fff; }
			.table-wrap { overflow-x: auto; max-height: 480px; overflow-y: auto; border-radius: 8px; }
			.tbl { width: 100%; border-collapse: collapse; font-size: 13px; }
			.tbl th { position: sticky; top: 0; background: var(--surf2); padding: 10px 12px; text-align: left; font-weight: 600; color: var(--t2); border-bottom: 1px solid var(--bd2); font-size: 12px; text-transform: uppercase; letter-spacing: .3px; z-index: 2; }
			.tbl th.th-num { text-align: right; }
			.tbl td { padding: 7px 10px; border-bottom: 1px solid var(--bd); vertical-align: middle; }
			.tbl tr:hover td { background: var(--surf2); }
			.tbl td.td-name { font-weight: 500; color: var(--t1); }
			.tbl td.td-tag { color: var(--t2); font-size: 12px; }
			.tbl td.td-num { text-align: right; font-variant-numeric: tabular-nums; font-weight: 600; color: var(--t1); min-width: 90px; }
			.cell-val { display: block; }
			.cell-bar { height: 3px; background: rgba(26,26,26,.04); border-radius: 100px; overflow: hidden; margin-top: 3px; }
			.cell-fill { height: 100%; background: linear-gradient(90deg, #1A1A1A, var(--red)); border-radius: 100px; }
			.tag-badge { display: inline-block; padding: 3px 10px; border-radius: 100px; font-size: 11.5px; font-weight: 600; letter-spacing: .2px; white-space: nowrap; }
			.tt { position: fixed; background: #1E1E1E; color: #fff; padding: 7px 12px; border-radius: 7px; font-size: 12.5px; pointer-events: none; opacity: 0; transition: opacity .15s; z-index: 9999; white-space: nowrap; box-shadow: 0 4px 20px rgba(0,0,0,.2); }
			.tt.on { opacity: 1; }
			.tt b { color: #D4B687; }
			</style>" &
			"<div class='dash'>
			  <div class='hdr'>
			    <div>
			      <span class='hdr-title'>Devoluções</span>
			      <span class='hdr-sub'>Onde está o gargalo e quem está envolvido</span>
			    </div>
			  </div>
			  <div class='kpi-row' id='kpiGrid'></div>
			  <div class='two-col'>
			    <div class='card donut-card'>
			      <div class='card-head'>
			        <div>
			          <div class='card-title'>Mix por Categoria</div>
			          <div class='card-sub'>Distribuição do R$ devolvido pelas áreas responsáveis</div>
			        </div>
			      </div>
			      <div class='donut-svg-wrap'><svg id='svgCat' preserveAspectRatio='xMidYMid meet'></svg></div>
			    </div>
			    <div class='card'>
			      <div class='card-head'>
			        <div>
			          <div class='card-title'>Top 10 Motivos</div>
			          <div class='card-sub'>Tipos específicos com maior impacto - tag indica a categoria</div>
			        </div>
			      </div>
			      <div class='bars-list-scroll' id='motivosList'></div>
			    </div>
			  </div>
			  <div class='card'>
			    <div class='card-head'>
			      <div>
			        <div class='card-title'>Evolução Mensal</div>
			        <div class='card-sub'>Série temporal das devoluções - escolha o indicador</div>
			      </div>
			      <div class='mini-toggle' id='evoModoToggle'>
			        <button class='on' data-m='val' onclick='setModoEvo(&quot;val&quot;)'>Valor R$</button>
			        <button data-m='peso' onclick='setModoEvo(&quot;peso&quot;)'>Peso</button>
			        <button data-m='taxa' onclick='setModoEvo(&quot;taxa&quot;)'>Taxa %</button>
			      </div>
			    </div>
			    <div class='chart-vert-wrap' id='evoChart'></div>
			  </div>
			  <div class='card'>
			    <div class='card-head'>
			      <div>
			        <div class='card-title'>Top 15 - Análise Hierárquica</div>
			        <div class='card-sub'>Quem mais devolveu - escolha o nível e a métrica</div>
			      </div>
			      <div class='toggle-group'>
			        <div class='tri-toggle' id='hierToggle'>
			          <button class='on' data-h='cliente' onclick='setModoHier(&quot;cliente&quot;)'>Cliente</button>
			          <button data-h='produto' onclick='setModoHier(&quot;produto&quot;)'>Produto</button>
			          <button data-h='vendedor' onclick='setModoHier(&quot;vendedor&quot;)'>Vendedor</button>
			        </div>
			        <div class='mini-toggle' id='hierModoToggle'>
			          <button class='on' data-m='rs' onclick='setModoHierMm(&quot;rs&quot;)'>Valor R$</button>
			          <button data-m='peso' onclick='setModoHierMm(&quot;peso&quot;)'>Peso</button>
			        </div>
			      </div>
			    </div>
			    <div class='chart-vert-wrap' id='hierChart'></div>
			  </div>
			  <div class='two-col'>
			    <div class='card'>
			      <div class='card-head'>
			        <div>
			          <div class='card-title'>Top Cidades com Devolução</div>
			          <div class='card-sub'>Onde acontecem as devoluções</div>
			        </div>
			        <div class='mini-toggle' id='cidModoToggle'>
			          <button class='on' data-m='rs' onclick='setModoCid(&quot;rs&quot;)'>R$</button>
			          <button data-m='peso' onclick='setModoCid(&quot;peso&quot;)'>Peso</button>
			        </div>
			      </div>
			      <div class='bars-list-scroll' id='cidList'></div>
			    </div>
			    <div class='card'>
			      <div class='card-head'>
			        <div>
			          <div class='card-title'>Top Atividades com Devolução</div>
			          <div class='card-sub'>Que perfil de cliente devolve mais</div>
			        </div>
			        <div class='mini-toggle' id='atvModoToggle'>
			          <button class='on' data-m='rs' onclick='setModoAtv(&quot;rs&quot;)'>R$</button>
			          <button data-m='peso' onclick='setModoAtv(&quot;peso&quot;)'>Peso</button>
			        </div>
			      </div>
			      <div class='bars-list-scroll' id='atvList'></div>
			    </div>
			  </div>
			  <div class='card'>
			    <div class='card-head'>
			      <div><div class='card-title'>Detalhamento</div><div class='card-sub'>Análise por dimensão - mini-barras nas colunas R$</div></div>
			      <div class='tabs' id='abasTabs'>
			        <button class='tab on' data-aba='motivo' onclick='setAba(&quot;motivo&quot;)'>Motivo</button>
			        <button class='tab' data-aba='cliente' onclick='setAba(&quot;cliente&quot;)'>Cliente</button>
			        <button class='tab' data-aba='produto' onclick='setAba(&quot;produto&quot;)'>Produto</button>
			        <button class='tab' data-aba='vendedor' onclick='setAba(&quot;vendedor&quot;)'>Vendedor</button>
			        <button class='tab' data-aba='cidade' onclick='setAba(&quot;cidade&quot;)'>Cidade</button>
			      </div>
			    </div>
			    <div class='table-wrap' id='tabelaBox'></div>
			  </div>
			</div>
			<div class='tt' id='tt'></div>" &
			"<script type='application/json' id='jKpi'>" & [_JSON KPIs Devolucoes] & "</script>" &
			"<script type='application/json' id='jMix'>" & [_JSON Mix Categoria Devolucoes] & "</script>" &
			"<script type='application/json' id='jMot'>" & [_JSON Top Motivos Devolucoes] & "</script>" &
			"<script type='application/json' id='jEvo'>" & [_JSON Evolucao Mensal Devolucoes] & "</script>" &
			"<script type='application/json' id='jHc'>"  & [_JSON Top Cliente Devolucoes] & "</script>" &
			"<script type='application/json' id='jHp'>"  & [_JSON Top Produto Devolucoes] & "</script>" &
			"<script type='application/json' id='jHv'>"  & [_JSON Top Vendedor Devolucoes] & "</script>" &
			"<script type='application/json' id='jCd'>"  & [_JSON Top Cidade Devolucoes] & "</script>" &
			"<script type='application/json' id='jAtv'>" & [_JSON Top Atividade Devolucoes] & "</script>" &
			"<script type='application/json' id='jTm'>"  & [_JSON Tabela Motivo Devolucoes] & "</script>" &
			"<script type='application/json' id='jTc'>"  & [_JSON Tabela Cliente Devolucoes] & "</script>" &
			"<script type='application/json' id='jTp'>"  & [_JSON Tabela Produto Devolucoes] & "</script>" &
			"<script type='application/json' id='jTv'>"  & [_JSON Tabela Vendedor Devolucoes] & "</script>" &
			"<script type='application/json' id='jTcd'>" & [_JSON Tabela Cidade Devolucoes] & "</script>" &
			[_JS Devolucoes]
		displayFolder: HTML Devolucoes
		lineageTag: ef5eb680-1510-471b-9049-e712a0a3aa94

	/// JSON com dados dos 4 KPIs da pagina Yuzap x ERP.
	measure '_JSON KPIs Yz' =
			"{""identificados"":" & COALESCE([Yuzap - Clientes Identificados], 0) &
			",""momIdentificados"":""" & COALESCE([Yuzap - MoM Clientes %], "--") & """" &
			",""convertidos"":" & COALESCE([Yuzap - Clientes Convertidos], 0) &
			",""perdidos"":" & COALESCE([Yuzap - Clientes Perdidos], 0) &
			",""conversao"":" & SUBSTITUTE(FORMAT(COALESCE([Yuzap - % Conversão], 0) * 100, "0.00"), ",", ".") &
			",""momConversao"":""" & COALESCE([Yuzap - MoM Conversão %], "--") & """" &
			",""fat"":" & SUBSTITUTE(FORMAT(COALESCE([Yuzap - Faturamento], 0), "0.00"), ",", ".") &
			",""momFat"":""" & COALESCE([Yuzap - MoM Faturamento %], "--") & """" &
			",""taxaDev"":" & SUBSTITUTE(FORMAT(COALESCE([Yuzap - Taxa Devolução %], 0) * 100, "0.00"), ",", ".") &
			",""momDev"":""" & COALESCE([Yuzap - MoM Devoluções %], "--") & """" &
			",""conversas"":" & COALESCE([Yuzap - Conversas], 0) &
			",""pedidos"":" & COALESCE([Yuzap - Pedidos], 0) &
			",""ticket"":" & SUBSTITUTE(FORMAT(COALESCE([Yuzap - Ticket Médio], 0), "0.00"), ",", ".") &
			"}"
		displayFolder: HTML Yuzap
		lineageTag: 28c246a4-9cf9-402a-9778-4e5c7c9b8d0c

	/// Dados do funil de conversao Yuzap. Etapas: Identificados -> Convertidos -> Recompraram (2+ pedidos) -> Sem Devolucao.
	measure '_JSON Funil Yz' =
			VAR _yz =
			    CALCULATETABLE(
			        VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			        NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			        F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			    )
			VAR _yzAsSeq = SELECTCOLUMNS(_yz, "x", VALUE(F_Yuzap_Conversas[data.attr_cdigo_cliente]))
			VAR _filtroERP = TREATAS(_yzAsSeq, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			VAR _identificados = COUNTROWS(_yz)
			VAR _convertidos =
			    CALCULATE(
			        DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]),
			        _filtroERP
			    )
			VAR _recorrentes =
			    CALCULATE(
			        COUNTROWS(
			            FILTER(
			                ADDCOLUMNS(
			                    VALUES(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]),
			                    "_p", [Total de Pedidos]
			                ),
			                [_p] >= 2
			            )
			        ),
			        _filtroERP
			    )
			VAR _semDev =
			    CALCULATE(
			        COUNTROWS(
			            FILTER(
			                ADDCOLUMNS(
			                    VALUES(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]),
			                    "_d", [Total Devoluções (R$)]
			                ),
			                COALESCE([_d], 0) = 0
			            )
			        ),
			        _filtroERP
			    )
			RETURN
			"[" &
			"{""nome"":""Identificados no Yuzap"",""val"":" & COALESCE(_identificados, 0) & ",""desc"":""Clientes com código no Yuzap""}," &
			"{""nome"":""Convertidos no ERP"",""val"":" & COALESCE(_convertidos, 0) & ",""desc"":""Compraram pelo menos 1x""}," &
			"{""nome"":""Recorrentes"",""val"":" & COALESCE(_recorrentes, 0) & ",""desc"":""Com 2+ pedidos""}," &
			"{""nome"":""Sem Devolução"",""val"":" & COALESCE(_semDev, 0) & ",""desc"":""Convertidos sem nenhuma devolução""}" &
			"]"
		displayFolder: HTML Yuzap
		lineageTag: ca500081-22cc-4105-aaf7-83c1a1e08d84

	/// Conversao por Label Yuzap. Para cada label, clientes distintos com esse label, quantos converteram no ERP, % conversao e faturamento.
	measure '_JSON Por Label Yz' =
			VAR _labels =
			    FILTER(
			        VALUES(F_Yuzap_Conversas[Labels]),
			        NOT(ISBLANK(F_Yuzap_Conversas[Labels])) &&
			        F_Yuzap_Conversas[Labels] <> ""
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _labels,
			        "_clientes",
			            CALCULATE(
			                DISTINCTCOUNT(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			                NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			                F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			            ),
			        "_convertidos",
			            VAR _seqs =
			                CALCULATETABLE(
			                    VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			                    NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			                    F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			                )
			            VAR _f = TREATAS(SELECTCOLUMNS(_seqs, "x", VALUE(F_Yuzap_Conversas[data.attr_cdigo_cliente])), DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			            RETURN CALCULATE(DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]), _f),
			        "_fat",
			            VAR _seqs =
			                CALCULATETABLE(
			                    VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			                    NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			                    F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			                )
			            VAR _f = TREATAS(SELECTCOLUMNS(_seqs, "x", VALUE(F_Yuzap_Conversas[data.attr_cdigo_cliente])), DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			            RETURN CALCULATE([Faturamento Total], _f)
			    )
			VAR _f = FILTER(_com, [_clientes] > 0)
			RETURN
			"[" & CONCATENATEX(
			    _f,
			    "{""label"":""" & SUBSTITUTE(SUBSTITUTE(F_Yuzap_Conversas[Labels], """""", ""), "\", "") &
			    """,""clientes"":" & COALESCE([_clientes], 0) &
			    ",""convertidos"":" & COALESCE([_convertidos], 0) &
			    ",""taxa"":" & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_convertidos], 0), COALESCE([_clientes], 0), 0) * 100, "0.00"), ",", ".") &
			    ",""fat"":" & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_clientes], DESC
			) & "]"
		displayFolder: HTML Yuzap
		lineageTag: b9a0601b-fe5b-400a-a24d-0380d438626d

	/// Lista dos clientes Yuzap perdidos (identificados mas sem venda no ERP). Inclui codigo, nome, telefone, qtd conversas, ultimo label, ultimo agente, data ultima conversa e dias desde a conversa.
	measure '_JSON Perdidos Yz' =
			VAR _yzAll =
			    CALCULATETABLE(
			        VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			        NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			        F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			    )
			VAR _erpClientes =
			    SELECTCOLUMNS(
			        VALUES(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]),
			        "x", FORMAT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE], "0")
			    )
			VAR _perdidos =
			    FILTER(
			        _yzAll,
			        NOT(F_Yuzap_Conversas[data.attr_cdigo_cliente] IN _erpClientes)
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _perdidos,
			        "_nome",       CALCULATE(MAX(F_Yuzap_Conversas[Nome Contato])),
			        "_tel",        CALCULATE(MAX(F_Yuzap_Conversas[telefone_contato])),
			        "_qtdConv",    CALCULATE(COUNTROWS(F_Yuzap_Conversas)),
			        "_ultData",    CALCULATE(MAX(F_Yuzap_Conversas[Data Atualizacao])),
			        "_ultLabel",
			            VAR _md = CALCULATE(MAX(F_Yuzap_Conversas[Data Atualizacao]))
			            RETURN CALCULATE(MAX(F_Yuzap_Conversas[Labels]), F_Yuzap_Conversas[Data Atualizacao] = _md),
			        "_ultAgente",
			            VAR _md = CALCULATE(MAX(F_Yuzap_Conversas[Data Atualizacao]))
			            RETURN CALCULATE(MAX(F_Yuzap_Conversas[Agente Responsavel]), F_Yuzap_Conversas[Data Atualizacao] = _md)
			    )
			VAR _hoje = TODAY()
			RETURN
			"[" & CONCATENATEX(
			    _com,
			    "{""codigo"":""" & SUBSTITUTE(SUBSTITUTE(F_Yuzap_Conversas[data.attr_cdigo_cliente], """""", ""), "\", "") &
			    """,""nome"":"""      & SUBSTITUTE(SUBSTITUTE(COALESCE([_nome], "-"), """""", ""), "\", "") &
			    """,""tel"":"""       & SUBSTITUTE(SUBSTITUTE(COALESCE([_tel], "-"), """""", ""), "\", "") &
			    """,""conversas"":"  & COALESCE([_qtdConv], 0) &
			    ",""label"":"""      & SUBSTITUTE(SUBSTITUTE(COALESCE([_ultLabel], "-"), """""", ""), "\", "") &
			    """,""agente"":"""   & SUBSTITUTE(SUBSTITUTE(COALESCE([_ultAgente], "-"), """""", ""), "\", "") &
			    """,""data"":"""     & IF(ISBLANK([_ultData]), "-", FORMAT([_ultData], "dd/MM/yyyy")) &
			    """,""dias"":"       & IF(ISBLANK([_ultData]), 0, INT(_hoje - [_ultData])) &
			    "}",
			    ",",
			    [_ultData], DESC
			) & "]"
		displayFolder: HTML Yuzap
		lineageTag: 41ec7b4a-b00f-474e-bd15-672d589303e8

	/// Evolucao mensal dos clientes Yuzap. v1 - ignora filtro de D_Calendario (mostra todos meses do dataset).
	measure '_JSON Evolucao Yz' =
			VAR _yz =
			    CALCULATETABLE(
			        VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			        NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			        F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			    )
			VAR _filtroERP = TREATAS(SELECTCOLUMNS(_yz, "x", VALUE(F_Yuzap_Conversas[data.attr_cdigo_cliente])), DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			VAR _meses =
			    CALCULATETABLE(
			        FILTER(
			            SUMMARIZE(D_Calendario, D_Calendario[Mês/Ano]),
			            CALCULATE([Faturamento Total], _filtroERP) > 0
			        ),
			        REMOVEFILTERS(D_Calendario)
			    )
			VAR _com =
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            _meses,
			            "_fat",     CALCULATE([Faturamento Total], _filtroERP),
			            "_peso",    CALCULATE([Peso Total Vendido], _filtroERP),
			            "_pedidos", CALCULATE([Total de Pedidos], _filtroERP),
			            "_dev",     CALCULATE([Total Devoluções (R$)], _filtroERP),
			            "_ordem",   CALCULATE(MIN(D_Calendario[Data]))
			        ),
			        REMOVEFILTERS(D_Calendario)
			    )
			VAR _ordenado = TOPN(24, _com, [_ordem], ASC)
			RETURN
			"[" & CONCATENATEX(
			    _ordenado,
			    "{""mes"":""" & SUBSTITUTE(D_Calendario[Mês/Ano], """""", "") &
			    """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""peso"":"      & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""pedidos"":"   & COALESCE([_pedidos], 0) &
			    ",""dev"":"       & SUBSTITUTE(FORMAT(COALESCE([_dev], 0), "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_ordem], ASC
			) & "]"
		displayFolder: HTML Yuzap
		lineageTag: e933d691-f878-48f3-b45f-431c3bcf148d

	/// Top produtos vendidos para clientes Yuzap. v2 - corrigido context transition em _clientes.
	measure '_JSON Top Produto Yz' =
			VAR _yz =
			    CALCULATETABLE(
			        VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			        NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			        F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			    )
			VAR _filtroERP = TREATAS(SELECTCOLUMNS(_yz, "x", VALUE(F_Yuzap_Conversas[data.attr_cdigo_cliente])), DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			VAR _produtos =
			    CALCULATETABLE(
			        FILTER(
			            VALUES(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO]),
			            NOT(ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO])) && DCVVQ_VENDAGERALTELEVENDAS[PRODUTO] <> ""
			        ),
			        _filtroERP
			    )
			VAR _com =
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            _produtos,
			            "_grupo",    CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO])),
			            "_fat",      CALCULATE([Faturamento Total]),
			            "_peso",     CALCULATE([Peso Total Vendido]),
			            "_dev",      CALCULATE([Total Devoluções (R$)]),
			            "_clientes", CALCULATE(DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]))
			        ),
			        _filtroERP
			    )
			VAR _topRS   = TOPN(50, FILTER(_com, [_fat] > 0),   [_fat], DESC)
			VAR _topPeso = TOPN(50, FILTER(_com, [_peso] > 0), [_peso], DESC)
			VAR _arrRS =
			    "[" & CONCATENATEX(
			        _topRS,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO], """""", ""), "\", "") &
			        """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""peso"":"      & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""grupo"":"""   & SUBSTITUTE(SUBSTITUTE(COALESCE([_grupo], "-"), """""", ""), "\", "") &
			        """,""clientes"":"& COALESCE([_clientes], 0) &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrPeso =
			    "[" & CONCATENATEX(
			        _topPeso,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO], """""", ""), "\", "") &
			        """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""rs"":"        & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""grupo"":"""   & SUBSTITUTE(SUBSTITUTE(COALESCE([_grupo], "-"), """""", ""), "\", "") &
			        """,""clientes"":"& COALESCE([_clientes], 0) &
			        "}",
			        ",",
			        [_peso], DESC
			    ) & "]"
			RETURN
			"{""rs"":" & _arrRS & ",""peso"":" & _arrPeso & "}"
		displayFolder: HTML Yuzap
		lineageTag: 028e9563-ec7e-44fc-a387-954b4521dee4

	/// Top vendedores que atenderam clientes Yuzap. v2 - corrigido context transition em _clientes.
	measure '_JSON Top Vendedor Yz' =
			VAR _yz =
			    CALCULATETABLE(
			        VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			        NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			        F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			    )
			VAR _filtroERP = TREATAS(SELECTCOLUMNS(_yz, "x", VALUE(F_Yuzap_Conversas[data.attr_cdigo_cliente])), DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			VAR _vendedores =
			    CALCULATETABLE(
			        FILTER(
			            VALUES(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR]),
			            NOT(ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR])) && DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR] <> ""
			        ),
			        _filtroERP
			    )
			VAR _com =
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            _vendedores,
			            "_supervisor", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[SUPERVISOR])),
			            "_fat",        CALCULATE([Faturamento Total]),
			            "_peso",       CALCULATE([Peso Total Vendido]),
			            "_dev",        CALCULATE([Total Devoluções (R$)]),
			            "_clientes",   CALCULATE(DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]))
			        ),
			        _filtroERP
			    )
			VAR _topRS   = TOPN(50, FILTER(_com, [_fat] > 0),   [_fat], DESC)
			VAR _topPeso = TOPN(50, FILTER(_com, [_peso] > 0), [_peso], DESC)
			VAR _arrRS =
			    "[" & CONCATENATEX(
			        _topRS,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR], """""", ""), "\", "") &
			        """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""peso"":"      & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""supervisor"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_supervisor], "-"), """""", ""), "\", "") &
			        """,""clientes"":"& COALESCE([_clientes], 0) &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrPeso =
			    "[" & CONCATENATEX(
			        _topPeso,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR], """""", ""), "\", "") &
			        """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""rs"":"        & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""supervisor"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_supervisor], "-"), """""", ""), "\", "") &
			        """,""clientes"":"& COALESCE([_clientes], 0) &
			        "}",
			        ",",
			        [_peso], DESC
			    ) & "]"
			RETURN
			"{""rs"":" & _arrRS & ",""peso"":" & _arrPeso & "}"
		displayFolder: HTML Yuzap
		lineageTag: fcc62b79-7617-4bd7-86cb-ef1729d4a211

	/// Top cidades dos clientes Yuzap. Toggle R$/Peso.
	measure '_JSON Top Cidade Yz' =
			VAR _yz =
			    CALCULATETABLE(
			        VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			        NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			        F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			    )
			VAR _filtroERP = TREATAS(SELECTCOLUMNS(_yz, "x", VALUE(F_Yuzap_Conversas[data.attr_cdigo_cliente])), DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			VAR _cidades =
			    CALCULATETABLE(
			        FILTER(
			            VALUES(DCVVQ_VENDAGERALTELEVENDAS[CIDADE]),
			            NOT(ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[CIDADE])) && DCVVQ_VENDAGERALTELEVENDAS[CIDADE] <> ""
			        ),
			        _filtroERP
			    )
			VAR _com =
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            _cidades,
			            "_uf",       CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[UF])),
			            "_fat",      CALCULATE([Faturamento Total]),
			            "_peso",     CALCULATE([Peso Total Vendido]),
			            "_clientes", CALCULATE(DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]))
			        ),
			        _filtroERP
			    )
			VAR _topRS   = TOPN(50, FILTER(_com, [_fat] > 0),   [_fat], DESC)
			VAR _topPeso = TOPN(50, FILTER(_com, [_peso] > 0), [_peso], DESC)
			VAR _arrRS =
			    "[" & CONCATENATEX(
			        _topRS,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CIDADE], """""", ""), "\", "") &
			        """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""peso"":"      & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""uf"":"""      & SUBSTITUTE(SUBSTITUTE(COALESCE([_uf], "-"), """""", ""), "\", "") &
			        """,""clientes"":"& COALESCE([_clientes], 0) &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrPeso =
			    "[" & CONCATENATEX(
			        _topPeso,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CIDADE], """""", ""), "\", "") &
			        """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""rs"":"        & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""uf"":"""      & SUBSTITUTE(SUBSTITUTE(COALESCE([_uf], "-"), """""", ""), "\", "") &
			        """,""clientes"":"& COALESCE([_clientes], 0) &
			        "}",
			        ",",
			        [_peso], DESC
			    ) & "]"
			RETURN
			"{""rs"":" & _arrRS & ",""peso"":" & _arrPeso & "}"
		displayFolder: HTML Yuzap
		lineageTag: b8e65519-5a32-4b69-ae77-17ae7a0674a2

	/// Top atividades dos clientes Yuzap. Toggle R$/Peso.
	measure '_JSON Top Atividade Yz' =
			VAR _yz =
			    CALCULATETABLE(
			        VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			        NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			        F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			    )
			VAR _filtroERP = TREATAS(SELECTCOLUMNS(_yz, "x", VALUE(F_Yuzap_Conversas[data.attr_cdigo_cliente])), DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			VAR _ativs =
			    CALCULATETABLE(
			        FILTER(
			            VALUES(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE]),
			            NOT(ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE])) && DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE] <> ""
			        ),
			        _filtroERP
			    )
			VAR _com =
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            _ativs,
			            "_fat",      CALCULATE([Faturamento Total]),
			            "_peso",     CALCULATE([Peso Total Vendido]),
			            "_clientes", CALCULATE(DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]))
			        ),
			        _filtroERP
			    )
			VAR _topRS   = FILTER(_com, [_fat] > 0)
			VAR _topPeso = FILTER(_com, [_peso] > 0)
			VAR _arrRS =
			    "[" & CONCATENATEX(
			        _topRS,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE], """""", ""), "\", "") &
			        """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""peso"":"      & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""clientes"":"& COALESCE([_clientes], 0) &
			        "}",
			        ",",
			        [_fat], DESC
			    ) & "]"
			VAR _arrPeso =
			    "[" & CONCATENATEX(
			        _topPeso,
			        "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE], """""", ""), "\", "") &
			        """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			        ",""rs"":"        & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			        ",""clientes"":"& COALESCE([_clientes], 0) &
			        "}",
			        ",",
			        [_peso], DESC
			    ) & "]"
			RETURN
			"{""rs"":" & _arrRS & ",""peso"":" & _arrPeso & "}"
		displayFolder: HTML Yuzap
		lineageTag: 04ff93c8-cfbe-4f10-b835-d149575b9b83

	/// Mix por Categoria de Devolucao dos clientes Yuzap. Para rosca.
	measure '_JSON Mix Categoria Dev Yz' =
			VAR _yz =
			    CALCULATETABLE(
			        VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			        NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			        F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			    )
			VAR _filtroERP = TREATAS(SELECTCOLUMNS(_yz, "x", VALUE(F_Yuzap_Conversas[data.attr_cdigo_cliente])), DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			VAR _cats =
			    CALCULATETABLE(
			        FILTER(
			            VALUES(DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução]),
			            NOT(ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução])) &&
			            DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução] <> "Sem tipo"
			        ),
			        _filtroERP
			    )
			VAR _com =
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            _cats,
			            "_dev",     CALCULATE([Total Devoluções (R$)]),
			            "_peso",    CALCULATE([Peso Total Devolvido]),
			            "_tipos",   CALCULATE(DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO]), DCVVQ_VENDAGERALTELEVENDAS[VLRDEVOLUCAO] > 0),
			            "_clientes",CALCULATE(DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]), DCVVQ_VENDAGERALTELEVENDAS[VLRDEVOLUCAO] > 0)
			        ),
			        _filtroERP
			    )
			VAR _f = FILTER(_com, [_dev] > 0)
			RETURN
			"[" & CONCATENATEX(
			    _f,
			    "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução], """""", ""), "\", "") &
			    """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_dev], 0), "0.00"), ",", ".") &
			    ",""peso"":"      & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""qtdTipos"":"  & COALESCE([_tipos], 0) &
			    ",""clientes"":" & COALESCE([_clientes], 0) &
			    "}",
			    ",",
			    [_dev], DESC
			) & "]"
		displayFolder: HTML Yuzap
		lineageTag: 7aa6e899-bb98-40c4-8abf-afa19854129a

	/// Top motivos de devolucao dos clientes Yuzap. JS faz slice 0,10.
	measure '_JSON Top Motivos Dev Yz' =
			VAR _yz =
			    CALCULATETABLE(
			        VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			        NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			        F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			    )
			VAR _filtroERP = TREATAS(SELECTCOLUMNS(_yz, "x", VALUE(F_Yuzap_Conversas[data.attr_cdigo_cliente])), DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			VAR _tipos =
			    CALCULATETABLE(
			        FILTER(
			            VALUES(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO]),
			            NOT(ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO])) && DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO] <> ""
			        ),
			        _filtroERP
			    )
			VAR _com =
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            _tipos,
			            "_categoria", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução])),
			            "_dev",       CALCULATE([Total Devoluções (R$)]),
			            "_peso",      CALCULATE([Peso Total Devolvido]),
			            "_clientes",  CALCULATE(DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]), DCVVQ_VENDAGERALTELEVENDAS[VLRDEVOLUCAO] > 0)
			        ),
			        _filtroERP
			    )
			VAR _top = TOPN(20, FILTER(_com, [_dev] > 0), [_dev], DESC)
			RETURN
			"[" & CONCATENATEX(
			    _top,
			    "{""nome"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO], """""", ""), "\", "") &
			    """,""categoria"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_categoria], "-"), """""", ""), "\", "") &
			    """,""val"":"     & SUBSTITUTE(FORMAT(COALESCE([_dev], 0), "0.00"), ",", ".") &
			    ",""peso"":"      & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""clientes"":"  & COALESCE([_clientes], 0) &
			    "}",
			    ",",
			    [_dev], DESC
			) & "]"
		displayFolder: HTML Yuzap
		lineageTag: 187178a4-7419-4e3c-9de5-42f8f2fc0687

	/// Tabela detalhada dos clientes Yuzap com FAT > 0 (apenas convertidos/recorrentes). Inclui status, qtd conversas Yuzap, fat, pedidos, devolucao, taxa dev, dias ultima compra.
	measure '_JSON Tabela Cliente Yz' =
			VAR _yz =
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            FILTER(
			                VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			                NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])) &&
			                F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			            ),
			            "_nome",     CALCULATE(MAX(F_Yuzap_Conversas[Nome Contato])),
			            "_qtdConv",  CALCULATE(COUNTROWS(F_Yuzap_Conversas)),
			            "_ultLabel",
			                VAR _md = CALCULATE(MAX(F_Yuzap_Conversas[Data Atualizacao]))
			                RETURN CALCULATE(MAX(F_Yuzap_Conversas[Labels]), F_Yuzap_Conversas[Data Atualizacao] = _md)
			        )
			    )
			VAR _hoje = TODAY()
			VAR _com =
			    ADDCOLUMNS(
			        _yz,
			        "_cidade",    CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[CIDADE]), TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])),
			        "_atividade", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE]), TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])),
			        "_clienteNome", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE]), TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])),
			        "_fat",       CALCULATE([Faturamento Total], TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])),
			        "_pedidos",   CALCULATE([Total de Pedidos],  TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])),
			        "_dev",       CALCULATE([Total Devoluções (R$)], TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])),
			        "_ultCompra", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[DATA]), TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]))
			    )
			VAR _comVenda = FILTER(_com, COALESCE([_fat], 0) > 0)
			VAR _ordenado = TOPN(220, _comVenda, [_fat], DESC, [_qtdConv], DESC)
			RETURN
			"[" & CONCATENATEX(
			    _ordenado,
			    "{""codigo"":""" & SUBSTITUTE(SUBSTITUTE(F_Yuzap_Conversas[data.attr_cdigo_cliente], """""", ""), "\", "") &
			    """,""cliente"":"""   & SUBSTITUTE(SUBSTITUTE(COALESCE([_clienteNome], [_nome], "-"), """""", ""), "\", "") &
			    """,""cidade"":"""    & SUBSTITUTE(SUBSTITUTE(COALESCE([_cidade], "-"), """""", ""), "\", "") &
			    """,""atividade"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_atividade], "-"), """""", ""), "\", "") &
			    """,""label"":"""     & SUBSTITUTE(SUBSTITUTE(COALESCE([_ultLabel], "-"), """""", ""), "\", "") &
			    """,""status"":"""    & IF([_pedidos] >= 2, "Recorrente", "Convertido") &
			    """,""conversas"":"  & COALESCE([_qtdConv], 0) &
			    ",""fat"":"          & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""pedidos"":"      & COALESCE([_pedidos], 0) &
			    ",""dev"":"          & SUBSTITUTE(FORMAT(COALESCE([_dev], 0), "0.00"), ",", ".") &
			    ",""taxaDev"":"      & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_dev], 0), COALESCE([_fat], 0) + COALESCE([_dev], 0), 0) * 100, "0.00"), ",", ".") &
			    ",""diasUltCompra"":" & IF(ISBLANK([_ultCompra]), -1, INT(_hoje - [_ultCompra])) &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Yuzap
		lineageTag: 1e2e956d-89a0-4690-9dcd-57447edfc397

	/// Tabela detalhada de produtos vendidos para clientes Yuzap. Top 100.
	measure '_JSON Tabela Produto Yz' =
			VAR _yz =
			    CALCULATETABLE(
			        VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			        NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			        F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			    )
			VAR _filtroERP = TREATAS(SELECTCOLUMNS(_yz, "x", VALUE(F_Yuzap_Conversas[data.attr_cdigo_cliente])), DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			VAR _produtos =
			    CALCULATETABLE(
			        FILTER(
			            VALUES(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO]),
			            NOT(ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO])) && DCVVQ_VENDAGERALTELEVENDAS[PRODUTO] <> ""
			        ),
			        _filtroERP
			    )
			VAR _com =
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            _produtos,
			            "_grupo",    CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[GRUPOPRODUTO])),
			            "_subgrupo", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[SUBGRUPOPROD])),
			            "_fat",      CALCULATE([Faturamento Total]),
			            "_peso",     CALCULATE([Peso Total Vendido]),
			            "_dev",      CALCULATE([Total Devoluções (R$)]),
			            "_clientes", CALCULATE(DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]))
			        ),
			        _filtroERP
			    )
			VAR _top = TOPN(100, FILTER(_com, [_fat] > 0), [_fat], DESC)
			RETURN
			"[" & CONCATENATEX(
			    _top,
			    "{""produto"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[PRODUTO], """""", ""), "\", "") &
			    """,""grupo"":"""    & SUBSTITUTE(SUBSTITUTE(COALESCE([_grupo], "-"), """""", ""), "\", "") &
			    """,""subgrupo"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_subgrupo], "-"), """""", ""), "\", "") &
			    """,""fat"":"        & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""peso"":"         & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""dev"":"          & SUBSTITUTE(FORMAT(COALESCE([_dev], 0), "0.00"), ",", ".") &
			    ",""clientes"":"     & COALESCE([_clientes], 0) &
			    ",""taxaDev"":"      & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_dev], 0), COALESCE([_fat], 0) + COALESCE([_dev], 0), 0) * 100, "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Yuzap
		lineageTag: 1339dc14-d5e6-4d1b-ba68-bb38906333b0

	/// Tabela detalhada de vendedores que atenderam clientes Yuzap.
	measure '_JSON Tabela Vendedor Yz' =
			VAR _yz =
			    CALCULATETABLE(
			        VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			        NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			        F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			    )
			VAR _filtroERP = TREATAS(SELECTCOLUMNS(_yz, "x", VALUE(F_Yuzap_Conversas[data.attr_cdigo_cliente])), DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			VAR _vendedores =
			    CALCULATETABLE(
			        FILTER(
			            VALUES(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR]),
			            NOT(ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR])) && DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR] <> ""
			        ),
			        _filtroERP
			    )
			VAR _com =
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            _vendedores,
			            "_supervisor", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[SUPERVISOR])),
			            "_gerente",    CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[GERENTE])),
			            "_fat",        CALCULATE([Faturamento Total]),
			            "_peso",       CALCULATE([Peso Total Vendido]),
			            "_dev",        CALCULATE([Total Devoluções (R$)]),
			            "_pedidos",    CALCULATE([Total de Pedidos]),
			            "_clientes",   CALCULATE(DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]))
			        ),
			        _filtroERP
			    )
			VAR _f = FILTER(_com, [_fat] > 0)
			RETURN
			"[" & CONCATENATEX(
			    _f,
			    "{""vendedor"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[VENDEDOR], """""", ""), "\", "") &
			    """,""supervisor"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_supervisor], "-"), """""", ""), "\", "") &
			    """,""gerente"":"""  & SUBSTITUTE(SUBSTITUTE(COALESCE([_gerente], "-"), """""", ""), "\", "") &
			    """,""fat"":"          & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""peso"":"           & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""pedidos"":"        & COALESCE([_pedidos], 0) &
			    ",""clientes"":"       & COALESCE([_clientes], 0) &
			    ",""dev"":"            & SUBSTITUTE(FORMAT(COALESCE([_dev], 0), "0.00"), ",", ".") &
			    ",""taxaDev"":"        & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_dev], 0), COALESCE([_fat], 0) + COALESCE([_dev], 0), 0) * 100, "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Yuzap
		lineageTag: 140fea02-cacb-4d6c-b698-bf1ec49430b5

	/// Tabela detalhada de cidades dos clientes Yuzap.
	measure '_JSON Tabela Cidade Yz' =
			VAR _yz =
			    CALCULATETABLE(
			        VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			        NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			        F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			    )
			VAR _filtroERP = TREATAS(SELECTCOLUMNS(_yz, "x", VALUE(F_Yuzap_Conversas[data.attr_cdigo_cliente])), DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			VAR _cidades =
			    CALCULATETABLE(
			        FILTER(
			            VALUES(DCVVQ_VENDAGERALTELEVENDAS[CIDADE]),
			            NOT(ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[CIDADE])) && DCVVQ_VENDAGERALTELEVENDAS[CIDADE] <> ""
			        ),
			        _filtroERP
			    )
			VAR _com =
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            _cidades,
			            "_uf",       CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[UF])),
			            "_fat",      CALCULATE([Faturamento Total]),
			            "_peso",     CALCULATE([Peso Total Vendido]),
			            "_dev",      CALCULATE([Total Devoluções (R$)]),
			            "_pedidos",  CALCULATE([Total de Pedidos]),
			            "_clientes", CALCULATE(DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]))
			        ),
			        _filtroERP
			    )
			VAR _top = TOPN(50, FILTER(_com, [_fat] > 0), [_fat], DESC)
			RETURN
			"[" & CONCATENATEX(
			    _top,
			    "{""cidade"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[CIDADE], """""", ""), "\", "") &
			    """,""uf"":"""     & SUBSTITUTE(SUBSTITUTE(COALESCE([_uf], "-"), """""", ""), "\", "") &
			    """,""fat"":"     & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""peso"":"      & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""pedidos"":"   & COALESCE([_pedidos], 0) &
			    ",""clientes"":"  & COALESCE([_clientes], 0) &
			    ",""dev"":"       & SUBSTITUTE(FORMAT(COALESCE([_dev], 0), "0.00"), ",", ".") &
			    ",""taxaDev"":"   & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_dev], 0), COALESCE([_fat], 0) + COALESCE([_dev], 0), 0) * 100, "0.00"), ",", ".") &
			    "}",
			    ",",
			    [_fat], DESC
			) & "]"
		displayFolder: HTML Yuzap
		lineageTag: 7364f4d0-b5db-41b1-a785-66e3ba61446d

	/// Tabela detalhada de motivos de devolucao dos clientes Yuzap.
	measure '_JSON Tabela Motivo Yz' =
			VAR _yz =
			    CALCULATETABLE(
			        VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			        NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])),
			        F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			    )
			VAR _filtroERP = TREATAS(SELECTCOLUMNS(_yz, "x", VALUE(F_Yuzap_Conversas[data.attr_cdigo_cliente])), DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			VAR _tipos =
			    CALCULATETABLE(
			        FILTER(
			            VALUES(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO]),
			            NOT(ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO])) && DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO] <> ""
			        ),
			        _filtroERP
			    )
			VAR _com =
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            _tipos,
			            "_categoria", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução])),
			            "_dev",       CALCULATE([Total Devoluções (R$)]),
			            "_peso",      CALCULATE([Peso Total Devolvido]),
			            "_qtdLinhas", CALCULATE(COUNTROWS(DCVVQ_VENDAGERALTELEVENDAS), DCVVQ_VENDAGERALTELEVENDAS[VLRDEVOLUCAO] > 0),
			            "_clientes",  CALCULATE(DISTINCTCOUNT(DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE]), DCVVQ_VENDAGERALTELEVENDAS[VLRDEVOLUCAO] > 0)
			        ),
			        _filtroERP
			    )
			VAR _f = FILTER(_com, [_dev] > 0)
			RETURN
			"[" & CONCATENATEX(
			    _f,
			    "{""motivo"":""" & SUBSTITUTE(SUBSTITUTE(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO], """""", ""), "\", "") &
			    """,""categoria"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_categoria], "-"), """""", ""), "\", "") &
			    """,""dev"":"    & SUBSTITUTE(FORMAT(COALESCE([_dev], 0), "0.00"), ",", ".") &
			    ",""peso"":"     & SUBSTITUTE(FORMAT(COALESCE([_peso], 0), "0.00"), ",", ".") &
			    ",""qtdLinhas"":" & COALESCE([_qtdLinhas], 0) &
			    ",""clientes"":" & COALESCE([_clientes], 0) &
			    "}",
			    ",",
			    [_dev], DESC
			) & "]"
		displayFolder: HTML Yuzap
		lineageTag: 4603095f-1559-4d1e-9444-05cb69cfd6e1

	/// JavaScript da pagina Yuzap x ERP. Renderiza: KPIs, Funil, Por Label, Perdidos, Evolucao, Top Hierarquico (Produto/Vendedor), Bar List (Cidade/Atividade), Rosca Cat Dev, Top Motivos, Tabela 5 abas.
	measure '_JS Yz' =
			"<script>" & "(function () {
			  'use strict';
			  function rJ(id) { var e = document.getElementById(id); try { return JSON.parse((e && e.textContent) || 'null'); } catch (ex) { return null; } }
			  function esc(v) { return String(v == null ? '' : v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
			  function escT(v) { return esc(v).replace(/'/g,'&#39;'); }
			  function fN(v) { return (Number(v) || 0).toLocaleString('pt-BR'); }
			  function fA(v) { v = Number(v) || 0; if (Math.abs(v) >= 1e6) return (v/1e6).toFixed(1).replace('.',',') + ' M'; if (Math.abs(v) >= 1e3) return (v/1e3).toFixed(1).replace('.',',') + ' mil'; return fN(v); }
			  function fM(v) { v = Number(v) || 0; return 'R$ ' + v.toLocaleString('pt-BR', {minimumFractionDigits:2, maximumFractionDigits:2}); }
			  function fMK(v) { v = Number(v) || 0; if (Math.abs(v) >= 1e6) return 'R$ ' + (v/1e6).toFixed(2).replace('.',',') + ' M'; if (Math.abs(v) >= 1e3) return 'R$ ' + (v/1e3).toFixed(1).replace('.',',') + ' mil'; return fM(v); }
			  function fPct(v) { return (Number(v)||0).toFixed(2).replace('.',',') + '%'; }
			  function momCls(s) { if (!s || s === '--') return 'neu'; return s.indexOf('+') === 0 ? 'up' : (s.indexOf('-') === 0 ? 'down' : 'neu'); }
			  function svgDim(el, fbW, fbH) { var bb = el.getBoundingClientRect(); return [Math.round(bb.width) || fbW, Math.round(bb.height) || fbH]; }
			  function tagColor(str) {
			    if (!str) return {bg:'rgba(139,139,139,.12)',fg:'#5A5A5A'};
			    var h=0; for (var i=0;i<str.length;i++) h = ((h<<5)-h) + str.charCodeAt(i);
			    var palette = [{bg:'rgba(184,147,90,.15)',fg:'#8A6740'},{bg:'rgba(78,125,98,.15)',fg:'#3D6049'},{bg:'rgba(74,110,138,.15)',fg:'#3A5872'},{bg:'rgba(192,124,58,.15)',fg:'#995F2C'},{bg:'rgba(58,36,16,.12)',fg:'#3A2410'},{bg:'rgba(90,90,90,.15)',fg:'#5A5A5A'}];
			    return palette[Math.abs(h) % palette.length];
			  }
			  function statusBadge(s){ if(s==='Convertido') return {bg:'rgba(78,125,98,.18)',fg:'#3D6049'}; if(s==='Recorrente') return {bg:'rgba(184,147,90,.20)',fg:'#8A6740'}; return {bg:'rgba(160,72,72,.15)',fg:'#A04848'}; }
			  function catColor(c){ if(c && c.indexOf('Comercial')===0) return {bg:'rgba(74,110,138,.18)',fg:'#3A5872'}; if(c && c.indexOf('Qualidade')===0) return {bg:'rgba(160,72,72,.16)',fg:'#A04848'}; if(c && (c.indexOf('Logistica')===0||c.indexOf('Log')===0)) return {bg:'rgba(192,124,58,.18)',fg:'#995F2C'}; if(c && (c.indexOf('Industria')===0||c.indexOf('Ind')===0)) return {bg:'rgba(78,125,98,.18)',fg:'#3D6049'}; return tagColor(c); }
			  var ttEl = document.getElementById('tt');
			  window.tip = function(e,h){ if (!ttEl) return; ttEl.innerHTML = h; ttEl.classList.add('on'); var ww=window.innerWidth, x=e.clientX+14; if(x+260>ww) x=ww-280; ttEl.style.left = x+'px'; ttEl.style.top = (e.clientY-36)+'px'; };
			  window.tipOff = function(){ ttEl && ttEl.classList.remove('on'); };
			  var kpiIcons = {
			    users: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><path d='M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2'/><circle cx='9' cy='7' r='4'/><path d='M23 21v-2a4 4 0 0 0-3-3.87'/><path d='M16 3.13a4 4 0 0 1 0 7.75'/></svg>"",
			    target: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><circle cx='12' cy='12' r='10'/><circle cx='12' cy='12' r='6'/><circle cx='12' cy='12' r='2'/></svg>"",
			    money: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><line x1='12' y1='1' x2='12' y2='23'/><path d='M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6'/></svg>"",
			    alert: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><path d='M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z'/><line x1='12' y1='9' x2='12' y2='13'/><line x1='12' y1='17' x2='12.01' y2='17'/></svg>""
			  };
			  function buildKPIs(){
			    var K=rJ('jKpi')||{}; var el=document.getElementById('kpiGrid'); if(!el) return;
			    var cards=[
			      {icon:'users',  label:'Clientes Identificados', val:fN(K.identificados||0), sub:'<span>'+fN(K.conversas||0)+' conversas no Yuzap</span>'},
			      {icon:'target', label:'% Conversao Yuzap->ERP', val:fPct(K.conversao||0),   sub:'<span>'+fN(K.convertidos||0)+' convertidos / '+fN(K.perdidos||0)+' perdidos</span>'},
			      {icon:'money',  label:'Faturamento Gerado',     val:fMK(K.fat||0),          sub:'MoM = <span class=\\''+momCls(K.momFat)+'\\'>'+(K.momFat||'-')+'</span>'},
			      {icon:'alert',  label:'Taxa de Devolucao',      val:fPct(K.taxaDev||0),     sub:'MoM = <span class=\\''+momCls(K.momDev)+'\\'>'+(K.momDev||'-')+'</span>'}
			    ];
			    el.innerHTML=cards.map(function(c){ return ""<div class='kpi'><div class='kpi-top'><span class='kpi-label'>""+c.label+""</span><div class='kpi-icon'>""+kpiIcons[c.icon]+""</div></div><div class='kpi-val'>""+c.val+""</div><div class='kpi-sub'>""+c.sub+""</div></div>""; }).join('');
			  }
			  function renderFunil(){
			    var el=document.getElementById('funilBox'); if(!el) return;
			    var data=rJ('jFn')||[]; if(!data.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Number(data[0].val)||1;
			    el.innerHTML=data.map(function(d,i){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      var pct=i===0?100:(v/(Number(data[0].val)||1))*100;
			      var pctTxt=pct.toFixed(1).replace('.',',')+'%';
			      var colors=['#1A1A1A','#4E7D62','#B8935A','#4A6E8A'];
			      var c=colors[i % colors.length];
			      var tt='<b>'+escT(d.nome)+'</b><br>'+escT(d.desc)+'<br>Total: '+fN(v)+'<br>'+pctTxt+' do topo do funil';
			      return ""<div class='funil-row' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'><div class='funil-head'><div class='funil-name'>""+esc(d.nome)+"" <span class='funil-desc'>""+esc(d.desc)+""</span></div><div class='funil-val'>""+fN(v)+"" <span class='funil-pct'>(""+pctTxt+"")</span></div></div><div class='funil-track'><div class='funil-fill' data-w='""+w+""' style='background:""+c+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.funil-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  function renderPorLabel(){
			    var el=document.getElementById('porLabelBox'); if(!el) return;
			    var data=rJ('jLb')||[]; if(!data.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mxFat=Math.max.apply(null,data.map(function(d){return Number(d.fat)||0;}).concat([1]));
			    var mxCli=Math.max.apply(null,data.map(function(d){return Number(d.clientes)||0;}).concat([1]));
			    var head=""<thead><tr><th class='th-name'>Label Yuzap</th><th class='th-num'>Clientes</th><th class='th-num'>Convertidos</th><th class='th-num'>% Conv.</th><th class='th-num'>Faturamento</th></tr></thead>"";
			    var body=""<tbody>""+data.map(function(d){
			      var cli=Number(d.clientes)||0, conv=Number(d.convertidos)||0, taxa=Number(d.taxa)||0, fat=Number(d.fat)||0;
			      var wCli=(cli/mxCli)*100, wFat=(fat/mxFat)*100;
			      var taxaCls = taxa>=70?'pct-hi':(taxa>=30?'pct-md':'pct-lo');
			      var clr=tagColor(d.label);
			      return ""<tr><td class='td-tag'><span class='tag-badge' style='background:""+clr.bg+"";color:""+clr.fg+""'>""+esc(d.label)+""</span></td><td class='td-num'><div class='cell-val'>""+fN(cli)+""</div><div class='cell-bar'><div class='cell-fill' style='width:""+wCli.toFixed(1)+""%'></div></div></td><td class='td-num'>""+fN(conv)+""</td><td class='td-num ""+taxaCls+""'>""+fPct(taxa)+""</td><td class='td-num'><div class='cell-val'>""+fMK(fat)+""</div><div class='cell-bar'><div class='cell-fill' style='width:""+wFat.toFixed(1)+""%'></div></div></td></tr>"";
			    }).join('')+""</tbody>"";
			    el.innerHTML=""<table class='tbl'>""+head+body+""</table>"";
			  }
			  var _perdPg=0, _perdPSize=20;
			  window.setPerdPg=function(dir){ var data=rJ('jPe')||[]; var maxPg=Math.max(0,Math.ceil(data.length/_perdPSize)-1); _perdPg=Math.max(0,Math.min(maxPg,_perdPg+dir)); renderPerdidos(); };
			  function renderPerdidos(){
			    var el=document.getElementById('perdidosBox'); if(!el) return;
			    var data=rJ('jPe')||[]; if(!data.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem clientes perdidos</div>""; return; }
			    var total=data.length, maxPg=Math.max(0,Math.ceil(total/_perdPSize)-1);
			    if(_perdPg>maxPg) _perdPg=maxPg;
			    var start=_perdPg*_perdPSize, end=Math.min(start+_perdPSize,total);
			    var page=data.slice(start,end);
			    var head=""<thead><tr><th class='th-name'>Cliente</th><th class='th-name'>Codigo</th><th class='th-name'>Telefone</th><th class='th-num'>Conversas</th><th class='th-name'>Ultimo Label</th><th class='th-name'>Agente</th><th class='th-name'>Ultima Atividade</th><th class='th-num'>Dias</th></tr></thead>"";
			    var body=""<tbody>""+page.map(function(d){
			      var clr=tagColor(d.label);
			      var dias=Number(d.dias)||0;
			      var diasCls=dias>30?'pct-lo':(dias>7?'pct-md':'pct-hi');
			      return ""<tr><td class='td-name'>""+esc(d.nome)+""</td><td class='td-mono'>""+esc(d.codigo)+""</td><td class='td-mono'>""+esc(d.tel)+""</td><td class='td-num'>""+fN(d.conversas)+""</td><td class='td-tag'><span class='tag-badge' style='background:""+clr.bg+"";color:""+clr.fg+""'>""+esc(d.label||'-')+""</span></td><td class='td-name'>""+esc(d.agente)+""</td><td class='td-name'>""+esc(d.data)+""</td><td class='td-num ""+diasCls+""'>""+fN(dias)+""</td></tr>"";
			    }).join('')+""</tbody>"";
			    var pager=""<div class='pager'><button ""+(_perdPg===0?'disabled':'')+"" onclick='setPerdPg(-1)'>< Anterior</button><span>Pagina ""+(_perdPg+1)+"" de ""+(maxPg+1)+"" - mostrando ""+(start+1)+""-""+end+"" de ""+total+"" perdidos</span><button ""+(_perdPg>=maxPg?'disabled':'')+"" onclick='setPerdPg(1)'>Proximo ></button></div>"";
			    el.innerHTML=""<table class='tbl tbl-compact'>""+head+body+""</table>""+pager;
			  }
			  var _modoEvo='val';
			  window.setModoEvo=function(m){ _modoEvo=m; document.querySelectorAll('#evoModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderEvolucao(); };
			  function renderEvolucao(){
			    var el=document.getElementById('svgEvo'); if(!el) return;
			    var d=svgDim(el,900,300); var W=d[0],H=d[1];
			    el.setAttribute('viewBox','0 0 '+W+' '+H);
			    var data=rJ('jEv')||[]; if(!data.length){ el.innerHTML=""<text x='""+(W/2)+""' y='""+(H/2)+""' text-anchor='middle' fill='#999'>Sem dados</text>""; return; }
			    var P={t:34,r:34,b:50,l:64};
			    var n=data.length;
			    var vals=data.map(function(r){ return Number(r[_modoEvo])||0; });
			    var mx=Math.max.apply(null,vals.concat([1]))*1.18;
			    var stepX=(W-P.l-P.r)/Math.max(1,n-1);
			    var fmtV = _modoEvo==='val'||_modoEvo==='dev'? fMK : (_modoEvo==='peso'? function(v){return fA(v)+' kg';} : fN);
			    var labels={val:'Faturamento',peso:'Peso',pedidos:'Pedidos',dev:'Devolucao'};
			    var color = _modoEvo==='dev' ? '#A04848' : '#B8935A';
			    var svg='';
			    for(var i=0;i<=4;i++){
			      var y=P.t+(H-P.t-P.b)*i/4;
			      var v=mx*(1-i/4);
			      svg+=""<line x1='""+P.l+""' x2='""+(W-P.r)+""' y1='""+y.toFixed(1)+""' y2='""+y.toFixed(1)+""' stroke='rgba(0,0,0,.06)' stroke-dasharray='3,4'/>"";
			      if(i<4) svg+=""<text x='""+(P.l-6)+""' y='""+(y+4).toFixed(1)+""' text-anchor='end' fill='#8B8B8B' style='font-size:12px;font-family:Segoe UI,system-ui'>""+fA(v)+""</text>"";
			    }
			    var pts=data.map(function(r,i){ var x=P.l+i*stepX; var v=Number(r[_modoEvo])||0; var y=P.t+(H-P.t-P.b)*(1-v/mx); return {x:x,y:y,v:v,r:r}; });
			    var path = pts.map(function(p,i){ return (i===0?'M':'L')+p.x.toFixed(1)+' '+p.y.toFixed(1); }).join(' ');
			    var area = path + ' L '+pts[pts.length-1].x.toFixed(1)+' '+(H-P.b)+' L '+pts[0].x.toFixed(1)+' '+(H-P.b)+' Z';
			    var uid='ev'+Math.floor(Math.random()*99999);
			    svg+=""<defs><linearGradient id='""+uid+""' x1='0' y1='0' x2='0' y2='1'><stop offset='0%' stop-color='""+color+""' stop-opacity='.25'/><stop offset='100%' stop-color='""+color+""' stop-opacity='0'/></linearGradient></defs>"";
			    svg+=""<path d='""+area+""' fill='url(#""+uid+"")'/>"";
			    svg+=""<path d='""+path+""' fill='none' stroke='""+color+""' stroke-width='2.5'/>"";
			    pts.forEach(function(p){
			      var tt='<b>'+escT(p.r.mes)+'</b><br>Faturamento: '+fMK(p.r.val)+'<br>Peso: '+fA(p.r.peso)+' kg<br>Pedidos: '+fN(p.r.pedidos)+'<br>Devolucao: '+fMK(p.r.dev);
			      svg+=""<circle cx='""+p.x.toFixed(1)+""' cy='""+p.y.toFixed(1)+""' r='4' fill='#fff' stroke='""+color+""' stroke-width='2' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'/>"";
			      svg+=""<text x='""+p.x.toFixed(1)+""' y='""+(p.y-10).toFixed(1)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:10.5px;font-weight:700;font-family:Segoe UI,system-ui;pointer-events:none'>""+fmtV(p.v)+""</text>"";
			    });
			    var labelStep=Math.max(1,Math.ceil(n/12));
			    pts.forEach(function(p,i){ if(i%labelStep!==0 && i!==n-1) return; svg+=""<text x='""+p.x.toFixed(1)+""' y='""+(H-P.b+18)+""' text-anchor='middle' fill='#5A5A5A' style='font-size:11.5px;font-family:Segoe UI,system-ui'>""+esc(p.r.mes)+""</text>""; });
			    svg+=""<text x='""+P.l+""' y='""+(P.t-10)+""' fill='#5A5A5A' style='font-size:11.5px;font-family:Segoe UI,system-ui;font-weight:600'>""+labels[_modoEvo]+""</text>"";
			    el.innerHTML=svg;
			  }
			  var _modoH='produto', _modoHM='rs';
			  window.setModoH=function(m){ _modoH=m; document.querySelectorAll('#hierToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.h===m); }); renderHier(); };
			  window.setModoHM=function(m){ _modoHM=m; document.querySelectorAll('#hierMToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderHier(); };
			  function renderHier(){
			    var el=document.getElementById('hierBox'); if(!el) return;
			    var src={produto:'jHp',vendedor:'jHv'};
			    var data=rJ(src[_modoH])||{rs:[],peso:[]};
			    var arr=(data[_modoHM]||[]).slice(0,15);
			    if(!arr.length){ el.innerHTML=""<div style='padding:30px;color:#8B8B8B;text-align:center'>Sem dados</div>""; return; }
			    var H=460;
			    var P={t:38,r:24,b:108,l:68};
			    var n=arr.length;
			    var containerW=el.clientWidth||900;
			    var availW=containerW-P.l-P.r;
			    var minBarW=30,maxBarW=56,defaultGap=18,maxGap=40;
			    var idealBarW=(availW-(n-1)*defaultGap)/Math.max(n,1);
			    var barW,gap,contentW,startX;
			    if(idealBarW>=maxBarW){ barW=maxBarW; var rem=availW-n*barW; gap=n>1?Math.min(maxGap,rem/(n-1)):0; var tw=n*barW+(n-1)*gap; startX=P.l+Math.max(0,(availW-tw)/2); contentW=containerW; }
			    else if(idealBarW>=minBarW){ barW=idealBarW; gap=defaultGap; startX=P.l; contentW=containerW; }
			    else { barW=minBarW; gap=defaultGap; startX=P.l; contentW=n*barW+(n-1)*gap+P.l+P.r; }
			    var W=Math.max(contentW,containerW);
			    var mx=Math.max.apply(null,arr.map(function(d){return Number(d.val)||0;}).concat([1]))*1.14;
			    var fmtV=_modoHM==='rs'? fMK : function(v){return fA(v)+' kg';};
			    var lblFn=_modoHM==='rs'?'Faturamento':'Peso';
			    var uid='b'+Math.floor(Math.random()*99999);
			    var maxWC=barW<40?10:14;
			    var svg=""<defs><linearGradient id='bg""+uid+""' x1='0%' y1='0%' x2='0%' y2='100%'><stop offset='0%' stop-color='#B8935A' stop-opacity='1'/><stop offset='100%' stop-color='#1A1A1A' stop-opacity='1'/></linearGradient></defs>"";
			    for(var i=0;i<=4;i++){ var y=P.t+(H-P.t-P.b)*i/4; var v=mx*(1-i/4); svg+=""<line x1='""+P.l+""' x2='""+(W-P.r)+""' y1='""+y.toFixed(1)+""' y2='""+y.toFixed(1)+""' stroke='rgba(0,0,0,.06)' stroke-dasharray='3,4'/>""; if(i<4) svg+=""<text x='""+(P.l-6)+""' y='""+(y+4).toFixed(1)+""' text-anchor='end' fill='#8B8B8B' style='font-size:12.5px;font-family:Segoe UI,system-ui;font-weight:500'>""+fA(v)+""</text>""; }
			    arr.forEach(function(d,i){
			      var v=Number(d.val)||0;
			      var bh=Math.max(2,(v/mx)*(H-P.t-P.b));
			      var bx=startX+i*(barW+gap);
			      var by=H-P.b-bh;
			      var lx=bx+barW/2;
			      var sub = _modoH==='produto'? (d.grupo||'-') : (d.supervisor||'-');
			      var tt='<b>'+escT(d.nome)+'</b><br>'+lblFn+': '+fmtV(v)+'<br>'+(_modoHM==='rs'?'Peso: '+fA(d.peso||0)+' kg':'Faturamento: '+fMK(d.rs||0))+'<br>Clientes: '+fN(d.clientes||0)+'<br>'+(_modoH==='produto'?'Grupo: ':'Supervisor: ')+escT(sub);
			      svg+=""<rect class='vbar' x='""+bx.toFixed(1)+""' y='""+by.toFixed(1)+""' width='""+barW.toFixed(1)+""' height='""+bh.toFixed(1)+""' rx='3' fill='url(#bg""+uid+"")' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'/>"";
			      svg+=""<text x='""+lx.toFixed(1)+""' y='""+(by-8).toFixed(1)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:11.5px;font-weight:700;font-variant-numeric:tabular-nums;font-family:Segoe UI,system-ui;pointer-events:none'>""+(_modoHM==='rs'?'R$ '+fA(v):fA(v))+""</text>"";
			      var words=d.nome.split(/\\s+/);
			      var dw=words.slice(0,4).map(function(w){return w.length>maxWC?w.slice(0,maxWC-2)+'..':w;});
			      var ny=H-P.b+16;
			      dw.forEach(function(w,j){ svg+=""<text x='""+lx.toFixed(1)+""' y='""+(ny+j*14)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:11.5px;font-weight:500;font-family:Segoe UI,system-ui'>""+esc(w)+""</text>""; });
			    });
			    el.innerHTML=""<svg width='""+W+""' height='""+H+""' xmlns='http://www.w3.org/2000/svg'>""+svg+""</svg>"";
			  }
			  var _modoCd='rs';
			  window.setModoCd=function(m){ _modoCd=m; document.querySelectorAll('#cdModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderCidades(); };
			  function renderCidades(){
			    var el=document.getElementById('cidList'); if(!el) return;
			    var data=rJ('jCd')||{rs:[],peso:[]};
			    var arr=(data[_modoCd]||[]).slice(0,15);
			    if(!arr.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Math.max.apply(null,arr.map(function(d){return Number(d.val)||0;}).concat([1]));
			    var fmtV=_modoCd==='rs'?fMK:function(v){return fA(v)+' kg';};
			    el.innerHTML=arr.map(function(d){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      var tt='<b>'+escT(d.nome)+' / '+escT(d.uf||'-')+'</b><br>'+(_modoCd==='rs'?'Faturamento':'Peso')+': '+fmtV(v)+'<br>Clientes: '+fN(d.clientes||0);
			      return ""<div class='bar-row' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'><div class='bar-head'><div class='bar-name'>""+esc(d.nome)+"" <span class='bar-sub'>""+esc(d.uf||'')+""</span></div><div class='bar-val'>""+fmtV(v)+""</div></div><div class='bar-track'><div class='bar-fill' data-w='""+w+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.bar-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  var _modoAtv='rs';
			  window.setModoAtv=function(m){ _modoAtv=m; document.querySelectorAll('#atvModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderAtividades(); };
			  function renderAtividades(){
			    var el=document.getElementById('atvList'); if(!el) return;
			    var data=rJ('jAtv')||{rs:[],peso:[]};
			    var arr=(data[_modoAtv]||[]).slice(0,12);
			    if(!arr.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Math.max.apply(null,arr.map(function(d){return Number(d.val)||0;}).concat([1]));
			    var fmtV=_modoAtv==='rs'?fMK:function(v){return fA(v)+' kg';};
			    el.innerHTML=arr.map(function(d){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      var tt='<b>'+escT(d.nome)+'</b><br>'+(_modoAtv==='rs'?'Faturamento':'Peso')+': '+fmtV(v)+'<br>Clientes: '+fN(d.clientes||0);
			      return ""<div class='bar-row' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'><div class='bar-head'><div class='bar-name'>""+esc(d.nome)+""</div><div class='bar-val'>""+fmtV(v)+""</div></div><div class='bar-track'><div class='bar-fill' data-w='""+w+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.bar-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  function renderRoscaCat(){
			    var el=document.getElementById('svgRoscaCat'); if(!el) return;
			    var d=svgDim(el,420,300); var W=d[0],H=d[1];
			    el.setAttribute('viewBox','0 0 '+W+' '+H);
			    var arr=(rJ('jMix')||[]).filter(function(x){return (Number(x.val)||0)>0;});
			    if(!arr.length){ el.innerHTML=""<text x='""+(W/2)+""' y='""+(H/2)+""' text-anchor='middle' fill='#999'>Sem devolucoes</text>""; return; }
			    var total=arr.reduce(function(s,x){return s+(Number(x.val)||0);},0); if(total<=0) total=1;
			    var colors={Comercial:'#4A6E8A',Qualidade:'#A04848',Logistica:'#C07C3A','Log\u00edstica':'#C07C3A',Industria:'#4E7D62','Ind\u00fastria':'#4E7D62',Administrativo:'#5A5A5A',Fiscal:'#8A6740'};
			    var fallback=['#1A1A1A','#B8935A','#4E7D62','#C07C3A','#4A6E8A','#5A5A5A'];
			    var cx=W*0.32, cy=H/2;
			    var r=Math.min(W*0.26,H*0.40), ri=r*0.58;
			    var start=-Math.PI/2;
			    var svg='';
			    arr.forEach(function(d2,i){
			      var v=Number(d2.val)||0;
			      var ang=(v/total)*Math.PI*2;
			      var end=start+ang;
			      var la=ang>Math.PI?1:0;
			      var x1=cx+r*Math.cos(start), y1=cy+r*Math.sin(start);
			      var x2=cx+r*Math.cos(end),   y2=cy+r*Math.sin(end);
			      var xi1=cx+ri*Math.cos(end), yi1=cy+ri*Math.sin(end);
			      var xi2=cx+ri*Math.cos(start), yi2=cy+ri*Math.sin(start);
			      var dPath='M '+x1.toFixed(2)+' '+y1.toFixed(2)+' A '+r.toFixed(2)+' '+r.toFixed(2)+' 0 '+la+' 1 '+x2.toFixed(2)+' '+y2.toFixed(2)+' L '+xi1.toFixed(2)+' '+yi1.toFixed(2)+' A '+ri.toFixed(2)+' '+ri.toFixed(2)+' 0 '+la+' 0 '+xi2.toFixed(2)+' '+yi2.toFixed(2)+' Z';
			      var pct=(v/total*100).toFixed(1).replace('.',',');
			      var color=colors[d2.nome]||fallback[i%fallback.length];
			      var tt='<b>'+escT(d2.nome)+'</b><br>Devolucao: '+fMK(v)+'<br>'+pct+'% do total<br>Tipos: '+fN(d2.qtdTipos||0)+'<br>Clientes: '+fN(d2.clientes||0);
			      svg+=""<path class='donut-slice' d='""+dPath+""' fill='""+color+""' stroke='#FFFFFF' stroke-width='2' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'/>"";
			      start=end;
			    });
			    svg+=""<text x='""+cx+""' y='""+(cy-2)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:19px;font-weight:700;font-family:Segoe UI,system-ui'>""+fMK(total)+""</text>"";
			    svg+=""<text x='""+cx+""' y='""+(cy+16)+""' text-anchor='middle' fill='#8B8B8B' style='font-size:10.5px;font-weight:600;letter-spacing:1.6px;font-family:Segoe UI,system-ui'>DEVOLUCAO YUZAP</text>"";
			    var lx=W*0.60;
			    var step=42;
			    var ly=Math.max(28,(H-arr.length*step)/2+12);
			    arr.forEach(function(d2,i){
			      var v=Number(d2.val)||0;
			      var pct=(v/total*100).toFixed(1).replace('.',',');
			      var color=colors[d2.nome]||fallback[i%fallback.length];
			      var y=ly+i*step;
			      svg+=""<rect x='""+lx+""' y='""+(y-10)+""' width='12' height='12' rx='3' fill='""+color+""'/>"";
			      svg+=""<text x='""+(lx+20)+""' y='""+y+""' fill='#1A1A1A' style='font-size:13px;font-weight:600;font-family:Segoe UI,system-ui'>""+esc(d2.nome)+""</text>"";
			      svg+=""<text x='""+(lx+20)+""' y='""+(y+15)+""' style='font-size:11.5px;font-family:Segoe UI,system-ui'><tspan fill='#5A5A5A'>""+fMK(v)+""</tspan> <tspan fill='#B8935A' font-weight='700'>""+pct+""%</tspan></text>"";
			    });
			    el.innerHTML=svg;
			  }
			  function renderTopMotivos(){
			    var el=document.getElementById('topMotBox'); if(!el) return;
			    var data=(rJ('jMot')||[]).slice(0,10);
			    if(!data.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Math.max.apply(null,data.map(function(d){return Number(d.val)||0;}).concat([1]));
			    el.innerHTML=data.map(function(d){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      var clr=catColor(d.categoria);
			      var tt='<b>'+escT(d.nome)+'</b><br>Categoria: '+escT(d.categoria)+'<br>Devolucao: '+fMK(v)+'<br>Peso: '+fA(d.peso||0)+' kg<br>Clientes: '+fN(d.clientes||0);
			      return ""<div class='bar-row' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'><div class='bar-head'><div class='bar-name'>""+esc(d.nome)+"" <span class='tag-badge tag-mini' style='background:""+clr.bg+"";color:""+clr.fg+""'>""+esc(d.categoria||'-')+""</span></div><div class='bar-val'>""+fMK(v)+""</div></div><div class='bar-track'><div class='bar-fill' data-w='""+w+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.bar-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  var _aba='cliente';
			  window.setAba=function(aba){ _aba=aba; document.querySelectorAll('#abasTabs .tab').forEach(function(t){ t.classList.toggle('on', t.dataset.aba===aba); }); renderTabela(); };
			  function renderTabela(){
			    var el=document.getElementById('tabBox'); if(!el) return;
			    var data, cols;
			    if(_aba==='cliente'){ data=rJ('jTc')||[]; cols=[{k:'codigo',t:'Codigo',cls:'mono'},{k:'cliente',t:'Cliente',cls:'name'},{k:'cidade',t:'Cidade',cls:'name'},{k:'atividade',t:'Atividade',cls:'tag'},{k:'label',t:'Ult. Label',cls:'tag'},{k:'status',t:'Status',cls:'status'},{k:'conversas',t:'Conv.',cls:'num',fmt:fN},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'dev',t:'Devolucao R$',cls:'num',fmt:fMK},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct},{k:'diasUltCompra',t:'Dias Ult. Compra',cls:'num',fmt:function(v){var n=Number(v); return n<0?'-':fN(n);}}]; }
			    else if(_aba==='produto'){ data=rJ('jTp')||[]; cols=[{k:'produto',t:'Produto',cls:'name'},{k:'grupo',t:'Grupo',cls:'tag'},{k:'subgrupo',t:'Subgrupo',cls:'tag'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'peso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'clientes',t:'Clientes',cls:'num',fmt:fN},{k:'dev',t:'Devolucao R$',cls:'num',fmt:fMK,bar:true},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else if(_aba==='vendedor'){ data=rJ('jTv')||[]; cols=[{k:'vendedor',t:'Vendedor',cls:'name'},{k:'supervisor',t:'Supervisor',cls:'tag'},{k:'gerente',t:'Gerente',cls:'tag'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'peso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'clientes',t:'Clientes',cls:'num',fmt:fN},{k:'dev',t:'Devolucao R$',cls:'num',fmt:fMK},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else if(_aba==='cidade'){ data=rJ('jTcd')||[]; cols=[{k:'cidade',t:'Cidade',cls:'name'},{k:'uf',t:'UF',cls:'tag'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'peso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'clientes',t:'Clientes',cls:'num',fmt:fN},{k:'dev',t:'Devolucao R$',cls:'num',fmt:fMK},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else { data=rJ('jTm')||[]; cols=[{k:'motivo',t:'Motivo de Devolucao',cls:'name'},{k:'categoria',t:'Categoria',cls:'cat'},{k:'dev',t:'Devolucao R$',cls:'num',fmt:fMK,bar:true},{k:'peso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'qtdLinhas',t:'Linhas',cls:'num',fmt:fN},{k:'clientes',t:'Clientes',cls:'num',fmt:fN}]; }
			    if(!data.length){ el.innerHTML=""<div style='padding:20px;color:#8B8B8B;text-align:center'>Sem dados</div>""; return; }
			    var maxNum={};
			    cols.forEach(function(c){ if(c.cls==='num' && c.bar){ maxNum[c.k]=Math.max.apply(null,data.map(function(d){return Number(d[c.k])||0;}).concat([1])); } });
			    var head=""<thead><tr>""+cols.map(function(c){return ""<th class='th-""+c.cls+""'>""+c.t+""</th>"";}).join('')+""</tr></thead>"";
			    var body=""<tbody>""+data.map(function(d){
			      return ""<tr>""+cols.map(function(c){
			        var v=d[c.k]; var text=c.fmt?c.fmt(v):esc(v);
			        if(c.cls==='num' && c.bar){ var n=Number(v)||0; var pct=Math.max(0,(n/maxNum[c.k])*100); return ""<td class='td-num'><div class='cell-val'>""+text+""</div><div class='cell-bar'><div class='cell-fill' style='width:""+pct.toFixed(1)+""%'></div></div></td>""; }
			        if(c.cls==='tag'){ var clr=tagColor(v); return ""<td class='td-tag'><span class='tag-badge' style='background:""+clr.bg+"";color:""+clr.fg+""'>""+esc(v||'-')+""</span></td>""; }
			        if(c.cls==='cat'){ var clr2=catColor(v); return ""<td class='td-tag'><span class='tag-badge' style='background:""+clr2.bg+"";color:""+clr2.fg+""'>""+esc(v||'-')+""</span></td>""; }
			        if(c.cls==='status'){ var clr3=statusBadge(v); return ""<td class='td-tag'><span class='tag-badge' style='background:""+clr3.bg+"";color:""+clr3.fg+""'>""+esc(v||'-')+""</span></td>""; }
			        if(c.cls==='mono'){ return ""<td class='td-mono'>""+esc(v)+""</td>""; }
			        return ""<td class='td-""+c.cls+""'>""+text+""</td>"";
			      }).join('')+""</tr>"";
			    }).join('')+""</tbody>"";
			    el.innerHTML=""<table class='tbl'>""+head+body+""</table>"";
			  }
			  function renderAll(){
			    if(!document.getElementById('kpiGrid')) return false;
			    try { buildKPIs(); renderFunil(); renderPorLabel(); renderPerdidos(); renderEvolucao(); renderHier(); renderCidades(); renderAtividades(); renderRoscaCat(); renderTopMotivos(); renderTabela(); return true; }
			    catch(e){ console.error(e); return false; }
			  }
			  var _prevHash='';
			  function dataHash(){ return ['jKpi','jFn','jLb','jPe','jEv','jHp','jHv','jCd','jAtv','jMix','jMot','jTc','jTp','jTv','jTcd','jTm'].map(function(id){ var e=document.getElementById(id); if(!e) return ''; return e.textContent.length+'|'+e.textContent.slice(0,20); }).join('~'); }
			  setInterval(function(){ var h=dataHash(); if(h!==_prevHash){ _prevHash=h; renderAll(); } }, 350);
			  var rt;
			  window.addEventListener('resize', function(){ clearTimeout(rt); rt=setTimeout(renderAll,120); });
			  function tryRender(a){ a=a||0; if(renderAll()) return; if(a<25) setTimeout(function(){ tryRender(a+1); }, 100); }
			  if(document.readyState==='loading'){ document.addEventListener('DOMContentLoaded', function(){ tryRender(); }); } else { tryRender(); }
			  window.addEventListener('load', function(){ tryRender(); });
			})();" & "</script>"
		displayFolder: HTML Yuzap
		lineageTag: b666fdf2-5950-4418-9dac-4b36edc1b5de

	/// HTML completo da pagina Yuzap x ERP v5 - acentos e ortografia corrigidos. Cards Mix Devolucao + Top 10 Motivos com altura fixa via flexbox. Resto: sem Conversao por Label, cards Cidades/Atividades com scroll, aba Clientes c/ Dev, tabela Cliente filtra fat>0. Usa _JS Yz v2.
	measure 'HTML Yz' =
			VAR _css =
			"<style>" &
			"*,*::before,*::after{box-sizing:border-box}" &
			"html,body{margin:0;padding:0;background:#EDE8DF;color:#1A1A1A;font-family:'Segoe UI',system-ui,-apple-system,sans-serif;font-size:14px;line-height:1.4}" &
			".wrap{max-width:1480px;margin:0 auto;padding:14px 18px 40px}" &
			".pgHead{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:16px 20px;background:linear-gradient(135deg,#1A1A1A 0%,#2A1F12 70%,#3A2410 100%);color:#EDE8DF;border-radius:10px;margin-bottom:16px;box-shadow:0 6px 22px rgba(0,0,0,.18)}" &
			".pgHead h1{margin:0;font-size:19px;font-weight:700;letter-spacing:.2px;line-height:1.15}" &
			".pgHead .pgSub{font-size:12px;color:#C9A96E;font-weight:600;letter-spacing:1.4px;text-transform:uppercase;display:block;margin-bottom:3px}" &
			".pgHead .pgIcon{width:42px;height:42px;border-radius:10px;background:rgba(184,147,90,.16);display:flex;align-items:center;justify-content:center;color:#C9A96E;flex-shrink:0}" &
			".pgHead .pgIcon svg{width:22px;height:22px}" &
			".grid{display:grid;grid-template-columns:repeat(12,1fr);gap:14px}" &
			".col-12{grid-column:span 12}.col-6{grid-column:span 6}.col-4{grid-column:span 4}.col-3{grid-column:span 3}" &
			"@media(max-width:980px){.col-6,.col-4,.col-3{grid-column:span 12}}" &
			".card{background:#FFFFFF;border-radius:10px;padding:16px 18px;box-shadow:0 2px 10px rgba(58,36,16,.08);border:1px solid rgba(58,36,16,.06)}" &
			".card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:12px}" &
			".card-title{font-size:13.5px;font-weight:700;color:#1A1A1A;letter-spacing:.1px;margin:0}" &
			".card-sub{font-size:11.5px;color:#8B8B8B;margin-top:2px;font-weight:500}" &
			".card-eq{height:480px;display:flex;flex-direction:column}" &
			".card-eq .card-head{flex-shrink:0}" &
			".kpi{background:#FFFFFF;border-radius:10px;padding:14px 16px;box-shadow:0 2px 10px rgba(58,36,16,.08);border:1px solid rgba(58,36,16,.06);display:flex;flex-direction:column;gap:6px;min-height:108px}" &
			".kpi-top{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}" &
			".kpi-label{font-size:11px;color:#5A5A5A;font-weight:600;letter-spacing:1.1px;text-transform:uppercase;line-height:1.25}" &
			".kpi-icon{width:32px;height:32px;border-radius:8px;background:rgba(184,147,90,.14);color:#B8935A;display:flex;align-items:center;justify-content:center;flex-shrink:0}" &
			".kpi-icon svg{width:17px;height:17px}" &
			".kpi-val{font-size:24px;font-weight:700;color:#1A1A1A;line-height:1.1;font-variant-numeric:tabular-nums;letter-spacing:-.4px}" &
			".kpi-sub{font-size:11.5px;color:#5A5A5A;font-weight:500}" &
			".kpi-sub .up{color:#3D6049;font-weight:700}" &
			".kpi-sub .down{color:#A04848;font-weight:700}" &
			".kpi-sub .neu{color:#8B8B8B;font-weight:600}" &
			".funil-row{margin-bottom:10px}" &
			".funil-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:4px}" &
			".funil-name{font-size:13px;font-weight:600;color:#1A1A1A}" &
			".funil-desc{font-size:11.5px;color:#8B8B8B;font-weight:500;margin-left:6px}" &
			".funil-val{font-size:14px;font-weight:700;color:#1A1A1A;font-variant-numeric:tabular-nums}" &
			".funil-pct{font-size:11.5px;color:#B8935A;font-weight:700;margin-left:4px}" &
			".funil-track{height:14px;background:rgba(58,36,16,.05);border-radius:4px;overflow:hidden}" &
			".funil-fill{height:100%;width:0;border-radius:4px;transition:width .55s cubic-bezier(.2,.65,.3,1)}" &
			".bar-row{margin-bottom:8px}" &
			".bar-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:3px}" &
			".bar-name{font-size:12.5px;font-weight:600;color:#1A1A1A;flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}" &
			".bar-sub{font-size:11px;color:#8B8B8B;font-weight:500;margin-left:6px}" &
			".bar-val{font-size:12.5px;font-weight:700;color:#1A1A1A;font-variant-numeric:tabular-nums;flex-shrink:0}" &
			".bar-track{height:8px;background:rgba(58,36,16,.05);border-radius:3px;overflow:hidden}" &
			".bar-fill{height:100%;width:0;background:linear-gradient(90deg,#B8935A 0%,#1A1A1A 100%);border-radius:3px;transition:width .55s cubic-bezier(.2,.65,.3,1)}" &
			".toggle{display:inline-flex;background:rgba(58,36,16,.06);border-radius:6px;padding:2px;gap:0}" &
			".toggle button{background:transparent;border:0;padding:5px 11px;font-size:11.5px;font-weight:600;color:#5A5A5A;cursor:pointer;border-radius:4px;letter-spacing:.3px;font-family:inherit;transition:all .2s}" &
			".toggle button:hover{color:#1A1A1A}" &
			".toggle button.on{background:#1A1A1A;color:#EDE8DF;box-shadow:0 1px 4px rgba(0,0,0,.15)}" &
			".tbl{width:100%;border-collapse:collapse;font-size:12.5px}" &
			".tbl thead th{position:sticky;top:0;background:#F5F1E8;color:#5A5A5A;font-size:10.5px;font-weight:700;text-transform:uppercase;letter-spacing:.8px;padding:9px 8px;border-bottom:2px solid rgba(58,36,16,.12);text-align:left}" &
			".tbl thead .th-num{text-align:right}" &
			".tbl tbody td{padding:8px;border-bottom:1px solid rgba(58,36,16,.06);vertical-align:middle}" &
			".tbl tbody tr:hover{background:rgba(184,147,90,.05)}" &
			".td-num{text-align:right;font-variant-numeric:tabular-nums;font-weight:600;color:#1A1A1A}" &
			".td-name{color:#1A1A1A;font-weight:500}" &
			".td-mono{font-family:'Consolas','Courier New',monospace;font-size:11.5px;color:#5A5A5A}" &
			".td-tag{}" &
			".tag-badge{display:inline-block;padding:3px 9px;border-radius:11px;font-size:10.5px;font-weight:700;letter-spacing:.3px;white-space:nowrap}" &
			".tag-mini{padding:2px 7px;font-size:9.5px;margin-left:6px;vertical-align:middle}" &
			".cell-val{font-weight:700;color:#1A1A1A;font-variant-numeric:tabular-nums;text-align:right}" &
			".cell-bar{height:4px;background:rgba(58,36,16,.05);border-radius:2px;overflow:hidden;margin-top:3px}" &
			".cell-fill{height:100%;background:linear-gradient(90deg,#B8935A,#1A1A1A);border-radius:2px}" &
			".pct-hi{color:#3D6049}" &
			".pct-md{color:#8A6740}" &
			".pct-lo{color:#A04848}" &
			".tbl-compact tbody td{padding:6px 8px;font-size:12px}" &
			".pager{display:flex;align-items:center;justify-content:center;gap:14px;padding:10px 0 2px;font-size:11.5px;color:#5A5A5A;font-weight:500}" &
			".pager button{background:#FFFFFF;border:1px solid rgba(58,36,16,.15);color:#1A1A1A;font-weight:600;padding:5px 12px;border-radius:5px;cursor:pointer;font-size:11.5px;font-family:inherit;transition:all .15s}" &
			".pager button:hover:not(:disabled){background:#1A1A1A;color:#EDE8DF;border-color:#1A1A1A}" &
			".pager button:disabled{opacity:.4;cursor:not-allowed}" &
			".tabs{display:flex;gap:0;border-bottom:2px solid rgba(58,36,16,.08);margin-bottom:12px}" &
			".tabs .tab{background:transparent;border:0;padding:8px 16px;font-size:12.5px;font-weight:600;color:#8B8B8B;cursor:pointer;letter-spacing:.3px;font-family:inherit;border-bottom:2px solid transparent;margin-bottom:-2px;transition:all .15s}" &
			".tabs .tab:hover{color:#1A1A1A}" &
			".tabs .tab.on{color:#1A1A1A;border-bottom-color:#B8935A}" &
			".scrollX{overflow-x:auto;-webkit-overflow-scrolling:touch}" &
			".scrollY{max-height:520px;overflow-y:auto;overflow-x:auto}" &
			".scroll-card{max-height:360px;overflow-y:auto;overflow-x:hidden;padding-right:4px}" &
			".scroll-card::-webkit-scrollbar,.scroll-flex::-webkit-scrollbar{width:6px}" &
			".scroll-card::-webkit-scrollbar-track,.scroll-flex::-webkit-scrollbar-track{background:rgba(58,36,16,.04);border-radius:3px}" &
			".scroll-card::-webkit-scrollbar-thumb,.scroll-flex::-webkit-scrollbar-thumb{background:rgba(58,36,16,.2);border-radius:3px}" &
			".scroll-card::-webkit-scrollbar-thumb:hover,.scroll-flex::-webkit-scrollbar-thumb:hover{background:rgba(58,36,16,.35)}" &
			".scroll-flex{flex:1;min-height:0;overflow-y:auto;overflow-x:hidden;padding-right:4px}" &
			".svg-box{width:100%;height:300px;display:block}" &
			".svg-hier{width:100%;min-height:460px;display:block}" &
			".svg-rosca{width:100%;height:360px;display:block}" &
			".svg-rosca-flex{flex:1;width:100%;min-height:0;display:block}" &
			".vbar{transition:opacity .15s}" &
			".vbar:hover{opacity:.82}" &
			".donut-slice{cursor:pointer;transition:opacity .15s}" &
			".donut-slice:hover{opacity:.85}" &
			"#tt{position:fixed;display:none;background:#1A1A1A;color:#EDE8DF;font-size:11.5px;line-height:1.5;padding:8px 11px;border-radius:6px;pointer-events:none;z-index:9999;box-shadow:0 6px 22px rgba(0,0,0,.32);max-width:260px;font-family:'Segoe UI',system-ui,sans-serif}" &
			"#tt.on{display:block}" &
			"#tt b{color:#C9A96E;font-weight:700}" &
			".pgHead-stats{display:flex;gap:18px;flex-wrap:wrap}" &
			".pgHead-stat{display:flex;flex-direction:column;align-items:flex-end}" &
			".pgHead-stat-l{font-size:10px;color:#C9A96E;font-weight:600;letter-spacing:.9px;text-transform:uppercase}" &
			".pgHead-stat-v{font-size:15px;color:#EDE8DF;font-weight:700;font-variant-numeric:tabular-nums}" &
			"</style>"
			
			VAR _icon = "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2' stroke-linecap='round' stroke-linejoin='round'><path d='M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z'/></svg>"
			
			VAR _head =
			"<div class='pgHead'>" &
			"<div style='display:flex;align-items:center;gap:14px'>" &
			"<div class='pgIcon'>" & _icon & "</div>" &
			"<div><span class='pgSub'>Cruzamento Yuzap x ERP</span><h1>Conversão de Atendimentos em Vendas</h1></div>" &
			"</div>" &
			"<div class='pgHead-stats'>" &
			"<div class='pgHead-stat'><span class='pgHead-stat-l'>Identificados</span><span class='pgHead-stat-v'>" & FORMAT(COALESCE([Yuzap - Clientes Identificados], 0), "#,0") & "</span></div>" &
			"<div class='pgHead-stat'><span class='pgHead-stat-l'>Convertidos</span><span class='pgHead-stat-v'>" & FORMAT(COALESCE([Yuzap - Clientes Convertidos], 0), "#,0") & "</span></div>" &
			"<div class='pgHead-stat'><span class='pgHead-stat-l'>Faturamento</span><span class='pgHead-stat-v'>" & FORMAT(COALESCE([Yuzap - Faturamento], 0)/1000, "#,0") & " mil</span></div>" &
			"</div>" &
			"</div>"
			
			VAR _kpis = "<div class='grid' style='margin-bottom:14px'><div class='col-12' id='kpiGrid' style='display:grid;grid-template-columns:repeat(4,1fr);gap:14px'></div></div>"
			
			VAR _funil =
			"<div class='grid' style='margin-bottom:14px'><div class='col-12'><div class='card'>" &
			"<div class='card-head'><div><h3 class='card-title'>Funil de Conversão Yuzap → ERP</h3><div class='card-sub'>Da identificação no Yuzap à venda recorrente sem devoluções</div></div></div>" &
			"<div id='funilBox'></div>" &
			"</div></div></div>"
			
			VAR _perdidos =
			"<div class='grid' style='margin-bottom:14px'><div class='col-12'><div class='card'>" &
			"<div class='card-head'><div><h3 class='card-title'>Clientes Perdidos: identificados no Yuzap, sem venda no ERP</h3><div class='card-sub'>Oportunidade de retomada - ordenado por atividade mais recente</div></div></div>" &
			"<div class='scrollX' id='perdidosBox'></div>" &
			"</div></div></div>"
			
			VAR _evo =
			"<div class='grid' style='margin-bottom:14px'><div class='col-12'><div class='card'>" &
			"<div class='card-head'><div><h3 class='card-title'>Evolução Mensal</h3><div class='card-sub'>Ignora filtros de data - mostra histórico completo</div></div>" &
			"<div class='toggle' id='evoModoToggle'>" &
			"<button data-m='val' class='on' onclick='setModoEvo(""val"")'>Faturamento</button>" &
			"<button data-m='peso' onclick='setModoEvo(""peso"")'>Peso</button>" &
			"<button data-m='pedidos' onclick='setModoEvo(""pedidos"")'>Pedidos</button>" &
			"<button data-m='dev' onclick='setModoEvo(""dev"")'>Devolução</button>" &
			"</div></div>" &
			"<svg id='svgEvo' class='svg-box' xmlns='http://www.w3.org/2000/svg' preserveAspectRatio='xMidYMid meet'></svg>" &
			"</div></div></div>"
			
			VAR _hier =
			"<div class='grid' style='margin-bottom:14px'><div class='col-12'><div class='card'>" &
			"<div class='card-head'><div><h3 class='card-title'>Top 15 - Produtos e Vendedores</h3><div class='card-sub'>Hierarquia: produto ou vendedor; métrica: faturamento ou peso</div></div>" &
			"<div style='display:flex;gap:8px;align-items:center'>" &
			"<div class='toggle' id='hierToggle'>" &
			"<button data-h='produto' class='on' onclick='setModoH(""produto"")'>Produto</button>" &
			"<button data-h='vendedor' onclick='setModoH(""vendedor"")'>Vendedor</button>" &
			"</div>" &
			"<div class='toggle' id='hierMToggle'>" &
			"<button data-m='rs' class='on' onclick='setModoHM(""rs"")'>R$</button>" &
			"<button data-m='peso' onclick='setModoHM(""peso"")'>kg</button>" &
			"</div></div></div>" &
			"<div class='scrollX' id='hierBox' style='min-height:460px'></div>" &
			"</div></div></div>"
			
			VAR _geo =
			"<div class='grid' style='margin-bottom:14px'>" &
			"<div class='col-6'><div class='card'>" &
			"<div class='card-head'><div><h3 class='card-title'>Top Cidades</h3><div class='card-sub'>Onde estão os clientes Yuzap convertidos</div></div>" &
			"<div class='toggle' id='cdModoToggle'>" &
			"<button data-m='rs' class='on' onclick='setModoCd(""rs"")'>R$</button>" &
			"<button data-m='peso' onclick='setModoCd(""peso"")'>kg</button>" &
			"</div></div>" &
			"<div class='scroll-card' id='cidList'></div>" &
			"</div></div>" &
			"<div class='col-6'><div class='card'>" &
			"<div class='card-head'><div><h3 class='card-title'>Top Atividades</h3><div class='card-sub'>Segmentos de mercado dos clientes Yuzap</div></div>" &
			"<div class='toggle' id='atvModoToggle'>" &
			"<button data-m='rs' class='on' onclick='setModoAtv(""rs"")'>R$</button>" &
			"<button data-m='peso' onclick='setModoAtv(""peso"")'>kg</button>" &
			"</div></div>" &
			"<div class='scroll-card' id='atvList'></div>" &
			"</div></div>" &
			"</div>"
			
			VAR _dev =
			"<div class='grid' style='margin-bottom:14px'>" &
			"<div class='col-6'><div class='card card-eq'>" &
			"<div class='card-head'><div><h3 class='card-title'>Mix de Devolução por Categoria</h3><div class='card-sub'>Devoluções apenas dos clientes Yuzap</div></div></div>" &
			"<svg id='svgRoscaCat' class='svg-rosca-flex' xmlns='http://www.w3.org/2000/svg' preserveAspectRatio='xMidYMid meet'></svg>" &
			"</div></div>" &
			"<div class='col-6'><div class='card card-eq'>" &
			"<div class='card-head'><div><h3 class='card-title'>Top 10 Motivos de Devolução</h3><div class='card-sub'>Específicos dos clientes Yuzap, com categoria</div></div></div>" &
			"<div class='scroll-flex' id='topMotBox'></div>" &
			"</div></div>" &
			"</div>"
			
			VAR _tabela =
			"<div class='grid'><div class='col-12'><div class='card'>" &
			"<div class='card-head'><div><h3 class='card-title'>Detalhamento</h3><div class='card-sub'>Explore os dados em 5 perspectivas - todas filtradas pelos clientes Yuzap</div></div></div>" &
			"<div class='tabs' id='abasTabs'>" &
			"<button class='tab on' data-aba='cliente' onclick='setAba(""cliente"")'>Clientes</button>" &
			"<button class='tab' data-aba='produto' onclick='setAba(""produto"")'>Produtos</button>" &
			"<button class='tab' data-aba='vendedor' onclick='setAba(""vendedor"")'>Vendedores</button>" &
			"<button class='tab' data-aba='cidade' onclick='setAba(""cidade"")'>Cidades</button>" &
			"<button class='tab' data-aba='devcliente' onclick='setAba(""devcliente"")'>Clientes c/ Dev.</button>" &
			"</div>" &
			"<div class='scrollY' id='tabBox'></div>" &
			"</div></div></div>"
			
			VAR _jsonContainers =
			"<div style='display:none'>" &
			"<div id='jKpi'>"  & [_JSON KPIs Yz] & "</div>" &
			"<div id='jFn'>"   & [_JSON Funil Yz] & "</div>" &
			"<div id='jPe'>"   & [_JSON Perdidos Yz] & "</div>" &
			"<div id='jEv'>"   & [_JSON Evolucao Yz] & "</div>" &
			"<div id='jHp'>"   & [_JSON Top Produto Yz] & "</div>" &
			"<div id='jHv'>"   & [_JSON Top Vendedor Yz] & "</div>" &
			"<div id='jCd'>"   & [_JSON Top Cidade Yz] & "</div>" &
			"<div id='jAtv'>"  & [_JSON Top Atividade Yz] & "</div>" &
			"<div id='jMix'>"  & [_JSON Mix Categoria Dev Yz] & "</div>" &
			"<div id='jMot'>"  & [_JSON Top Motivos Dev Yz] & "</div>" &
			"<div id='jTc'>"   & [_JSON Tabela Cliente Yz] & "</div>" &
			"<div id='jTp'>"   & [_JSON Tabela Produto Yz] & "</div>" &
			"<div id='jTv'>"   & [_JSON Tabela Vendedor Yz] & "</div>" &
			"<div id='jTcd'>"  & [_JSON Tabela Cidade Yz] & "</div>" &
			"<div id='jTdc'>"  & [_JSON TabDevCliente Yz] & "</div>" &
			"</div>"
			
			RETURN
			"<div>" &
			_css &
			"<div id='tt'></div>" &
			"<div class='wrap'>" &
			_head &
			_kpis &
			_funil &
			_perdidos &
			_evo &
			_hier &
			_geo &
			_dev &
			_tabela &
			"</div>" &
			_jsonContainers &
			[_JS Yz v2] &
			"</div>"
		displayFolder: HTML Yuzap
		lineageTag: 8966d27b-eedd-47e5-8b30-7fef92942f59

	/// Versao corrigida do _JS Yz. Bug original: 'class=\\''+momCls(...)+'\\'>'  quebra parse JS porque \\ + aspa simples fecha string. Corrigido com aspas duplas no HTML class.
	measure '_JS Yz Fixed' =
			SUBSTITUTE(
			    SUBSTITUTE(
			        [_JS Yz],
			        "sub:'MoM = <span class=\\''+momCls(K.momFat)+'\\'>'+(K.momFat||'-')+'</span>'",
			        "sub:'MoM = <span class=""'+momCls(K.momFat)+'"">'+(K.momFat||'-')+'</span>'"
			    ),
			    "sub:'MoM = <span class=\\''+momCls(K.momDev)+'\\'>'+(K.momDev||'-')+'</span>'",
			    "sub:'MoM = <span class=""'+momCls(K.momDev)+'"">'+(K.momDev||'-')+'</span>'"
			)
		displayFolder: HTML Yuzap
		lineageTag: f238f39d-a587-491d-a6a8-548cc07327b9

	/// Tabela detalhada dos clientes Yuzap COM DEVOLUCAO > 0. Inclui motivo principal (maior valor de dev), categoria, fat, dev, taxa dev, pedidos, peso devolvido.
	measure '_JSON TabDevCliente Yz' =
			VAR _yz =
			    CALCULATETABLE(
			        ADDCOLUMNS(
			            FILTER(
			                VALUES(F_Yuzap_Conversas[data.attr_cdigo_cliente]),
			                NOT(ISBLANK(F_Yuzap_Conversas[data.attr_cdigo_cliente])) &&
			                F_Yuzap_Conversas[data.attr_cdigo_cliente] <> ""
			            ),
			            "_nome",     CALCULATE(MAX(F_Yuzap_Conversas[Nome Contato]))
			        )
			    )
			VAR _com =
			    ADDCOLUMNS(
			        _yz,
			        "_cidade",      CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[CIDADE]), TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])),
			        "_atividade",   CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[ATIVIDADE]), TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])),
			        "_clienteNome", CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[CLIENTE]), TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])),
			        "_fat",         CALCULATE([Faturamento Total], TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])),
			        "_pedidos",     CALCULATE([Total de Pedidos],  TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])),
			        "_dev",         CALCULATE([Total Devoluções (R$)], TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])),
			        "_pesoDev",     CALCULATE([Peso Total Devolvido], TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])),
			        "_motivoTop",
			            CALCULATE(
			                CONCATENATEX(
			                    TOPN(
			                        1,
			                        FILTER(
			                            VALUES(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO]),
			                            NOT(ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO])) &&
			                            DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO] <> "" &&
			                            CALCULATE([Total Devoluções (R$)]) > 0
			                        ),
			                        CALCULATE([Total Devoluções (R$)]),
			                        DESC
			                    ),
			                    DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO]
			                ),
			                TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			            ),
			        "_categoriaTop",
			            CALCULATE(
			                CONCATENATEX(
			                    TOPN(
			                        1,
			                        FILTER(
			                            VALUES(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO]),
			                            NOT(ISBLANK(DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO])) &&
			                            DCVVQ_VENDAGERALTELEVENDAS[TIPODEVOLUCAO] <> "" &&
			                            CALCULATE([Total Devoluções (R$)]) > 0
			                        ),
			                        CALCULATE([Total Devoluções (R$)]),
			                        DESC
			                    ),
			                    CALCULATE(MAX(DCVVQ_VENDAGERALTELEVENDAS[Categoria Devolução]))
			                ),
			                TREATAS({F_Yuzap_Conversas[data.attr_cdigo_cliente]}, DCVVQ_VENDAGERALTELEVENDAS[SEQCLIENTE])
			            )
			    )
			VAR _comDev = FILTER(_com, COALESCE([_dev], 0) > 0)
			VAR _ordenado = TOPN(220, _comDev, [_dev], DESC)
			RETURN
			"[" & CONCATENATEX(
			    _ordenado,
			    "{""codigo"":""" & SUBSTITUTE(SUBSTITUTE(F_Yuzap_Conversas[data.attr_cdigo_cliente], """""", ""), "\", "") &
			    """,""cliente"":"""   & SUBSTITUTE(SUBSTITUTE(COALESCE([_clienteNome], [_nome], "-"), """""", ""), "\", "") &
			    """,""cidade"":"""    & SUBSTITUTE(SUBSTITUTE(COALESCE([_cidade], "-"), """""", ""), "\", "") &
			    """,""atividade"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_atividade], "-"), """""", ""), "\", "") &
			    """,""motivo"":"""    & SUBSTITUTE(SUBSTITUTE(COALESCE([_motivoTop], "-"), """""", ""), "\", "") &
			    """,""categoria"":""" & SUBSTITUTE(SUBSTITUTE(COALESCE([_categoriaTop], "-"), """""", ""), "\", "") &
			    """,""fat"":"          & SUBSTITUTE(FORMAT(COALESCE([_fat], 0), "0.00"), ",", ".") &
			    ",""dev"":"          & SUBSTITUTE(FORMAT(COALESCE([_dev], 0), "0.00"), ",", ".") &
			    ",""pesoDev"":"      & SUBSTITUTE(FORMAT(COALESCE([_pesoDev], 0), "0.00"), ",", ".") &
			    ",""taxaDev"":"      & SUBSTITUTE(FORMAT(DIVIDE(COALESCE([_dev], 0), COALESCE([_fat], 0) + COALESCE([_dev], 0), 0) * 100, "0.00"), ",", ".") &
			    ",""pedidos"":"      & COALESCE([_pedidos], 0) &
			    "}",
			    ",",
			    [_dev], DESC
			) & "]"
		displayFolder: HTML Yuzap
		lineageTag: 1eae3b18-ebe5-48ff-a312-65b846c2bdfb

	/// Parte 1 do JS Yz v2 - acentos e ortografia corrigidos.
	measure '_JS Yz P1' =
			"(function () {
			  'use strict';
			  function rJ(id) { var e = document.getElementById(id); try { return JSON.parse((e && e.textContent) || 'null'); } catch (ex) { return null; } }
			  function esc(v) { return String(v == null ? '' : v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
			  function escT(v) { return esc(v).replace(/'/g,'&#39;'); }
			  function fN(v) { return (Number(v) || 0).toLocaleString('pt-BR'); }
			  function fA(v) { v = Number(v) || 0; if (Math.abs(v) >= 1e6) return (v/1e6).toFixed(1).replace('.',',') + ' M'; if (Math.abs(v) >= 1e3) return (v/1e3).toFixed(1).replace('.',',') + ' mil'; return fN(v); }
			  function fM(v) { v = Number(v) || 0; return 'R$ ' + v.toLocaleString('pt-BR', {minimumFractionDigits:2, maximumFractionDigits:2}); }
			  function fMK(v) { v = Number(v) || 0; if (Math.abs(v) >= 1e6) return 'R$ ' + (v/1e6).toFixed(2).replace('.',',') + ' M'; if (Math.abs(v) >= 1e3) return 'R$ ' + (v/1e3).toFixed(1).replace('.',',') + ' mil'; return fM(v); }
			  function fPct(v) { return (Number(v)||0).toFixed(2).replace('.',',') + '%'; }
			  function momCls(s) { if (!s || s === '--') return 'neu'; return s.indexOf('+') === 0 ? 'up' : (s.indexOf('-') === 0 ? 'down' : 'neu'); }
			  function svgDim(el, fbW, fbH) { var bb = el.getBoundingClientRect(); return [Math.round(bb.width) || fbW, Math.round(bb.height) || fbH]; }
			  function tagColor(str) {
			    if (!str) return {bg:'rgba(139,139,139,.12)',fg:'#5A5A5A'};
			    var h=0; for (var i=0;i<str.length;i++) h = ((h<<5)-h) + str.charCodeAt(i);
			    var palette = [{bg:'rgba(184,147,90,.15)',fg:'#8A6740'},{bg:'rgba(78,125,98,.15)',fg:'#3D6049'},{bg:'rgba(74,110,138,.15)',fg:'#3A5872'},{bg:'rgba(192,124,58,.15)',fg:'#995F2C'},{bg:'rgba(58,36,16,.12)',fg:'#3A2410'},{bg:'rgba(90,90,90,.15)',fg:'#5A5A5A'}];
			    return palette[Math.abs(h) % palette.length];
			  }
			  function statusBadge(s){ if(s==='Convertido') return {bg:'rgba(78,125,98,.18)',fg:'#3D6049'}; if(s==='Recorrente') return {bg:'rgba(184,147,90,.20)',fg:'#8A6740'}; return {bg:'rgba(160,72,72,.15)',fg:'#A04848'}; }
			  function catColor(c){ if(c && c.indexOf('Comercial')===0) return {bg:'rgba(74,110,138,.18)',fg:'#3A5872'}; if(c && c.indexOf('Qualidade')===0) return {bg:'rgba(160,72,72,.16)',fg:'#A04848'}; if(c && (c.indexOf('Logística')===0||c.indexOf('Logistica')===0||c.indexOf('Log')===0)) return {bg:'rgba(192,124,58,.18)',fg:'#995F2C'}; if(c && (c.indexOf('Indústria')===0||c.indexOf('Industria')===0||c.indexOf('Ind')===0)) return {bg:'rgba(78,125,98,.18)',fg:'#3D6049'}; return tagColor(c); }
			  var ttEl = document.getElementById('tt');
			  window.tip = function(e,h){ if (!ttEl) return; ttEl.innerHTML = h; ttEl.classList.add('on'); var ww=window.innerWidth, x=e.clientX+14; if(x+260>ww) x=ww-280; ttEl.style.left = x+'px'; ttEl.style.top = (e.clientY-36)+'px'; };
			  window.tipOff = function(){ ttEl && ttEl.classList.remove('on'); };
			  var kpiIcons = {
			    users: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><path d='M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2'/><circle cx='9' cy='7' r='4'/><path d='M23 21v-2a4 4 0 0 0-3-3.87'/><path d='M16 3.13a4 4 0 0 1 0 7.75'/></svg>"",
			    target: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><circle cx='12' cy='12' r='10'/><circle cx='12' cy='12' r='6'/><circle cx='12' cy='12' r='2'/></svg>"",
			    money: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><line x1='12' y1='1' x2='12' y2='23'/><path d='M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6'/></svg>"",
			    alert: ""<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2.2'><path d='M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z'/><line x1='12' y1='9' x2='12' y2='13'/><line x1='12' y1='17' x2='12.01' y2='17'/></svg>""
			  };
			  function buildKPIs(){
			    var K=rJ('jKpi')||{}; var el=document.getElementById('kpiGrid'); if(!el) return;
			    var cards=[
			      {icon:'users',  label:'Clientes Identificados', val:fN(K.identificados||0), sub:'<span>'+fN(K.conversas||0)+' conversas no Yuzap</span>'},
			      {icon:'target', label:'% Conversão Yuzap → ERP', val:fPct(K.conversao||0),   sub:'<span>'+fN(K.convertidos||0)+' convertidos / '+fN(K.perdidos||0)+' perdidos</span>'},
			      {icon:'money',  label:'Faturamento Gerado',     val:fMK(K.fat||0),          sub:'MoM = <span class=""'+momCls(K.momFat)+'"">'+(K.momFat||'-')+'</span>'},
			      {icon:'alert',  label:'Taxa de Devolução',      val:fPct(K.taxaDev||0),     sub:'MoM = <span class=""'+momCls(K.momDev)+'"">'+(K.momDev||'-')+'</span>'}
			    ];
			    el.innerHTML=cards.map(function(c){ return ""<div class='kpi'><div class='kpi-top'><span class='kpi-label'>""+c.label+""</span><div class='kpi-icon'>""+kpiIcons[c.icon]+""</div></div><div class='kpi-val'>""+c.val+""</div><div class='kpi-sub'>""+c.sub+""</div></div>""; }).join('');
			  }
			  function renderFunil(){
			    var el=document.getElementById('funilBox'); if(!el) return;
			    var data=rJ('jFn')||[]; if(!data.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Number(data[0].val)||1;
			    el.innerHTML=data.map(function(d,i){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      var pct=i===0?100:(v/(Number(data[0].val)||1))*100;
			      var pctTxt=pct.toFixed(1).replace('.',',')+'%';
			      var colors=['#1A1A1A','#4E7D62','#B8935A','#4A6E8A'];
			      var c=colors[i % colors.length];
			      var tt='<b>'+escT(d.nome)+'</b><br>'+escT(d.desc)+'<br>Total: '+fN(v)+'<br>'+pctTxt+' do topo do funil';
			      return ""<div class='funil-row' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'><div class='funil-head'><div class='funil-name'>""+esc(d.nome)+"" <span class='funil-desc'>""+esc(d.desc)+""</span></div><div class='funil-val'>""+fN(v)+"" <span class='funil-pct'>(""+pctTxt+"")</span></div></div><div class='funil-track'><div class='funil-fill' data-w='""+w+""' style='background:""+c+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.funil-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  var _perdPg=0, _perdPSize=20;
			  window.setPerdPg=function(dir){ var data=rJ('jPe')||[]; var maxPg=Math.max(0,Math.ceil(data.length/_perdPSize)-1); _perdPg=Math.max(0,Math.min(maxPg,_perdPg+dir)); renderPerdidos(); };
			  function renderPerdidos(){
			    var el=document.getElementById('perdidosBox'); if(!el) return;
			    var data=rJ('jPe')||[]; if(!data.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem clientes perdidos</div>""; return; }
			    var total=data.length, maxPg=Math.max(0,Math.ceil(total/_perdPSize)-1);
			    if(_perdPg>maxPg) _perdPg=maxPg;
			    var start=_perdPg*_perdPSize, end=Math.min(start+_perdPSize,total);
			    var page=data.slice(start,end);
			    var head=""<thead><tr><th class='th-name'>Cliente</th><th class='th-name'>Código</th><th class='th-name'>Telefone</th><th class='th-num'>Conversas</th><th class='th-name'>Último Label</th><th class='th-name'>Agente</th><th class='th-name'>Última Atividade</th><th class='th-num'>Dias</th></tr></thead>"";
			    var body=""<tbody>""+page.map(function(d){
			      var clr=tagColor(d.label);
			      var dias=Number(d.dias)||0;
			      var diasCls=dias>30?'pct-lo':(dias>7?'pct-md':'pct-hi');
			      return ""<tr><td class='td-name'>""+esc(d.nome)+""</td><td class='td-mono'>""+esc(d.codigo)+""</td><td class='td-mono'>""+esc(d.tel)+""</td><td class='td-num'>""+fN(d.conversas)+""</td><td class='td-tag'><span class='tag-badge' style='background:""+clr.bg+"";color:""+clr.fg+""'>""+esc(d.label||'-')+""</span></td><td class='td-name'>""+esc(d.agente)+""</td><td class='td-name'>""+esc(d.data)+""</td><td class='td-num ""+diasCls+""'>""+fN(dias)+""</td></tr>"";
			    }).join('')+""</tbody>"";
			    var pager=""<div class='pager'><button ""+(_perdPg===0?'disabled':'')+"" onclick='setPerdPg(-1)'>‹ Anterior</button><span>Página ""+(_perdPg+1)+"" de ""+(maxPg+1)+"" - mostrando ""+(start+1)+""-""+end+"" de ""+total+"" perdidos</span><button ""+(_perdPg>=maxPg?'disabled':'')+"" onclick='setPerdPg(1)'>Próximo ›</button></div>"";
			    el.innerHTML=""<table class='tbl tbl-compact'>""+head+body+""</table>""+pager;
			  }"
		displayFolder: HTML Yuzap
		lineageTag: 13d11140-4a09-4838-abfd-a8a582d52129

	/// Parte 2 do JS Yz v2 - acentos e ortografia corrigidos. Legenda da rosca com fontes maiores.
	measure '_JS Yz P2' =
			"  var _modoEvo='val';
			  window.setModoEvo=function(m){ _modoEvo=m; document.querySelectorAll('#evoModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderEvolucao(); };
			  function renderEvolucao(){
			    var el=document.getElementById('svgEvo'); if(!el) return;
			    var d=svgDim(el,900,300); var W=d[0],H=d[1];
			    el.setAttribute('viewBox','0 0 '+W+' '+H);
			    var data=rJ('jEv')||[]; if(!data.length){ el.innerHTML=""<text x='""+(W/2)+""' y='""+(H/2)+""' text-anchor='middle' fill='#999'>Sem dados</text>""; return; }
			    var P={t:34,r:34,b:50,l:64};
			    var n=data.length;
			    var vals=data.map(function(r){ return Number(r[_modoEvo])||0; });
			    var mx=Math.max.apply(null,vals.concat([1]))*1.18;
			    var stepX=(W-P.l-P.r)/Math.max(1,n-1);
			    var fmtV = _modoEvo==='val'||_modoEvo==='dev'? fMK : (_modoEvo==='peso'? function(v){return fA(v)+' kg';} : fN);
			    var labels={val:'Faturamento',peso:'Peso',pedidos:'Pedidos',dev:'Devolução'};
			    var color = _modoEvo==='dev' ? '#A04848' : '#B8935A';
			    var svg='';
			    for(var i=0;i<=4;i++){
			      var y=P.t+(H-P.t-P.b)*i/4;
			      var v=mx*(1-i/4);
			      svg+=""<line x1='""+P.l+""' x2='""+(W-P.r)+""' y1='""+y.toFixed(1)+""' y2='""+y.toFixed(1)+""' stroke='rgba(0,0,0,.06)' stroke-dasharray='3,4'/>"";
			      if(i<4) svg+=""<text x='""+(P.l-6)+""' y='""+(y+4).toFixed(1)+""' text-anchor='end' fill='#8B8B8B' style='font-size:12px;font-family:Segoe UI,system-ui'>""+fA(v)+""</text>"";
			    }
			    var pts=data.map(function(r,i){ var x=P.l+i*stepX; var v=Number(r[_modoEvo])||0; var y=P.t+(H-P.t-P.b)*(1-v/mx); return {x:x,y:y,v:v,r:r}; });
			    var path = pts.map(function(p,i){ return (i===0?'M':'L')+p.x.toFixed(1)+' '+p.y.toFixed(1); }).join(' ');
			    var area = path + ' L '+pts[pts.length-1].x.toFixed(1)+' '+(H-P.b)+' L '+pts[0].x.toFixed(1)+' '+(H-P.b)+' Z';
			    var uid='ev'+Math.floor(Math.random()*99999);
			    svg+=""<defs><linearGradient id='""+uid+""' x1='0' y1='0' x2='0' y2='1'><stop offset='0%' stop-color='""+color+""' stop-opacity='.25'/><stop offset='100%' stop-color='""+color+""' stop-opacity='0'/></linearGradient></defs>"";
			    svg+=""<path d='""+area+""' fill='url(#""+uid+"")'/>"";
			    svg+=""<path d='""+path+""' fill='none' stroke='""+color+""' stroke-width='2.5'/>"";
			    pts.forEach(function(p){
			      var tt='<b>'+escT(p.r.mes)+'</b><br>Faturamento: '+fMK(p.r.val)+'<br>Peso: '+fA(p.r.peso)+' kg<br>Pedidos: '+fN(p.r.pedidos)+'<br>Devolução: '+fMK(p.r.dev);
			      svg+=""<circle cx='""+p.x.toFixed(1)+""' cy='""+p.y.toFixed(1)+""' r='4' fill='#fff' stroke='""+color+""' stroke-width='2' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'/>"";
			      svg+=""<text x='""+p.x.toFixed(1)+""' y='""+(p.y-10).toFixed(1)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:10.5px;font-weight:700;font-family:Segoe UI,system-ui;pointer-events:none'>""+fmtV(p.v)+""</text>"";
			    });
			    var labelStep=Math.max(1,Math.ceil(n/12));
			    pts.forEach(function(p,i){ if(i%labelStep!==0 && i!==n-1) return; svg+=""<text x='""+p.x.toFixed(1)+""' y='""+(H-P.b+18)+""' text-anchor='middle' fill='#5A5A5A' style='font-size:11.5px;font-family:Segoe UI,system-ui'>""+esc(p.r.mes)+""</text>""; });
			    svg+=""<text x='""+P.l+""' y='""+(P.t-10)+""' fill='#5A5A5A' style='font-size:11.5px;font-family:Segoe UI,system-ui;font-weight:600'>""+labels[_modoEvo]+""</text>"";
			    el.innerHTML=svg;
			  }
			  var _modoH='produto', _modoHM='rs';
			  window.setModoH=function(m){ _modoH=m; document.querySelectorAll('#hierToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.h===m); }); renderHier(); };
			  window.setModoHM=function(m){ _modoHM=m; document.querySelectorAll('#hierMToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderHier(); };
			  function renderHier(){
			    var el=document.getElementById('hierBox'); if(!el) return;
			    var src={produto:'jHp',vendedor:'jHv'};
			    var data=rJ(src[_modoH])||{rs:[],peso:[]};
			    var arr=(data[_modoHM]||[]).slice(0,15);
			    if(!arr.length){ el.innerHTML=""<div style='padding:30px;color:#8B8B8B;text-align:center'>Sem dados</div>""; return; }
			    var H=460;
			    var P={t:38,r:24,b:108,l:68};
			    var n=arr.length;
			    var containerW=el.clientWidth||900;
			    var availW=containerW-P.l-P.r;
			    var minBarW=30,maxBarW=56,defaultGap=18,maxGap=40;
			    var idealBarW=(availW-(n-1)*defaultGap)/Math.max(n,1);
			    var barW,gap,contentW,startX;
			    if(idealBarW>=maxBarW){ barW=maxBarW; var rem=availW-n*barW; gap=n>1?Math.min(maxGap,rem/(n-1)):0; var tw=n*barW+(n-1)*gap; startX=P.l+Math.max(0,(availW-tw)/2); contentW=containerW; }
			    else if(idealBarW>=minBarW){ barW=idealBarW; gap=defaultGap; startX=P.l; contentW=containerW; }
			    else { barW=minBarW; gap=defaultGap; startX=P.l; contentW=n*barW+(n-1)*gap+P.l+P.r; }
			    var W=Math.max(contentW,containerW);
			    var mx=Math.max.apply(null,arr.map(function(d){return Number(d.val)||0;}).concat([1]))*1.14;
			    var fmtV=_modoHM==='rs'? fMK : function(v){return fA(v)+' kg';};
			    var lblFn=_modoHM==='rs'?'Faturamento':'Peso';
			    var uid='b'+Math.floor(Math.random()*99999);
			    var maxWC=barW<40?10:14;
			    var svg=""<defs><linearGradient id='bg""+uid+""' x1='0%' y1='0%' x2='0%' y2='100%'><stop offset='0%' stop-color='#B8935A' stop-opacity='1'/><stop offset='100%' stop-color='#1A1A1A' stop-opacity='1'/></linearGradient></defs>"";
			    for(var i=0;i<=4;i++){ var y=P.t+(H-P.t-P.b)*i/4; var v=mx*(1-i/4); svg+=""<line x1='""+P.l+""' x2='""+(W-P.r)+""' y1='""+y.toFixed(1)+""' y2='""+y.toFixed(1)+""' stroke='rgba(0,0,0,.06)' stroke-dasharray='3,4'/>""; if(i<4) svg+=""<text x='""+(P.l-6)+""' y='""+(y+4).toFixed(1)+""' text-anchor='end' fill='#8B8B8B' style='font-size:12.5px;font-family:Segoe UI,system-ui;font-weight:500'>""+fA(v)+""</text>""; }
			    arr.forEach(function(d,i){
			      var v=Number(d.val)||0;
			      var bh=Math.max(2,(v/mx)*(H-P.t-P.b));
			      var bx=startX+i*(barW+gap);
			      var by=H-P.b-bh;
			      var lx=bx+barW/2;
			      var sub = _modoH==='produto'? (d.grupo||'-') : (d.supervisor||'-');
			      var tt='<b>'+escT(d.nome)+'</b><br>'+lblFn+': '+fmtV(v)+'<br>'+(_modoHM==='rs'?'Peso: '+fA(d.peso||0)+' kg':'Faturamento: '+fMK(d.rs||0))+'<br>Clientes: '+fN(d.clientes||0)+'<br>'+(_modoH==='produto'?'Grupo: ':'Supervisor: ')+escT(sub);
			      svg+=""<rect class='vbar' x='""+bx.toFixed(1)+""' y='""+by.toFixed(1)+""' width='""+barW.toFixed(1)+""' height='""+bh.toFixed(1)+""' rx='3' fill='url(#bg""+uid+"")' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'/>"";
			      svg+=""<text x='""+lx.toFixed(1)+""' y='""+(by-8).toFixed(1)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:11.5px;font-weight:700;font-variant-numeric:tabular-nums;font-family:Segoe UI,system-ui;pointer-events:none'>""+(_modoHM==='rs'?'R$ '+fA(v):fA(v))+""</text>"";
			      var words=d.nome.split(/\s+/);
			      var dw=words.slice(0,4).map(function(w){return w.length>maxWC?w.slice(0,maxWC-2)+'..':w;});
			      var ny=H-P.b+16;
			      dw.forEach(function(w,j){ svg+=""<text x='""+lx.toFixed(1)+""' y='""+(ny+j*14)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:11.5px;font-weight:500;font-family:Segoe UI,system-ui'>""+esc(w)+""</text>""; });
			    });
			    el.innerHTML=""<svg width='""+W+""' height='""+H+""' xmlns='http://www.w3.org/2000/svg'>""+svg+""</svg>"";
			  }
			  var _modoCd='rs';
			  window.setModoCd=function(m){ _modoCd=m; document.querySelectorAll('#cdModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderCidades(); };
			  function renderCidades(){
			    var el=document.getElementById('cidList'); if(!el) return;
			    var data=rJ('jCd')||{rs:[],peso:[]};
			    var arr=(data[_modoCd]||[]).slice(0,15);
			    if(!arr.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Math.max.apply(null,arr.map(function(d){return Number(d.val)||0;}).concat([1]));
			    var fmtV=_modoCd==='rs'?fMK:function(v){return fA(v)+' kg';};
			    el.innerHTML=arr.map(function(d){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      var tt='<b>'+escT(d.nome)+' / '+escT(d.uf||'-')+'</b><br>'+(_modoCd==='rs'?'Faturamento':'Peso')+': '+fmtV(v)+'<br>Clientes: '+fN(d.clientes||0);
			      return ""<div class='bar-row' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'><div class='bar-head'><div class='bar-name'>""+esc(d.nome)+"" <span class='bar-sub'>""+esc(d.uf||'')+""</span></div><div class='bar-val'>""+fmtV(v)+""</div></div><div class='bar-track'><div class='bar-fill' data-w='""+w+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.bar-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  var _modoAtv='rs';
			  window.setModoAtv=function(m){ _modoAtv=m; document.querySelectorAll('#atvModoToggle button').forEach(function(b){ b.classList.toggle('on', b.dataset.m===m); }); renderAtividades(); };
			  function renderAtividades(){
			    var el=document.getElementById('atvList'); if(!el) return;
			    var data=rJ('jAtv')||{rs:[],peso:[]};
			    var arr=(data[_modoAtv]||[]).slice(0,12);
			    if(!arr.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Math.max.apply(null,arr.map(function(d){return Number(d.val)||0;}).concat([1]));
			    var fmtV=_modoAtv==='rs'?fMK:function(v){return fA(v)+' kg';};
			    el.innerHTML=arr.map(function(d){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      var tt='<b>'+escT(d.nome)+'</b><br>'+(_modoAtv==='rs'?'Faturamento':'Peso')+': '+fmtV(v)+'<br>Clientes: '+fN(d.clientes||0);
			      return ""<div class='bar-row' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'><div class='bar-head'><div class='bar-name'>""+esc(d.nome)+""</div><div class='bar-val'>""+fmtV(v)+""</div></div><div class='bar-track'><div class='bar-fill' data-w='""+w+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.bar-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  function renderRoscaCat(){
			    var el=document.getElementById('svgRoscaCat'); if(!el) return;
			    var d=svgDim(el,420,300); var W=d[0],H=d[1];
			    el.setAttribute('viewBox','0 0 '+W+' '+H);
			    var arr=(rJ('jMix')||[]).filter(function(x){return (Number(x.val)||0)>0;});
			    if(!arr.length){ el.innerHTML=""<text x='""+(W/2)+""' y='""+(H/2)+""' text-anchor='middle' fill='#999'>Sem devoluções</text>""; return; }
			    var total=arr.reduce(function(s,x){return s+(Number(x.val)||0);},0); if(total<=0) total=1;
			    var colors={Comercial:'#4A6E8A',Qualidade:'#A04848',Logistica:'#C07C3A','Logística':'#C07C3A',Industria:'#4E7D62','Indústria':'#4E7D62',Administrativo:'#5A5A5A',Fiscal:'#8A6740'};
			    var fallback=['#1A1A1A','#B8935A','#4E7D62','#C07C3A','#4A6E8A','#5A5A5A'];
			    var cx=W*0.32, cy=H/2;
			    var r=Math.min(W*0.26,H*0.40), ri=r*0.58;
			    var start=-Math.PI/2;
			    var svg='';
			    arr.forEach(function(d2,i){
			      var v=Number(d2.val)||0;
			      var ang=(v/total)*Math.PI*2;
			      var end=start+ang;
			      var la=ang>Math.PI?1:0;
			      var x1=cx+r*Math.cos(start), y1=cy+r*Math.sin(start);
			      var x2=cx+r*Math.cos(end),   y2=cy+r*Math.sin(end);
			      var xi1=cx+ri*Math.cos(end), yi1=cy+ri*Math.sin(end);
			      var xi2=cx+ri*Math.cos(start), yi2=cy+ri*Math.sin(start);
			      var dPath='M '+x1.toFixed(2)+' '+y1.toFixed(2)+' A '+r.toFixed(2)+' '+r.toFixed(2)+' 0 '+la+' 1 '+x2.toFixed(2)+' '+y2.toFixed(2)+' L '+xi1.toFixed(2)+' '+yi1.toFixed(2)+' A '+ri.toFixed(2)+' '+ri.toFixed(2)+' 0 '+la+' 0 '+xi2.toFixed(2)+' '+yi2.toFixed(2)+' Z';
			      var pct=(v/total*100).toFixed(1).replace('.',',');
			      var color=colors[d2.nome]||fallback[i%fallback.length];
			      var tt='<b>'+escT(d2.nome)+'</b><br>Devolução: '+fMK(v)+'<br>'+pct+'% do total<br>Tipos: '+fN(d2.qtdTipos||0)+'<br>Clientes: '+fN(d2.clientes||0);
			      svg+=""<path class='donut-slice' d='""+dPath+""' fill='""+color+""' stroke='#FFFFFF' stroke-width='2' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'/>"";
			      start=end;
			    });
			    svg+=""<text x='""+cx+""' y='""+(cy-2)+""' text-anchor='middle' fill='#1A1A1A' style='font-size:22px;font-weight:700;font-family:Segoe UI,system-ui'>""+fMK(total)+""</text>"";
			    svg+=""<text x='""+cx+""' y='""+(cy+16)+""' text-anchor='middle' fill='#8B8B8B' style='font-size:11.5px;font-weight:600;letter-spacing:1.6px;font-family:Segoe UI,system-ui'>DEVOLUÇÃO YUZAP</text>"";
			    var lx=W*0.60;
			    var step=52;
			    var ly=Math.max(28,(H-arr.length*step)/2+12);
			    arr.forEach(function(d2,i){
			      var v=Number(d2.val)||0;
			      var pct=(v/total*100).toFixed(1).replace('.',',');
			      var color=colors[d2.nome]||fallback[i%fallback.length];
			      var y=ly+i*step;
			      svg+=""<rect x='""+lx+""' y='""+(y-12)+""' width='15' height='15' rx='3' fill='""+color+""'/>"";
			      svg+=""<text x='""+(lx+24)+""' y='""+y+""' fill='#1A1A1A' style='font-size:16px;font-weight:700;font-family:Segoe UI,system-ui'>""+esc(d2.nome)+""</text>"";
			      svg+=""<text x='""+(lx+24)+""' y='""+(y+18)+""' style='font-size:13.5px;font-family:Segoe UI,system-ui'><tspan fill='#5A5A5A'>""+fMK(v)+""</tspan> <tspan fill='#B8935A' font-weight='700'>""+pct+""%</tspan></text>"";
			    });
			    el.innerHTML=svg;
			  }"
		displayFolder: HTML Yuzap
		lineageTag: 6c2fda92-66d1-4803-b0ea-8601cfa3bcf3

	/// Parte 3 do JS Yz v2 - acentos e ortografia corrigidos. renderTopMotivos + renderTabela com aba devcliente + renderAll sem renderPorLabel + dataHash sem jLb + IIFE close.
	measure '_JS Yz P3' =
			"  function renderTopMotivos(){
			    var el=document.getElementById('topMotBox'); if(!el) return;
			    var data=(rJ('jMot')||[]).slice(0,10);
			    if(!data.length){ el.innerHTML=""<div style='padding:10px;color:#8B8B8B'>Sem dados</div>""; return; }
			    var mx=Math.max.apply(null,data.map(function(d){return Number(d.val)||0;}).concat([1]));
			    el.innerHTML=data.map(function(d){
			      var v=Number(d.val)||0, w=(v/mx)*100;
			      var clr=catColor(d.categoria);
			      var tt='<b>'+escT(d.nome)+'</b><br>Categoria: '+escT(d.categoria)+'<br>Devolução: '+fMK(v)+'<br>Peso: '+fA(d.peso||0)+' kg<br>Clientes: '+fN(d.clientes||0);
			      return ""<div class='bar-row' onmousemove=\""tip(event,'""+tt+""')\"" onmouseleave='tipOff()'><div class='bar-head'><div class='bar-name'>""+esc(d.nome)+"" <span class='tag-badge tag-mini' style='background:""+clr.bg+"";color:""+clr.fg+""'>""+esc(d.categoria||'-')+""</span></div><div class='bar-val'>""+fMK(v)+""</div></div><div class='bar-track'><div class='bar-fill' data-w='""+w+""'></div></div></div>"";
			    }).join('');
			    setTimeout(function(){ el.querySelectorAll('.bar-fill').forEach(function(f){ f.style.width=f.dataset.w+'%'; }); }, 80);
			  }
			  var _aba='cliente';
			  window.setAba=function(aba){ _aba=aba; document.querySelectorAll('#abasTabs .tab').forEach(function(t){ t.classList.toggle('on', t.dataset.aba===aba); }); renderTabela(); };
			  function renderTabela(){
			    var el=document.getElementById('tabBox'); if(!el) return;
			    var data, cols;
			    if(_aba==='cliente'){ data=rJ('jTc')||[]; cols=[{k:'codigo',t:'Código',cls:'mono'},{k:'cliente',t:'Cliente',cls:'name'},{k:'cidade',t:'Cidade',cls:'name'},{k:'atividade',t:'Atividade',cls:'tag'},{k:'label',t:'Últ. Label',cls:'tag'},{k:'status',t:'Status',cls:'status'},{k:'conversas',t:'Conv.',cls:'num',fmt:fN},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'dev',t:'Devolução R$',cls:'num',fmt:fMK},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct},{k:'diasUltCompra',t:'Dias Últ. Compra',cls:'num',fmt:function(v){var n=Number(v); return n<0?'-':fN(n);}}]; }
			    else if(_aba==='produto'){ data=rJ('jTp')||[]; cols=[{k:'produto',t:'Produto',cls:'name'},{k:'grupo',t:'Grupo',cls:'tag'},{k:'subgrupo',t:'Subgrupo',cls:'tag'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'peso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'clientes',t:'Clientes',cls:'num',fmt:fN},{k:'dev',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else if(_aba==='vendedor'){ data=rJ('jTv')||[]; cols=[{k:'vendedor',t:'Vendedor',cls:'name'},{k:'supervisor',t:'Supervisor',cls:'tag'},{k:'gerente',t:'Gerente',cls:'tag'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'peso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'clientes',t:'Clientes',cls:'num',fmt:fN},{k:'dev',t:'Devolução R$',cls:'num',fmt:fMK},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else if(_aba==='cidade'){ data=rJ('jTcd')||[]; cols=[{k:'cidade',t:'Cidade',cls:'name'},{k:'uf',t:'UF',cls:'tag'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'peso',t:'Peso (kg)',cls:'num',fmt:fA},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN},{k:'clientes',t:'Clientes',cls:'num',fmt:fN},{k:'dev',t:'Devolução R$',cls:'num',fmt:fMK},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct}]; }
			    else { data=rJ('jTdc')||[]; cols=[{k:'codigo',t:'Código',cls:'mono'},{k:'cliente',t:'Cliente',cls:'name'},{k:'cidade',t:'Cidade',cls:'name'},{k:'atividade',t:'Atividade',cls:'tag'},{k:'motivo',t:'Motivo Principal',cls:'name'},{k:'categoria',t:'Categoria',cls:'cat'},{k:'fat',t:'Faturamento',cls:'num',fmt:fMK,bar:true},{k:'dev',t:'Devolução R$',cls:'num',fmt:fMK,bar:true},{k:'pesoDev',t:'Peso Dev (kg)',cls:'num',fmt:fA},{k:'taxaDev',t:'Taxa Dev %',cls:'num',fmt:fPct},{k:'pedidos',t:'Pedidos',cls:'num',fmt:fN}]; }
			    if(!data.length){ el.innerHTML=""<div style='padding:20px;color:#8B8B8B;text-align:center'>Sem dados</div>""; return; }
			    var maxNum={};
			    cols.forEach(function(c){ if(c.cls==='num' && c.bar){ maxNum[c.k]=Math.max.apply(null,data.map(function(d){return Number(d[c.k])||0;}).concat([1])); } });
			    var head=""<thead><tr>""+cols.map(function(c){return ""<th class='th-""+c.cls+""'>""+c.t+""</th>"";}).join('')+""</tr></thead>"";
			    var body=""<tbody>""+data.map(function(d){
			      return ""<tr>""+cols.map(function(c){
			        var v=d[c.k]; var text=c.fmt?c.fmt(v):esc(v);
			        if(c.cls==='num' && c.bar){ var n=Number(v)||0; var pct=Math.max(0,(n/maxNum[c.k])*100); return ""<td class='td-num'><div class='cell-val'>""+text+""</div><div class='cell-bar'><div class='cell-fill' style='width:""+pct.toFixed(1)+""%'></div></div></td>""; }
			        if(c.cls==='tag'){ var clr=tagColor(v); return ""<td class='td-tag'><span class='tag-badge' style='background:""+clr.bg+"";color:""+clr.fg+""'>""+esc(v||'-')+""</span></td>""; }
			        if(c.cls==='cat'){ var clr2=catColor(v); return ""<td class='td-tag'><span class='tag-badge' style='background:""+clr2.bg+"";color:""+clr2.fg+""'>""+esc(v||'-')+""</span></td>""; }
			        if(c.cls==='status'){ var clr3=statusBadge(v); return ""<td class='td-tag'><span class='tag-badge' style='background:""+clr3.bg+"";color:""+clr3.fg+""'>""+esc(v||'-')+""</span></td>""; }
			        if(c.cls==='mono'){ return ""<td class='td-mono'>""+esc(v)+""</td>""; }
			        return ""<td class='td-""+c.cls+""'>""+text+""</td>"";
			      }).join('')+""</tr>"";
			    }).join('')+""</tbody>"";
			    el.innerHTML=""<table class='tbl'>""+head+body+""</table>"";
			  }
			  function renderAll(){
			    if(!document.getElementById('kpiGrid')) return false;
			    try { buildKPIs(); renderFunil(); renderPerdidos(); renderEvolucao(); renderHier(); renderCidades(); renderAtividades(); renderRoscaCat(); renderTopMotivos(); renderTabela(); return true; }
			    catch(e){ console.error(e); return false; }
			  }
			  var _prevHash='';
			  function dataHash(){ return ['jKpi','jFn','jPe','jEv','jHp','jHv','jCd','jAtv','jMix','jMot','jTc','jTp','jTv','jTcd','jTdc'].map(function(id){ var e=document.getElementById(id); if(!e) return ''; return e.textContent.length+'|'+e.textContent.slice(0,20); }).join('~'); }
			  setInterval(function(){ var h=dataHash(); if(h!==_prevHash){ _prevHash=h; renderAll(); } }, 350);
			  var rt;
			  window.addEventListener('resize', function(){ clearTimeout(rt); rt=setTimeout(renderAll,120); });
			  function tryRender(a){ a=a||0; if(renderAll()) return; if(a<25) setTimeout(function(){ tryRender(a+1); }, 100); }
			  if(document.readyState==='loading'){ document.addEventListener('DOMContentLoaded', function(){ tryRender(); }); } else { tryRender(); }
			  window.addEventListener('load', function(){ tryRender(); });
			})();
			"
		displayFolder: HTML Yuzap
		lineageTag: 1e0a0a89-18c6-4a64-a1d0-c4a1488e7068

	/// JS Yz v2 final - concatena P1+P2+P3 em <script>...</script>. Substitui _JS Yz e _JS Yz Fixed. Sem renderPorLabel, com aba devcliente.
	measure '_JS Yz v2' = "<script>" & [_JS Yz P1] & [_JS Yz P2] & [_JS Yz P3] & "</script>"
		displayFolder: HTML Yuzap
		lineageTag: d86bdaa7-de03-4a09-bf4a-1c6bd7d41eca

	partition 'Medidas Visão Executiva' = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

